lib/Makefile.am

Groonga currently includes their header files with <>, and lists the -I flags too late, so the build shall fail if the system has an incompatible version of onigmo/oniguruma or mruby headers installed.

Make sure to use the header files of onigmo in vendor.

---

lib/ii.c

It'll improve performance for searching popular term and rare term such
as "a" and "dacicvs". (I don't know about "dacicvs".)
TODO:
* Benchmark me. We can enable the feature by
GRN_II_CURSOR_SET_MIN_ENABLE=1 environment variable. It's disabled
by default.

Support skip posting list in grn_ii_select()

---

doc/source/contribution/development/release.rst

Because this command must be executed on a single line.
Or we should put a backslash the end of the first line:
% sudo apt-get install -V debootstrap createrepo rpm \
mercurial python-docutils python-jinja2 ...

doc release: don't fold a line

---

include/groonga/Makefile.am

Because following error occcurred in nightly package http://packages.groonga.org/nightly/mariadb-10.0.16-with-mroonga-5.00-for-windows.2015.02.20.zip:
```log
c:\jw\workspace\dmbvc2013\powershell\work\source\storage\mroonga\vendor\groonga\lib\grn_db.h(27):
fatal error C1083: include ファイルを開けません。'groonga/scorer.h':No
such file or directory
(C:\jw\workspace\dmbvc2013\powershell\work\source\storage\mroonga\vendor\groonga\lib\command.c)
[C:\jw\workspace\dmbvc2013\powershell\work\build-vc2013-zip-32\storage\mroonga\vendor\groonga\lib\libgroonga.vcxproj]
```

Add missing scorer.h in packaged source

---

lib/ctx_impl_mrb.c
lib/mrb/mrb_content_type.c
lib/mrb/mrb_content_type.h
lib/mrb/sources.am

#285 のための対応です。レビューをお願いします。
手元では`Groonga::Writer#content_type=`も実装できているので、
これがマージされたらpull requestを出します。

mrb: bind Groonga::ContentType module

---

plugins/token_filters/stop_word.c
test/command/suite/token_filters/stop_word/offline_index_construction.expected
test/command/suite/token_filters/stop_word/offline_index_construction.test

オフラインインデックス構築時はtmp_lexiconで無名テーブルが渡されるので、``is_stop_word``カラム見つからなくてエラーになっちゃうので、``GRN_TOKEN_GET``時以外は、NULLを返すようにしました。

Fix a bug that stop_word plugin use offline index construction

---

vendor/onigmo/Makefile.am

following warning generates building mariadb bundled Mroonga nightly
package:
```log
CMake Warning (dev) at
storage/mroonga/vendor/groonga/vendor/CMakeLists.txt:16
(add_subdirectory):
The source directory
C:/jw/workspace/dmbvc2013/powershell/work/source/storage/mroonga/vendor/groonga/vendor/onigmo
does not contain a CMakeLists.txt file.
CMake does not support this case but it used to work accidentally and is
being allowed for compatibility.
Policy CMP0014 is not set: Input directories must have CMakeLists.txt. Run
"cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

onigmo: add EXTRA_DIST to suppress CMP0014 warning

---

configure.ac

bash's "source" command extension is not in POSIX.2 standard.  Use
. (dot) command to be worked on non-bash environment (like FreeBSD).

Use . (dot) rather than source to be compat with POSIX.2.

---

lib/token_cursor.c
test/command/suite/tokenizers/trigram/force_prefix/multiple_tokens/unmatured_two_characters.expected
test/command/suite/tokenizers/trigram/force_prefix/single_token/unmatured_two_characters.expected

現在、GroongaではTokenBigramで最後のトークン(TOKEN_LAST)が1文字トークン(UNMATURED)の場合、強制前方一致フラグtoken_cursor->force_prefixが設定されることにより、1文字トークンで検索される場合でも勝手にうまくヒットするようになっています。
* TokenBigramの例
-  クエリ：で -> [で]  
-  本文：文章です -> [文章/章で/です/す]
-  "で" というトークンは存在しないため前方一致が必要
しかし、TokenTrigramにすると2文字トークンは最後のトークンでないため(以下の例では最後のトークンは章）、強制前方一致フラグが設定されず、2文字トークンを含むとうまくヒットしなくなります。
* TokenTrigramの例
- クエリ：文章 -> [文章/章]
- 本文：文章です -> [文章で/章です/です/す]  
- "文章" というトークンは存在しないため前方一致が必要
そこで、UNMATUREDトークンの場合、TOKEN_LASTではなくトークンの最後の文字がクエリの末尾であることを示すTOKEN_REACH_ENDの場合に強制前方一致フラグを設定するようにしてやれば、TokenTrigramの場合に2文字トークンが含まれても勝手にうまくヒットするようになると思います。
よければご検討ください。

Support force prefix search when unmatured token is 2 characters or more

---

lib/db.c

In Rroonga, a test is failing:
```
=========================================================================================================
Failure: test_new(DatabaseTest)
/home/myokoym/work/groonga/rroonga/test/test-database.rb:73:in `test_new'
70:   end
71: 
72:   def test_new
=> 73:     assert_raise(Groonga::NoSuchFileOrDirectory) do
74:       new_context = Groonga::Context.new
75:       Groonga::Database.new(@database_path.to_s, :context => new_context)
76:     end
<Groonga::NoSuchFileOrDirectory> expected but was
<Groonga::InvalidArgument(<invalid argument: [db][open] invalid keys table's type: 0: #<Groonga::Database>
db.c:272: grn_db_open()>)>
diff:
? Groonga::N                                       oSuchFi               leO              r       Dir    ectory
? …
```

Don't override error

---

packages/debian/groonga-httpd.service
packages/debian/groonga-server-gqtp.service

I think that using `Wants=network-online.target` is more suitable for Groonga's server functionality.
Because systemd's manpage says:
network-online.target is a target that actively waits until the nework is "up", 
where the definition of "up" is defined by the network management software. 
Usually it indicates a configured, routable IP address of some kind.
ref: http://www.freedesktop.org/software/systemd/man/systemd.special.html#network-online.target

debian: Use network-online.target to wait configured network strictly

---

lib/com.c

this fixes the following build error with musl libc:
lib/com.c: In function 'grn_com_event_add':
lib/com.c:351:17: error: '__uint32_t' undeclared
(first use in this function)
e.events = (__uint32_t) events;
^
fixes #375

use standard uint32_t instead of non-standard __uint32_t

---

doc/source/conf.py

#367 
CLEANED!! :sparkles: 
```
$ make -C doc html
(snip)
copying static files... done
copying extra files... done
dumping search index in Japanese (code: ja) ... done
dumping object inventory... done
build succeeded, 2 warnings.
(snip)
```
2 warnings mean ...
```
groonga/doc/source/reference/cast.rst:: WARNING: document isn't included in any toctree
groonga/doc/source/reference/scoring_note.rst:: WARNING: document isn't included in any toctree
```
Now I ignore. :confused:

Remove resolved todo

---

lib/grn_report.h

This missing extern causes following error in OSX:
```log
...
2403 warnings generated.
CXXLD    libgroonga.la
duplicate symbol _GRN_REPORT_INDEX_LOG_LEVEL in:
.libs/db.o
.libs/expr.o
duplicate symbol _GRN_REPORT_INDEX_LOG_LEVEL in:
.libs/db.o
.libs/report.o
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [libgroonga.la] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Add missing extern to variable in header

---

doc/source/example/reference/commands/select/query_expander_substitution_table.log
doc/source/example/reference/commands/select/usage_setup.log
doc/source/example/reference/functions/query/usage_setup_schema.log
doc/source/example/reference/functions/snippet_html/usage_setup.log
doc/source/example/reference/grn_expr/query_syntax/setup.log
doc/source/example/reference/grn_expr/script_syntax/simple_term_extract_operator.log
doc/source/example/reference/indexing-schema.log
doc/source/troubleshooting/different_results_with_the_same_keyword.rst

これで一通りKEY_NORMALIZEは潰せたような..
ところで、
[7.3.44.4.5. default_tokenizer](http://groonga.org/ja/docs/reference/commands/table_create.html#key-type)
``デフォルト値はありません。``とありますが、
doc/source/example/reference/commands/select/query_expander_substitution_table.log
には、
```
table_create Thesaurus TABLE_PAT_KEY|KEY_NORMALIZE ShortText
```
とトークナイザを指定していないものがありますね。
次のように書き換えて問題なさそうだったのでdefault_tokenizerは未指定です。
```
table_create Thesaurus TABLE_PAT_KEY ShortText --normalizer NormalizerAuto
```
補足(2015/08/26 19:16)
次のどちらかが良いように思います。
* default_tokenizerは必ず指定する。(デフォルト値はありません。が正しい場合)
* 未指定の場合、XXになると表現を変える(デフォルト値がある場合)

doc: replace deprecated option (KEY_NORMALIZE)

---

configure.ac

This configure.ac is extreme slow on libtool-2.4.6.
From libtool mailing list.
You can workaround/fix this by:
-m4_define([nginx_version], m4_include(nginx_version))
-NGINX_VERSION=nginx_version
+NGINX_VERSION=m4_include([nginx_version])
See also.
http://lists.gnu.org/archive/html/libtool/2015-09/msg00004.html

Fix autogen.sh extream slow.

---

autogen.sh

Please review this patch.
If multiple gettext package installed,
Following statement does not work properly.
if [ -d $gettext_aclocal ]; then
ACLOCAL_ARGS="$ACLOCAL_ARGS -I $gettext_aclocal"
fi
./autogen.sh: line 12: [: /usr/local/Cellar/gettext/0.19.4/share/aclocal: binary operator expected
echo /usr/local/Cellar/gettext/*/share/aclocal
/usr/local/Cellar/gettext/0.19.4/share/aclocal /usr/local/Cellar/gettext/0.19.5.1/share/aclocal

Fix binary operator expected.

---

lib/ctx.c
lib/db.c
lib/grn_ctx_impl.h
lib/grn_db.h
test/unit/core/test-column.c

Use cases:
* Named output columns in select like "AS" in SQL
* Creating a column to temporary table and assigning return value
of function to the column:
select --filter all_records() \
--column[snippet].type ShortText \
--column[snippet].value 'snippet_html(body)' \
--output_columns _id,snippet
* Drilldown by computed value
* Select -> Create temporary column -> Compute value -> Drilldown:
select --filter all_records() \
--column[year].type UInt8 \
--column[year].value 'time_to_year(updated_at)' \
--drilldown year

Support columns for temporary table

---

doc/locale/ja/LC_MESSAGES/reference.po

一部英語のままなので修正です。
作成した修正は、「擬似カラム 擬似カラム以外のすべてと表示されてしまう気がします。
適宜修正をお願いします。

doc ja: write output_columns '*' description

---

lib/pat.c

I'm not sure whether this is a bug or not.
It seems strange that `pat->n_entries` is incremented when `_grn_pat_add()` returns `GRN_ID_NIL`. In the case, it seems that `_grn_pat_add()` doesn't add a new record.
@daijiro Could you confirm it?

pat: fix unexpected count up

---

tools/travis-install.sh

pkg-config 0.29 was merged in Homebrew 4 days ago.
This causes test failure on Travis CI's OSX instances.
When pkg-config 0.28 is installed on OS X with Homebrew
and then installing pkg-config 0.29:
NG:
``` bash
$ brew install pkg-config
```
OK:
```bash
$ brew unlink pkg-config
$ brew install pkg-config
```
or users can install pkg-config with `brew upgrade pkg-config`.
Above commands are tested on my MacBook '12 El Capitan.

travis: use latest pkg-config on Travis CI's OS X instances

---

lib/grn_hash.h
lib/grn_pat.h
lib/hash.c
lib/pat.c

These commits fix an issue that a table created with `TABLE_NO_KEY`, `TABLE_HASH_KEY` or `TABLE_PAT_KEY` cannot detect `truncate` by another process ( #447 ).
These commits add a flag named `truncated` (default: `false`) to headers of `grn_array`, `grn_hash` and `grn_pat`.
When a process truncates a table, the process set `true` to the `truncated` flag before removing associated files so that other processes can detect it.

Detect truncate by another process

---

lib/pat.c

I'm not sure but it seems ``grn_pat_inspect_node`` doesn't output all available nodes.
For example, In the following code, doesn't output "c" node.
```c
#include <stdio.h>
#include <string.h>
#include <groonga.h>
int
main(int argc, char **argv)
{
grn_ctx ctx;
grn_obj *db, *table;
grn_id id;
grn_obj *result;
const char *path = "test.grn";
grn_init();
grn_ctx_init(&ctx, 0);
db = grn_db_open(&ctx, path);
if (!db) { db = grn_db_create(&ctx, path, NULL); }
table = grn_table_create(&ctx, NULL, 0,
NULL,
GRN_OBJ_TABLE_PAT_KEY,
grn_ctx_at(&ctx, GRN_DB_SHORT_TEXT), NULL);
grn_table_add(&ctx, table, "b", strlen("b"), NULL);
grn_table_add(&ctx, table, "c", strlen("c"), NULL);
grn_table_add(&ctx, table, "ca", strlen("ca"), NULL);
grn_p(&ctx, table);
/*
before
#<table:pat (nil) key:ShortText …
```

pat_inspect_node: output all available nodes

---

plugins/functions/CMakeLists.txt
plugins/functions/Makefile.am
plugins/functions/string.c
plugins/functions/string_sources.am
test/command/suite/select/function/string/string_length/en.expected
test/command/suite/select/function/string/string_length/en.test
test/command/suite/select/function/string/string_length/ja.expected
test/command/suite/select/function/string/string_length/ja.test

I want to filter with charctor length as following.
```
select Users --filter 'char_length(name) == 2' --output_columns 'name' --command_version 2
```

plugin functions/char: add char_length()

---

lib/grn_pat.h
lib/pat.c
test/unit/core/test-patricia-trie-search.c

パトリシアトライを使って**キー**の高速なあいまい検索を実装してみました。
これを取り込んでもよさそうでしたら、grn_obj_searchで転置索引に対してfuzzy_searchを使えるようにして、selector関数を作りたいと思っています。
以下の検証プログラムでwikipediaタイトル1万件のgrn_pat_fuzzyの結果がレコードごとに編集距離を求めた場合の結果と数が同じになることを確認しています。
https://gist.github.com/naoa/934da65118b7bbc99178
よければご検討をお願いします。
```c
grn_rc grn_pat_fuzzy_search(grn_ctx *ctx, grn_pat *pat,
const void *key, unsigned int key_size, unsigned int max_size,
unsigned int max_distance, int flags, grn_hash *h);
```
keyとの編集距離がmax_distance以下であるキーのIDをhashにセットする。
max_distance: 取得対象とする最大の編集距離。この値が小さいほど多くの処理をスキップできて高速。
max_size: 前方一致検索する文字数。
flags: WITH_TRANSPOSITIONをつけると、並び替えのコストが1になる
高速化の主要なポイントは以下の２つです。
1. できるだけ同じ接頭辞の部分の計算結果を使い回す
2. 求めたい最大編集距離のパラメータを渡すことにより、最大編集距離以下にならないことが確定した時点でその子ノードの探索、編集距離演算をスキップする …

pat: Add grn_pat_fuzzy_search()

---

lib/proc/proc_fuzzy_search.c
test/command/suite/select/function/fuzzy_search/index/and.expected
test/command/suite/select/function/fuzzy_search/index/and.test
test/command/suite/select/function/fuzzy_search/index/hash.expected
test/command/suite/select/function/fuzzy_search/index/or.expected
test/command/suite/select/function/fuzzy_search/index/or.test
test/command/suite/select/function/fuzzy_search/sequential/max_distance.expected
test/command/suite/select/function/fuzzy_search/sequential/prefix_length_ja.expected
test/command/suite/select/function/fuzzy_search/sequential/reference.expected
test/command/suite/select/function/fuzzy_search/sequential/reference_vector.expected
test/command/suite/select/function/fuzzy_search/sequential/text.expected
test/command/suite/select/function/fuzzy_search/sequential/vector.expected

シーケンシャルのfuzzy_searchについて新しい一時テーブルと集合演算するのではなく、結果テーブルのpostingを追加するようにしました。

Proc fuzzy use same res

---

lib/proc/proc_fuzzy_search.c

すいません、途中のエラーケースのリターンでメモリ解放漏れがありました

proc_fuzzy_search: fix memory leak when memory couldn't allocated

---

lib/ii.c
lib/pat.c
test/command/suite/select/function/fuzzy_search/index/index.expected
test/command/suite/select/function/fuzzy_search/index/index_column.expected
test/command/suite/select/function/fuzzy_search/index/index_with_tokenizer.expected
test/command/suite/select/function/fuzzy_search/pat/max_distance.expected
test/command/suite/select/function/fuzzy_search/pat/max_expansion.expected
test/command/suite/select/function/fuzzy_search/pat/pat.expected
test/command/suite/select/function/fuzzy_search/pat/prefix_length.expected
test/command/suite/select/function/fuzzy_search/pat/prefix_length_ja.expected

[[groonga-dev,03916]](https://osdn.jp/projects/groonga/lists/archive/dev/2016-February/003919.html)
２．編集距離に応じてトークンの重み付けをする。
の方の実装です。
編集距離を他のマッチスコアとなじませるためにmax_distance - edit_distance + 1としてみました。
同じ文字列(編集距離が0)がmax_distance + 1になります。
遠くなるほどスコアが下がり、最も遠いのが1です。
よければ、ご検討ください。
もし、１．の方が望ましければ閉じてください。

Change how to calculate score of fuzzy_search

---

lib/ii.c
test/command/suite/select/function/fuzzy_search/index/index.expected
test/command/suite/select/function/fuzzy_search/index/index.test
test/command/suite/select/function/fuzzy_search/index/index_with_tokenizer.expected
test/command/suite/select/function/fuzzy_search/index/index_with_tokenizer.test
test/command/suite/select/function/fuzzy_search/index/vector.expected
test/command/suite/select/function/fuzzy_search/index/vector.test

すいません。トークンごとに重みを設定するためにpostingの重みを使うと、全レコードのpostingに重みを設定する必要があって現実的ではありませんでした。。
そこで、grn_ii_cursorに新しくweightのメンバーを追加してtokenごとに同じ重みを適用できるようにしました。（このぐらいしか思いつきませんでした。。）
今後の拡張として、通常の全文検索でもlexiconに重みカラムを置いておいてそれを適用するようなこともできるかもしれません。
この実装方法はいかがでしょうか？
APIが変わってしまいますが、ii_cursor_openに引数weightを増やして設定するほうが自然かもしれません。
既存への影響を考えてこれは受け入れられず、fuzzyではトークンごとの重みを適用しないでも構いません。
その場合はこちら。(revert版 距離は関係なくマッチすれば1)
https://github.com/naoa/groonga/tree/revert-fuzzy-weight
よければ、ご検討ください。

Fix fuzzy weight

---

lib/proc.c
test/command/suite/column_remove/nonexistent.expected
test/command/suite/column_remove/nonexistent.test

I improved error messages in `column_remove` command. I referred to [`column_rename`](https://github.com/groonga/groonga/blob/master/lib/proc.c#L1480) command.

column_remove: show more detail in error message

---

lib/db.c
lib/grn_db.h
lib/ii.c
test/command/suite/select/function/fuzzy_search/pat/and.expected
test/command/suite/select/function/fuzzy_search/pat/and.test
test/command/suite/select/function/fuzzy_search/pat/or.expected
test/command/suite/select/function/fuzzy_search/pat/or.test

TABLE_PATの_keyを直接指定したときのオペレータが反映できていませんでした。
インデックスでキーの列挙だけで使われるときにも、pat_fuzzy_searchとsetoperationで２回ループになって無駄になりそうなので、結果テーブルが0件、且つ、OP_ORのときはsetoperationをしないようにしています。
よければ、ご検討ください。

grn_table_fuzzy_search() support operator

---

lib/grn_proc.h
lib/proc.c
lib/proc/proc_snippet.c
lib/proc/sources.am
test/command/suite/select/function/snippet_full/cache.expected
test/command/suite/select/function/snippet_full/cache.test
test/command/suite/select/function/snippet_full/default.expected
test/command/suite/select/function/snippet_full/default.test
test/command/suite/select/function/snippet_full/default_tag.expected
test/command/suite/select/function/snippet_full/default_tag.test
test/command/suite/select/function/snippet_full/html_escape.expected
test/command/suite/select/function/snippet_full/html_escape.test
test/command/suite/select/function/snippet_full/leading_space.expected
test/command/suite/select/function/snippet_full/leading_space.test
test/command/suite/select/function/snippet_full/max_results.expected
test/command/suite/select/function/snippet_full/max_results.test
test/command/suite/select/function/snippet_full/normalizer.expected
test/command/suite/select/function/snippet_full/normalizer.test
test/command/suite/select/function/snippet_full/prefix.expected
test/command/suite/select/function/snippet_full/prefix.test
test/command/suite/select/function/snippet_full/suffix.expected
test/command/suite/select/function/snippet_full/suffix.test
test/command/suite/select/function/snippet_full/twice_keyword.expected
test/command/suite/select/function/snippet_full/twice_keyword.test

object literal形式のオプションを使ってフルスペックのsnippet_full関数を実装しました。
snippet_htmlでconditionからキーワードを引っ張る場合、filterのキーワードもすべてひっぱちゃうので、queryだけのものをスニペットしたいときなどに有用です。
default_open_tagとdefault_close_tagオプションがある場合は、後ろにN個のキーワード並べます。
```
snippet_full(string_or_column, {option}, [keyword1,keyword2...] )
```
default_open_tagとdefault_close_tagオプションがない場合は、後ろにキーワードと開始タグと終了タグの３つセットで並べます。
```
snippet_full(string_or_column, {option},
[keyword1,open_tag1, close_tag1, keyword2, open_tag2, close_tag2...] )
```
* option
| property            | description                                                | default        |
|---------------------|------------------------------------------------------------|----------------|
| width               | スニペットサイズ                                       | 200            |
| …

Snippet full

---

lib/proc/proc_snippet.c
test/command/suite/select/function/snippet_full/no_normalizer.expected
test/command/suite/select/function/snippet_full/no_normalizer.test

snippet関数でデフォルトはNormalizerAutoとしたのですが、```{"normalizer": ""}```でNormalizerを使用しないこともできるようにしたいと思いました。

snippet_full: allow doesn't use any normalizer

---

lib/proc/proc_fuzzy_search.c
lib/proc/proc_highlight.c

他の環境でビルドしてきづきました。
```
proc_fuzzy_search.c:327:21: warning: 'hash' may be used uninitialized in this function [-Wmaybe-uninitialized]
```
warningの抑止とスタイルなど非常にこまごました修正です。

suppress warning message for fuzzy search etc

---

include/groonga/groonga.h
lib/db.c
lib/dump.c
lib/grn_hash.h
lib/hash.c
lib/proc/proc_table.c
test/command/suite/dump/schema/table/hash/key_large_flag.expected
test/command/suite/dump/schema/table/hash/key_large_flag.test
test/command/suite/table_create/key_large/hash_key.expected
test/command/suite/table_create/key_large/hash_key.test
test/command/suite/table_create/key_large/patricia_trie.expected
test/command/suite/table_create/key_large/patricia_trie.test

If you add KEY_LARGE flag to table:
table_create Users TABLE_HASH_KEY|KEY_LARGE ShortText
you can put many keys to the table. By default, 4GiB is the max total
key size. With KEY_LARGE flag, 1TiB is the max total key size. Because
4KiB * (2 ** 28 - 1) < 1TiB. ((2 ** 28 - 1) is the max number of records
in a table.)
It doesn't break backward compatibility. You can use the existing
database without dump and restore.

hash: support 4GiB over total key size

---

doc/source/contribution/development/release.rst

doc ja: fix a typo

---

lib/proc/proc_select.c
test/command/suite/select/drilldown/labeled/table/cyclic.expected
test/command/suite/select/drilldown/labeled/table/cyclic.test
test/command/suite/select/drilldown/labeled/table/empty.expected
test/command/suite/select/drilldown/labeled/table/empty.test
test/command/suite/select/drilldown/labeled/table/one.expected
test/command/suite/select/drilldown/labeled/table/one.test
test/command/suite/select/drilldown/labeled/table/two.expected
test/command/suite/select/drilldown/labeled/table/two.test
test/command/suite/select/drilldown/labeled/table/unordered.expected
test/command/suite/select/drilldown/labeled/table/unordered.test

[groonga-dev 3903](https://osdn.jp/projects/groonga/lists/archive/dev/2016-February/003903.html)　のうち、まず、
> --drilldown[...].tableで他の--drilldown[...]の「...」に指定
> したドリルダウン結果を指定できることと
を実装してみました。よければご検討ください。
CI環境でテストが落ちているので調査しています。
```bash
select Memos   \
--drilldown[tag].keys tag  \
--drilldown[tag].output_columns _key,_nsubrecs,category  \
--drilldown[category].table tag \
--drilldown[category].keys category \
--drilldown[category].output_columns _key,_nsubrecs,sub_category \
--drilldown[sub_category].table category \
--drilldown[sub_category].keys sub_category \
--drilldown[sub_category].output_columns _key,_nsubrecs
[
...
{
"tag": [
[3],
[
["_key", "ShortText"],
["_nsubrecs", "Int32"],
["category","Categories"]
],
[
"Groonga",
2,
"C/C++"
],
[
"Mroonga",
1,
"C/C++"
],
[
"Rroonga",
1, …
```

drilldown: support specifying grouped table

---

lib/proc/proc_select.c

すいません。drilldownsでmallocした後のエラーチェックに漏れがありました。

select drilldown: add missing error check for memory allocation

---

lib/db.c

grn_testでleakってでいなかったのでどっかで回収されているかもしれませんが、``grn_table_group_single_key_records()``ではcalc_targetのためにGRN_VOID_INITしたvalue_bufferをGRN_OBJ_FINしていないように見えました。（他は大丈夫）

db: fix memory leak in grn_table_group_single_key_records

---

lib/db.c
lib/proc/proc_select.c
test/command/suite/select/drilldown/labeled/all_records/no_table.expected
test/command/suite/select/drilldown/labeled/all_records/no_table.test
test/command/suite/select/drilldown/labeled/all_records/sum.expected
test/command/suite/select/drilldown/labeled/all_records/sum.test

[groonga-dev 3903](https://osdn.jp/projects/groonga/lists/archive/dev/2016-February/003903.html)　の、
> --drilldown[...].keysを省略できること
を実装してみました。
モチベーションは、円グラフを書くためにベクターカラムのドリルダウン結果の_nsubrecsの合計値を取得したいことです。
キー数が0、calc_targetがあって、かつ、n_resultsが1の場合、"all_records"というキー名ですべてのレコードをgroupするモードを```grn_table_group()```APIに追加しました。
よければご検討ください。
```bash
select Memos  \
--drilldown[tag].keys tag \
--drilldown[tag_sum].table tag \
--drilldown[tag_sum].calc_types SUM \
--drilldown[tag_sum].calc_target _nsubrecs \
--drilldown[tag_sum].output_columns _key,_sum
[
...
{
"tag": [
[3],
[
["_key", "ShortText"],
["_nsubrecs","Int32"]
],
[
"Groonga",
2
],
[
"Mroonga",
1
],
[
"Rroonga",
1
]
],
"tag_sum": [
[1],
[
[ "_key","ShortText"],
[ "_sum","Int64"]
],
[
"all_records",
4
]
]
}
]
]
```

drilldown: support group by all records

---

.gitignore
build/makefiles/gettext.am
build/makefiles/sphinx-build.am
doc/Makefile.am
doc/locale/Makefile.am

少し前の 6f8eb65ff290e80b02f1541e04ab1f1208a3f10d と 2e91a753e48ed4e8de524eb4e535bbd502801125 の関連です。
この部分も多分不要じゃないかと思うので、気づいたついでに上げておきます。

sphinx: support only HTML output

---

doc/locale/ja/LC_MESSAGES/reference.po
doc/source/reference/commands/table_tokenize.rst

とても簡素ですが存在があるだけでも示した方がよいと思って、追加した``table_tokenize``の``index_column``オプション項目を追加しました。
なんかたくさん書き換わりました。

doc table_tokenize: add index_column option

---

lib/proc/proc_select.c
test/command/suite/select/column/stage/filtered/filter.expected
test/command/suite/select/column/stage/filtered/filter.test

現在、動的カラムのRECORDのidは、resultテーブルのidでなく、元の実テーブルのidを辿っていると思うのですが、これはresultのidで良いのではないですか？
以下は本パッチ前の結果です。valueでの``_id``が0になってしまっています。
```bash
table_create Items TABLE_HASH_KEY ShortText
[[0,0.0,0.0],true]
column_create Items price COLUMN_SCALAR UInt32
[[0,0.0,0.0],true]
load --table Items
[
{"_key": "Book",  "price": 1498},
{"_key": "Food",  "price": 1198},
{"_key": "Drink", "price": 600}
]
[[0,0.0,0.0],3]
select Items   --filter 'price < 1200'   \
--output_columns _id,_key,price,filtered   \
--column[filtered].stage filtered   \
--column[filtered].type UInt32   \
--column[filtered].flags COLUMN_SCALAR \ 
--column[filtered].value '_id'
[
[
0,
0.0,
0.0
],
[
[
[
2
],
[
[
"_id",
"UInt32"
],
[
"_key",
"ShortText"
],
[
"price",
"UInt32"
],
[
"filtered",
"UInt32"
]
],
[
2,
"Food",
1198,
0
],
[
3, …
```

Don't resolve record id on dynamic column

---

lib/proc/proc_select.c

#540 より分割
まずは、ドリルダウン結果で動的カラムを作るコードを流用するために、コードの移動と抽出だけのコミットにしました。

Extract dynamic column related functions

---

lib/dat.cpp
lib/db.c
lib/grn_dat.h
lib/grn_pat.h
lib/pat.c

It doesn't increase no overhead when the database isn't changed. For
example, you have no overhead and no change when you only use select
command.
It doesn't flush many times. It flushes only at the first database
change.

Support detecting changed database isn't closed

---

lib/db.c
test/command/suite/select/drilldown/labeled/column/stage/initial/drilldown.expected
test/command/suite/select/drilldown/labeled/column/stage/initial/drilldown.test

grn_table_sort_key_closeで動的カラムが解放されてしまうのを回避します。

Don't unlink dynamic column in grn_table_sort_key_close

---

lib/ii.c
lib/tokenizers.c
test/command/suite/select/env/overlap_token_skip/long.expected
test/command/suite/select/env/overlap_token_skip/long.test
test/command/suite/select/env/overlap_token_skip/non_overlap.expected
test/command/suite/select/env/overlap_token_skip/non_overlap.test
test/command/suite/select/env/overlap_token_skip/one.expected
test/command/suite/select/env/overlap_token_skip/one.test
test/command/suite/select/env/overlap_token_skip/short.expected
test/command/suite/select/env/overlap_token_skip/short.test
test/command/suite/select/env/overlap_token_skip/skip.expected
test/command/suite/select/env/overlap_token_skip/skip.test
test/command/suite/tokenizers/bigram/env/remove_blank_disable/include_blank.expected
test/command/suite/tokenizers/bigram/env/remove_blank_disable/include_blank.test

iiのチャンクを分割して構築した場合のカーソルスキップの効果を有効的に保ちつつ、Ngramトークナイザーを
高速化するため、token_info_buildでレアトークンを優先的に選択しながらオーバラップトークンをスキップする処理を実装してみました。
環境変数``GRN_II_OVERLAP_TOKEN_SKIP_ENABLE``で有効になります。
実装の大まかな流れは以下のとおりです。
* トークナイズしたトークンとestimate_sizeを一旦全部取得する。
* 隙間なく遷移するように隣接リストでグラフを構築する。(オーバラップトークンか次の隣接トークン)
* グラフを幅優先探索で文頭から末尾までのトークン数が最少になる経路+1の経路のうち、sum(max_estiamted_size / estimated_size)が最も大きくなる(レア度が高い)経路を選ぶ。
ここで最少+1としたのは、TokenBigramでトークンが偶数個の場合、最短経路が一意に決まってしまうためです。
探索は幅優先探索で組み合わせ数が多くなりすぎないように16トークン単位ごとに行っています。
Bigramで16であれば、1000組み合わせ程度で全文検索にはほとんど影響しないと思います。(たぶん。32ごとだと10万組み合わせぐらい)
メモリ節約の観点と実装が簡単だったのでノードの組み合わせ候補をuint32_tのビット位置で表現しています。
以下のような極端なレアトークンがないフレーズでは、スキップしないものより1.5倍程度高速になります。
* 検索フレーズ:「情報処理システム」トークナイザー:TokenBigram
* 情報:0:1130550 / 報処:1:92306 / 処理:2:1475958 / 理シ:3:95071 /シス:4:928786 /ステ:5:1852329 / …

ii: skip overlapping tokens in consideration of frequency of token

---

lib/grn_token_cursor.h
lib/token_cursor.c

GitHub: #556
grn_procのuser_dataにトークンフィルター内でmallocしたアドレスを持たせるのではなく、grn_token_cursorに持たせるようにしてみました。
このパッチ適用後では、issueの再現手順でダブルフリーが発生しなくなることを確認しています。

token_filter: fix thread unsafe code

---

lib/mrb/scripts/expression_tree_builder.rb
test/mruby/suite/expression_rewriter/test_between.rb

functionを持っているgrn_exprでもexpression_rewriterを動かせるようにしたいです。
以下のGroongaコマンドで確認しました。
https://gist.github.com/naoa/7b9282c52ade55ec7fd1250bda0600d0
本パッチ適用前の場合、
```bash
select Users --filter 'query("_key", "ali*") && age > 17 && age < 20'
[
[
[
-22,
0.0,
0.0
],
"undefined method 'value' for #<Groonga::Procedure:0x1317e00>"
]
]
#|e| NoMethodError: undefined method 'value' for #<Groonga::Procedure:0x1317e00>
```
となっていましたが、本パッチ適用後はクエリが正しく通るようになります。

expression_tree_builder: support expression having function

---

lib/mrb/scripts/expression_tree.rb
lib/mrb/scripts/expression_tree/index_column.rb
lib/mrb/scripts/expression_tree/sources.am
lib/mrb/scripts/expression_tree_builder.rb
test/mruby/suite/expression_rewriter/test_between.rb

IndexColumnがある場合でもExpressionTreeBuilderを落ちないようにしたいです。
とりあえず私の当面の目的は、私の使う予定のある構文でExpressionTreeBuilderが落ちないようにして、検索ワードに応じて使うインデックスをすげ替えるexpression-rewriterプラグインが動くようにしたいです。
https://github.com/naoa/groonga-index-selector
あと、AccesorとHashTableが指定された場合に落ちることがわかっています。

expression_tree: add IndexColumn

---

lib/proc/proc_select.c
test/command/suite/select/columns/stage/output/limit.expected
test/command/suite/select/columns/stage/output/limit.test
test/command/suite/select/columns/stage/output/no_sort_keys.expected
test/command/suite/select/columns/stage/output/no_sort_keys.test

関数の名前付けのために動的カラムを使いたかったのですが、filteredステージよりもoutputステージで使った方が速度劣化を抑えられそうでしたので実装してみました。ご確認ください。

select: support dynamic column as output stage

---

doc/locale/ja/LC_MESSAGES/news.po

```log
dirlldown_filter ->
drilldown_filter
^^
```

doc news ja: Fix a typo

---

examples/dictionary/edict/edict-import.sh

OSXの`zcat`コマンドではシェルスクリプト実行時にエラーとなるため、`gzcat`コマンドで代用できるようにしたい。

Use `gzcat` instead of `zcat` if exists.

---

lib/db.c

``grn_table_create``で、```TABLE_NO_KEY```以外が指定された場合、keyの存在チェックをしたほうがいいと思ったのですがいかがでしょうか？
以下のコマンドが正常に通って、なんで検索できないか気づくのに少し時間がかかりました。
```
table_create Lexicon TABLE_PAT_KEY --default_tokenizer TokenDelimit
[[0,0.0,0.0],true]
table_create Entries TABLE_NO_KEY
[[0,0.0,0.0],true]
column_create Entries title COLUMN_SCALAR ShortText
[[0,0.0,0.0],true]
column_create Lexicon title COLUMN_INDEX|WITH_POSITION Entries title
[[0,0.0,0.0],true]
load --table Entries
[
{"title": "Groonga and MySQL"}
]
[[0,0.0,0.0],1]
select Entries   --filter 'title @ "MySQL"'
[[0,0.0,0.0],[[[0],[["_id","UInt32"],["title","ShortText"]]]]]
```

db: validate key_type existance when table type is not TABLE_NO_KEY

---

lib/db.c

Reverts groonga/groonga#570
It also disables creating a result set table. It's not acceptable.

Revert "db: validate key_type existance when table type is not TABLE_NO_KEY"

---

lib/db.c

grn_proc_create 関数の冒頭で、ctx->impl を NULL チェックしているにも関わらず、
その手前で plugin_path メンバを参照しています。

Null-check should precede dereference

---

lib/grn_ecmascript.lemon
test/command/suite/select/function/fuzzy_search/with_logical_operation.expected
test/command/suite/select/function/fuzzy_search/with_logical_operation.test

fix #584
オブジェクトリテラル形式のオプションを使うとgrn_expr_dfiがずれていて、複数の論理演算のときにうまくscan_infoを構築できていませんでしたので、修正しました。
なお、ubuntu16.04を入れてlemon 3.11を使ってみたのですが、grn_ecmascript.c が激しく書き換わってしまいました。
後で更新をお願いできますでしょうか。

fix a bug object literal expression codes is broken

---

plugins/functions/vector.c
test/command/suite/select/function/vector/vector_slice/from.expected
test/command/suite/select/function/vector/vector_slice/from.test
test/command/suite/select/function/vector/vector_slice/negative_from.expected
test/command/suite/select/function/vector/vector_slice/negative_from.test
test/command/suite/select/function/vector/vector_slice/negative_length.expected
test/command/suite/select/function/vector/vector_slice/negative_length.test
test/command/suite/select/function/vector/vector_slice/no_length.expected
test/command/suite/select/function/vector/vector_slice/no_length.test
test/command/suite/select/function/vector/vector_slice/over_length.expected
test/command/suite/select/function/vector/vector_slice/over_length.test
test/command/suite/select/function/vector/vector_slice/reference_vector.expected
test/command/suite/select/function/vector/vector_slice/reference_vector.test
test/command/suite/select/function/vector/vector_slice/vector.expected
test/command/suite/select/function/vector/vector_slice/vector.test
test/command/suite/select/function/vector/vector_slice/weight_reference_vector.expected
test/command/suite/select/function/vector/vector_slice/weight_reference_vector.test

ベクターから要素を抽出する関数が欲しいです。
具体的には、文書から抽出した特徴語を２００次元ほどの重み付きリファレンスベクターに入れているのですが、それをサジェストワードに使うために上位10個ほどを抽出する目的に使いたいです。
第二引数fromに負の値を指定して後ろ１個だけ指定などをし易そうだったので、第三引数はlength(要素数)にしました。
他の方が良いなどの意見があればお願いします。
```
vector_slice(vector, from*[, length])
```
*fromは0 origin
* PostgreSQL
ARRAY[start:end]
1 origin
* Ruby
array.slice(index)
array.slice(index, length)
array.slice(start..end)
0 origin
* Python
array[start:end]
0 origin
* Javascript
array.slice(start,end)
0 origin
* PHP
array_slice(array, offset, length)
0 origin

plugin vector: add vector_slice()

---

lib/mrb/mrb_bulk.c

expression_rewriterにfloatを通すと以下のようにエラーになったのでfloatに対応したいです。
```
[
-22,
1469353071.917372,
0.001502752304077148,
"unsupported bulk value type: <12>(Float)",
[
[
"Groonga::ExpressionTreeBuilder.build",
"/usr/lib64/groonga/scripts/ruby/expression_tree_builder.rb",
83
]
]
]
```

mruby: support float bulk

---

lib/pat.c
test/command/suite/select/function/fuzzy_search/object_literal/prefix_length.expected
test/command/suite/select/function/fuzzy_search/object_literal/prefix_length.test

``grn_pat_fuzzy_search``の``prefix_match_size``オプションにバグがありました。
prefixが一致しているノードまで進めるのにpat_cursorを使っていましたが、この場合、実キーのidまで進んでしまっていました。
たとえば、以下のgrn_patに対して``key:Tom``, ``prefix_match_size:1``だと``L:8{2,4,0}("Tiga")``まで進んでしまっていました。
1つ目の``R:6{1,5,0}``のところまで進めるように修正しました。
```
#<table:pat Tags key:ShortText value:(nil) size:8 columns:[tag] default_tokenizer:(nil) normalizer:(nil) keys:["Pam", "Pom", "Tiga", "Tim", "Tina", "Tom", "Tomas", "Tomy"] subrec:none nodes:{
4{0,5,0}
L:5{1,4,0}
L:5{1,4,0}("Pam")[01010000 01100001 01101101]
R:4{0,5,0}("Pom")[01010000 01101111 01101101]
R:6{1,5,0}
L:8{2,4,0}
L:8{2,4,0}("Tiga")[01010100 01101001 01100111 01100001]
R:7{2,6,0}
L:6{1,5,0}("Tim")[01010100 01101001 01101101]
R:7{2,6,0}("Tina")[01010100 01101001 01101110 01100001]
R:1{2,7,0}
L:0{0,0,0}
R:2{2,7,1} …
```

pat_fuzzy: fix a bug that prefix_match_size option returns wrong node

---

lib/proc.c
test/command/suite/select/function/in_values/with_index/sequential_search.expected
test/command/suite/select/function/in_values/with_index/sequential_search.test

``in_values``関数のシーケンシャルサーチもrecord_idに解決する必要があると思います。

proc in_values: resolve rid on sequential search

---

lib/proc/proc_fuzzy_search.c
test/command/suite/select/function/fuzzy_search/sequential/and.expected
test/command/suite/select/function/fuzzy_search/sequential/and.test

``fuzzy_search``関数のシーケンシャルサーチもridを解決すべきでした。

proc fuzzy_search: resolve record id on sequential search

---

doc/source/contribution/development/release.rst

Because redirected `homebrew/legacy-homebrew` is the former repository
of Homebrew formulae.
This repository is not used anymore.
Now, that project uses `homebrew/homebrew-core` repository to manage
Formulae.

doc contribution: Update Homebrew repository URL

---

lib/db.c

There is a case that grn_ctx_at returns NULL. In such a case,
missing NULL check causes crash unexpectedly.

Add missing NULL check about return value of grn_ctx_at

---

lib/ii.c

escalationが実行されるときに最初のii_selectの結果のminが適用されていたので、escalation時はminを退避しておいてnilにし、escalation結果のminよりも小さい場合はそちらのminを適用するようにしました。
（match_escalation_thresholdが1以上の場合は１つ目のii_selectでminが設定されることがある）

Reset match_info->min when escalation

---

lib/hash.c
lib/pat.c

テーブルをtruncateするタイミングでtoken_filtersのポインタの解放漏れがあるようです。
以下で再現できます。
静的索引構築時にも``grn_table_truncate``が呼ばれるところがあって、静的索引構築でも再現します。
```bash
plugin_register token_filters/stop_word
table_create Memos TABLE_NO_KEY
column_create Memos content COLUMN_SCALAR ShortText
table_create Terms TABLE_HASH_KEY ShortText \
--default_tokenizer TokenBigram \
--normalizer NormalizerAuto \
--token_filters TokenFilterStopWord,TokenFilterStopWord,TokenFilterStopWord,TokenFilterStopWord,TokenFilterStopWord
column_create Terms memos_content COLUMN_INDEX|WITH_POSITION Memos content
column_create Terms is_stop_word COLUMN_SCALAR Bool
load --table Terms
[
{"_key": "and", "is_stop_word": true}
]
load --table Memos
[
{"content": "Hello"},
{"content": "Hello and Good-bye"},
{"content": "Good-bye"}
]
truncate Terms
select …
```

Fix memory leak when truncate hash/pat has many token filters

---

data/scripts/Makefile.am

It should be installed with groonga-httpd, and should not be in
distribution file in any case.

Change to install groonga-httpd-restart conditionally

---

lib/expr.c

すいません
ANDの高速化のパッチ(#618)により一部のケースで絞り込みすぎのバグがありました。
わかっている１つのケースは以下の再現ケースのように、
１つめのORクエリの最小record_id < 2つめのORクエリの最小record_id 
(``today``min:1) < (``tommow``min:2)
の後にANDクエリが続くようなケースです。
この場合、3つめの``day``のANDクエリの``ii_select``では``min:2``が設定されて``id:2``しかヒットしないため、
それ以外のレコードは``ii_resolve_sel_and``で削除されてしまいます。
* 再現ケース
```
table_create Terms TABLE_HASH_KEY ShortText \
--default_tokenizer TokenBigram \
--normalizer NormalizerAuto
table_create Memos TABLE_NO_KEY
column_create Memos content COLUMN_SCALAR ShortText
column_create Terms index COLUMN_INDEX|WITH_POSITION Memos content
load --table Memos
[
{"content": "Today is good day."},
{"content": "Tomorrow will be good day."}
]
select Memos   --match_columns 'content'   --query 'today OR tomorrow day'
[
[
0,
0.0,
0.0
],
[
[
[
1
],
[
[
"_id",
"UInt32" …
```

Fix a bug that couldn't search index correctly

---

configure.ac
vendor/onigmo/Makefile.am

Introduce --with-onigmo GNU configure option.
"bundled" (default):  use in-tree Onigmo
"system": try to use system Onigomo or rise error
"yes": try to use system Onigmo or fallback to in-tree one
"no" (--without-onigmo): disalbe Onigmo support
Default "bundled" is the same behavior so far.

Allow to select Onigmo support

---

lib/db.c

ドリルダウンでcalc_typesが設定されていないときに、_sum等でソートをしようとすると、
存在しない_sumのサブレコードにアクセスしようとしてクラッシュします。
以下は再現ケースです。
```bash
table_create Tags TABLE_PAT_KEY ShortText
[[0,0.0,0.0],true]
table_create Memos TABLE_HASH_KEY ShortText
[[0,0.0,0.0],true]
column_create Memos tag COLUMN_SCALAR Tags
[[0,0.0,0.0],true]
column_create Memos value COLUMN_SCALAR Int64
[[0,0.0,0.0],true]
load --table Memos
[
{"_key": "Groonga is fast!", "tag": "Groonga", "value": 10},
{"_key": "Mroonga is fast!", "tag": "Mroonga", "value": 20},
{"_key": "Groonga sticker!", "tag": "Groonga", "value": 40},
{"_key": "Rroonga is fast!", "tag": "Rroonga", "value": 80}
]
[[0,0.0,0.0],4]
select Memos   --filter ''  \
--drilldowns[tag].keys tag  \
--drilldowns[tag].output_columns _key \
--drilldowns[tag].sort_keys -_sum
#|C| -- CRASHED!!! --
``` …

Avoid access to non existence sub records for group

---

include/groonga/window_function.h
lib/window_function.c
lib/window_functions.c

window関数の引数がうまく渡っていないようで渡せるようにしたいです。
時系列を右肩上がりになるよう累積値で取得したくて、window関数を自作しています。
window関数があると全部出力しなくても昇順で累積した後に降順でソートして必要な直近のものだけだしたりできて便利です。
https://github.com/naoa/groonga-function-yawindow

Support args for window function

---

lib/db.c

% groonga
> lock_clear
(crash)

Fix a crash bug by lock_clear against temporary database

---

lib/pat.c
test/command/suite/select/function/highlight_html/space_in_target.expected
test/command/suite/select/function/highlight_html/space_in_target.test

With this change, highlight family functions support highlighting text
that has some blanks. See the test in this change for example.

grn_pat_scan: ignore blanks in target string.

---

lib/expr.c
lib/proc/proc_highlight.c
test/command/suite/select/function/highlight_html/similar_search.expected
test/command/suite/select/function/highlight_html/similar_search.test

類似文書検索のときに検索文書をトークナイズしてハイライト対象のキーワードに追加してみました。
句読点とかストップワードをちゃんと設定すれば実用になりそうな印象があります、が、ストップワードなしだといろんなところがハイライトされてビミョウです。。。

highlight_html: support similar search

---

test/command/suite/sharding/logical_select/cache/match_columns.expected
test/command/suite/sharding/logical_select/cache/match_columns.test

When the value of --match_columms parameter is changed, Groonga
returns result without using cache.

test: add test case when match_columns parameter is changed

---

test/command/suite/sharding/logical_select/cache/columns/type.expected
test/command/suite/sharding/logical_select/cache/columns/type.test

When the value of --columns[NAME].type parameter is changed, Groonga
returns result without using cache.

test: add columns[NAME].type test case without cache

---

test/command/suite/sharding/logical_select/columns/stage/initial/no_hit/match_columns.expected
test/command/suite/sharding/logical_select/columns/stage/initial/no_hit/match_columns.test

This test case checks whether match_columns with empty records of
dynamic columns (price_with_tax) in initial stage doesn't cause an
error.

test: add no hit dynamic columns with match_columns without error

---

test/command/suite/sharding/logical_select/columns/stage/initial/no_hit/output_columns.expected
test/command/suite/sharding/logical_select/columns/stage/initial/no_hit/output_columns.test

This test case checks whether output_columns with empty records of
dynamic columns (price_with_tax) in initial stage doesn't cause an
error.

test: add no hit dynamic columns with output_columns without error

---

test/command/suite/sharding/logical_select/cache/columns/flags.expected
test/command/suite/sharding/logical_select/cache/columns/flags.test

When the value of --columns[NAME].flags parameter is changed, Groonga
returns result without using cache.

test: add columns[NAME].flags test case without cache

---

test/command/suite/sharding/logical_select/columns/stage/initial/no_hit/drilldowns/keys.expected
test/command/suite/sharding/logical_select/columns/stage/initial/no_hit/drilldowns/keys.test

This test case checks whether drilldowns[LABEL].keys with empty
records of dynamic columns (price_with_tax) in initial stage doesn't
cause an error.

test: add no hit dynamic columns with drilldowns[LABEL].keys without error

---

test/command/suite/sharding/logical_select/columns/stage/initial/no_hit/drilldown.expected
test/command/suite/sharding/logical_select/columns/stage/initial/no_hit/drilldown.test

This test case checks whether drilldown with empty records of dynamic
columns (price_with_tax) in initial stage doesn't cause an error.

test: add no hit dynamic columns with drilldown without error

---

test/command/suite/sharding/logical_select/cache/drilldowns/columns/window/sort_keys.expected
test/command/suite/sharding/logical_select/cache/drilldowns/columns/window/sort_keys.test

WIP because of error. Wrong usage of window.sort_keys?

test: add drilldowns[LABEL].columns[NAME].window.sort_keys without cache

---

test/command/suite/sharding/logical_select/cache/drilldown_filter.expected
test/command/suite/sharding/logical_select/cache/drilldown_filter.test

When the value of --drilldown_filter parameter is changed, Groonga
returns result without using cache.

test: add drilldown_filter test case without cache

---

test/command/suite/sharding/logical_select/drilldowns/columns/stage/initial/no_hit/drilldowns/filter.expected
test/command/suite/sharding/logical_select/drilldowns/columns/stage/initial/no_hit/drilldowns/filter.test

This test case checks whether drilldowns[LABEL].filter with empty
records of dynamic columns (price_with_tax) in initial stage doesn't
cause an error.

test: add no hit dynamic columns with drilldowns[LABEL].filter without error

---

test/command/suite/sharding/logical_select/cache/drilldowns/table.expected
test/command/suite/sharding/logical_select/cache/drilldowns/table.test

When the value of --drilldowns[LABEL].table parameter is changed,
Groonga returns result without using cache.

test: add drilldowns[LABEL].table test case without cache

---

test/command/suite/sharding/logical_select/cache/drilldowns/columns/window/group_keys.expected
test/command/suite/sharding/logical_select/cache/drilldowns/columns/window/group_keys.test

When the value of --drilldowns[LABEL].columns[NAME].window.group_keys
parameter is changed, Groonga returns result without using cache.

test: add drilldowns[LABEL].columns[NAME].window.group_keys test case without cache

---

test/command/suite/sharding/logical_select/cache/drilldowns/columns/flags.expected
test/command/suite/sharding/logical_select/cache/drilldowns/columns/flags.test

When the value of --drilldowns[LABEL].columns[NAME].flags parameter is
changed, Groonga returns result without using cache.

test: add drilldowns[LABEL].columns[NAME].flags test case without cache

---

plugins/sharding/logical_enumerator.rb
test/command/suite/sharding/logical_select/no_condition/max_exclude.expected
test/command/suite/sharding/logical_select/no_condition/max_exclude.test
test/command/suite/sharding/logical_select/no_condition/max_include.expected
test/command/suite/sharding/logical_select/no_condition/max_include.test
test/command/suite/sharding/logical_select/no_condition/min_exclude.expected
test/command/suite/sharding/logical_select/no_condition/min_exclude.test
test/command/suite/sharding/logical_select/no_condition/min_include.expected
test/command/suite/sharding/logical_select/no_condition/min_include.test

`logical_table`で指定したテーブルのテーブル名に月の最終日が含まれていてかつ、`logical_select`を`min`オプション付きで実行した際に`logical_select`が`argument out of range`で失敗する問題を修正しました。

Fix a bug that occur "argument out of range" when executing `logical_select` with min and max options.

---

lib/io.c

It may be useful to identify lifetime of created files.

Add more create operation logs

---

lib/mrb/scripts/command_line/grndb.rb

Database#recover fails when corrupted object is locked.
so truncate such a object in advance.

grndb: truncate object in advance for force truncate mode

---

packages/windows/Rakefile

`pcre-8.39` had not been exist in `ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre`
So, I modified to use `pcre-8.41` instead `pcre-8.39`.

package windows: use the latest pcre

---

lib/proc.c

The command `normalize` returns `normalized_text` on success.
See http://groonga.org/ja/docs/reference/commands/normalize.html for details.
The expected format is as follows.
```
> normalize NormalizerAuto 'String' --output_pretty yes
[
[
0,
1499398853.852021,
0.0001425743103027344
],
{
"normalized": "string",
"types": [
],
"checks": [
]
}
]
```
However, `normalize` returns an empty string on error.
```
> normalize NoSuchNormalizer 'String' --output_pretty yes
[
[
-22,
1499398844.332195,
8.940696716308594e-05,
"[normalize] nonexistent normalizer: <NoSuchNormalizer>",
[
[
"proc_normalize",
"proc.c",
1110
]
]
],
""
]
```
After applying this patch, `normalize` returns nothing on error.
See the following example.
```
> normalize NoSuchNormalizer 'String' --output_pretty yes
[
[
-22, …
```

normalize: don't output "" on error

---

lib/proc/proc_tokenize.c

`table_tokenize` returns nothing if the specified table does not exist.
```
> table_tokenize no_such_table 'あいうえお'
```
This patch updates `table_tokenize` to return an error as follows.
```
> table_tokenize no_such_table 'あいうえお'
[[-22,1499412795.316891,0.001605749130249023,"[table_tokenize] nonexistent lexicon: <no_such_table>",[["command_table_tokenize","proc_tokenize.c",271]]]]
```

table_tokenize: add a missing error

---

test/command/suite/select/function/time/time_classify_month/overflow_interval.expected
test/command/suite/select/function/time/time_classify_month/overflow_interval.test

I added test case base on the comment of #733.
I thought it doesn't need because it is invalid case.

functions/time: add test for overflow interval case

---

lib/mrb/scripts/expression_tree/function_call.rb
lib/proc.c
test/command/suite/select/function/between/with_index/index_column.expected
test/command/suite/select/function/between/with_index/index_column.test

I would like to specify directly index column with ``between()``.

between: support specifying index column

---

configure.ac

The default pid path (/var/run/groonga-httpd.pid) and pid path of
groonga-httpd-restart (/var/run/groonga/groonga-httpd.pid) are
different.
This mismatch blocks restarting groonga-httpd.
GitHub: #743
Reported by sozaki. Thanks!!!

httpd: put groonga-httpd.pid under /var/run/groonga/

---

lib/expr.c
test/command/suite/select/query/asterisk/multiple_indexes.expected
test/command/suite/select/query/asterisk/multiple_indexes.test

The current Groonga does not support prefix match search using multiple indexes.
The following is an example.
```
table_create Tbl TABLE_NO_KEY
column_create Tbl title COLUMN_SCALAR ShortText
column_create Tbl body COLUMN_SCALAR Text
load --table Tbl --columns 'title,body'
[
["Groonga overview","Groonga is a fast and accurate full text search engine based on inverted index."],
["Full text search and Instant update","Groonga also uses inverted indexes but supports instant updates."]
]
table_create Idx TABLE_PAT_KEY ShortText --default_tokenizer TokenBigram --normalizer NormalizerAuto
column_create Idx title COLUMN_INDEX|WITH_POSITION Tbl title
column_create Idx body COLUMN_INDEX|WITH_POSITION Tbl body
select Tbl --match_columns 'title||body' --query 'Groo*' --output_columns '_id,_score' …
```

Support prefix match search using multiple indexes

---

lib/mrb/mrb_eval_context.c
test/command/suite/ruby/eval/syntaxerror/unexpected_dot.expected
test/command/suite/ruby/eval/syntaxerror/unexpected_dot.test
test/command/suite/ruby/eval/syntaxerror/unexpected_end.expected
test/command/suite/ruby/eval/syntaxerror/unexpected_end.test
test/command/suite/ruby/eval/syntaxerror/unexpected_equal.expected
test/command/suite/ruby/eval/syntaxerror/unexpected_equal.test

Fixed crash when ruby_eval returned syntax error. (e.g. #751)

Fix crash when ruby_eval returned syntax error

---

src/groonga.c

In the previous versions, --default-command-version 3 is not supported.
Before:
% groonga --default-command-version 3 -n db/db
invalid command version: <3>
After:
% groonga --default-command-version 3 -n db/db
>

Support --default-command-version 3

---

lib/dat/dat.hpp
lib/dat/trie.cpp

This change limits the number of nodes per key of a dat trie.
If it is unlimited, `grn_dat_rebuild_trie` creates a huge file in the worst case.

dat: limit the number of nodes per key

---

lib/io.c

It should be DEBUG because it doesn't cause problem by itself.
This message is logged when mapped area for indexes is unmapped.

io: set proper log level to DEBUG

---

include/groonga/plugin.h
lib/grn_proc.h
lib/plugin.c
lib/proc.c
plugins/functions/index_column.c
test/command/suite/select/function/index_column/index_column_source_records/default.expected
test/command/suite/select/function/index_column/index_column_source_records/default.test
test/command/suite/select/function/index_column/index_column_source_records/limit.expected
test/command/suite/select/function/index_column/index_column_source_records/limit.test

I would like to add function to retrieve source records of index column in order to efficiently get value of referenced column such as parent-child relationship.
Syntax:
```c
index_column_source_records(index_column_name[, limit])
```
*  index_column_name: name of index columns as string
* limit(option): number of records to get (default: -1, -1 means all records)

Add index_column_source_records() function

---

plugins/functions/index_column.c

Sorry. It allows only object literal now.

index_column_source_records: fix wrong error message

---

plugins/functions/index_column.c

index_column_source_records: fix memory leak

---

lib/mrb/mrb_column.c
lib/mrb/mrb_database.c
lib/mrb/mrb_table.c
lib/mrb/scripts/command_line/grndb.rb
test/command_line/suite/grndb/test_recover.rb

This option force to clear lock of object(Database, Column, Table).
You can use if you want to database recover even if remain locked of database.
But this option very risky.
Because can not safty recover database if remain locked of database.
Usage:
grndb recover --force-lock-clear DB_PATH

grndb: add --force-lock-clear option

---

lib/grn_ctx_impl.h
lib/load.c
test/command/suite/load/surrogate_pair/emoji.expected
test/command/suite/load/surrogate_pair/emoji.test
test/command/suite/load/surrogate_pair/normalize.expected
test/command/suite/load/surrogate_pair/normalize.test
test/command/suite/load/surrogate_pair/raw.expected
test/command/suite/load/surrogate_pair/raw.test

This commit supports surrogate pairs in a `load` body.
For example, `\uD83C\uDF7A` is decoded to `🍺`.

load: support surrogate pairs

---

doc/locale/ja/LC_MESSAGES/reference.po
doc/source/reference/commands/logical_select.rst

Because the number of records is different from the example.

doc logical_select: fix a typo

---

lib/file_lock.c
lib/grn_file_lock.h

`grn_file_lock` should have path buffer in its struct to prevent storing a pointer to a stack local buffer.

file_lock: Copy path to buffer to avoid storing a pointer to a local buffer.

---

doc/locale/ja/LC_MESSAGES/install.po
doc/source/install.rst
doc/source/install/docker.rst

Groonga Alpine Linux minimal image is distributed on DockerHub.
Should we describe this minimal image on document?

Add Groonga docker installation document

---

doc/source/reference/executables/groonga.rst

"--host" option is not available in the client mode.

doc: correct command lines of groonga executable in the client mode

---

doc/source/reference/executables/groonga.rst

As far as I understand from a description as follows (and from source code and behavior),
the client mode only supports GQTP and HTTP is not supported.
Users cannot specify a protocol to access the server.
> In client mode, ``groonga`` executable file runs as a client for GQTP
> protocol Groonga server.
Sorry if my understanding is not correct.
Thanks!

doc: correct a description on protocols available in the client mode.

---

build/ac_macros/check_functions.m4
config.h.cmake
lib/io.c

`futimes` (ie. without the 'n') is the non-POSIX compatible brother of the POSIX compatible method `futimens`. `futimes` Is only implemented on Linux and some of the BSD's. Other POSIX compliant platforms do not provide this method but do provide `futimens`.
This came up when I was trying to build groonga on SmartOS (ie. Illumos / Solaris).
See also: http://pubs.opengroup.org/onlinepubs/9699919799/functions/futimens.html

Use POSIX compatible futimens method

---

src/groonga.c

A type of variable "i" is int and a type of variable "n_floating_threads" is uint32_t.
So, if the size of the value of "n_floating_threads" over the size of "int", "i" occurs overflow.

Modify for suppressing a warning that C4018

---

lib/arrow.cpp

I read http://groonga.org/ja/docs/contribution/development/build/unix_autotools.html.
I run `make` on macOS Mojave 10.14.3.
I got the following result.
```
arrow.cpp:745:8: error: no matching function for call to 'check_status'
if (!grnarrow::check_status(ctx,
^~~~~~~~~~~~~~~~~~~~~~
arrow.cpp:55:12: note: candidate function not viable: no known conversion from
'std::__1::basic_ostringstream<char, std::__1::char_traits<char>,
std::__1::allocator<char> >' to 'const char *' for 3rd argument
grn_bool check_status(grn_ctx *ctx,
^
arrow.cpp:68:12: note: candidate function not viable: no known conversion from
'std::__1::basic_ostringstream<char, std::__1::char_traits<char>,
std::__1::allocator<char> >' to 'std::ostream &'
(aka 'basic_ostream<char> &') for 3rd argument
grn_bool …
```

Fix build error on macOS

---

plugins/sharding/logical_range_filter.rb

logical_range_filterで結果が0件だった場合に作成する一時テーブルがtemporary_tablesに追加されておらず、context.close時の解放対象になっていなかったため、temporary_tablesに追加するよう修正。

fix memory leak when logical_range_filter returns no records.

---

lib/normalizer.c
test/command/suite/select/filter/index/match/normalizer_nfkc100_unify_kana.expected
test/command/suite/select/filter/index/match/normalizer_nfkc100_unify_kana.test

Because char_type is sometimes OR operated with GRN_CHAR_BLANK.
Therefore, when load data that there is whitespace after KATAKANA,
load data are not normalize.
Because KATAKANA before whitespace is operated OR with GRN_CHAR_BLANK,
it can not be decided as KATAKANA.
Fix issues #912

normalizer: use GRN_CHAR_TYPE

---

appveyor.yml

Because MinGW bundles groonga-admin.

appveyor: install groonga-admin

---

appveyor.yml

In the previous version, it causes the following error.
The filename, directory name, or volume label syntax is incorrect.

appveyor: fix wrong argument to move

---

include/CMakeLists.txt

groonga.hpp and arrow.hpp are missing.

cmake: install missing *.hpp

---

CMakeLists.txt
lib/grn.h

WIP: Without USE_EXACT_ALLOC_COUNT, grn_fin(N) reports unexpected leaks.

cmake windows: enable USE_EXACT_ALLOC_COUNT

---

appveyor.yml

Without this commit, only base_version is used.

appveyor: create version.sh to detect commit

---

appveyor.yml

It reduces waiting time to check amd64 packages

appveyor: change build order (amd64, x86)

---

lib/mrb/mrb_writer.c

Correct output type of writer_write function in case target type is MRB_TT_FIXNUM.
The output type should be int64_t because the target type(mrb_int) can be int64_t.

Correct writer write output type

---

appveyor.yml
test/command_line/run-test.rb

On Appveyor,  directory name is recognized unicode escape
sequence. so it should be unescaped correctly.

appveyor: enable testing with japanese directory

---

.travis.yml

Currently, Travis raises the following warning.
Because automake1.11 is not installed.
```
/home/travis/build/groonga/groonga/vendor/onigmo-source/missing: line 52: aclocal-1.11: command not found
WARNING: `aclocal-1.11' is missing on your system.  You should only need it if
you modified `acinclude.m4' or `configure.ac'.  You might want
to install the `Automake' and `Perl' packages.  Grab them from
any GNU archive site.
/home/travis/build/groonga/groonga/vendor/onigmo-source/missing: line 52: automake-1.11: command not found
WARNING: `automake-1.11' is missing on your system.  You should only need it if
you modified `Makefile.am', `acinclude.m4' or `configure.ac'.
You might want to install the `Automake' and `Perl' packages.
Grab them from any GNU archive site.
```

travis: supress warning

---

lib/Makefile.am

If there is not this definition, libluajit is not linked to libgroonga.

Makefile.am: add a missing definition

---

lib/grn_windows.h
lib/plugin.c
lib/windows.c

There is a case that GetModuleFileNameW returns path which contains
extended path prefix \\?\ as module filename. It causes a bug that
plugin can't be found correctly because of this kind of extended path
prefix.
TODO: Support long path correctly on Windows. (Drop MAX_PATH limitation)
GitHub:#958
Reported by @yagisumi Thanks!!!

windows: remove extended path prefix \\?\

---

lib/mrb/scripts/expression_tree/binary_operation.rb
test/command/suite/sharding/logical_select/post_filter/accessor_optimize.expected
test/command/suite/sharding/logical_select/post_filter/accessor_optimize.test

However, currently, this estimation is provisional.
It always returns table size.
We should estimate the number of hits.

expr optimize: add support for accessor estimation

---

lib/grn_com.h

Remove a needless enum

---

appveyor.yml

Because of wrong chainging working directory, groonga-admin license file is not
bundled correctly.

appveyor: fix inappropriate LICENSE file copy

---

appveyor.yml
packages/windows/vcruntime/ucrt-readme.txt

Usually UCRT runtime is automatically installed, but there is a case that it doesn't installed yet.
For such a specific environment, we use local-deployment.

appveyor: add UCRT runtime

---

appveyor.yml

In the previous version, when (null -eq "") condition
is evaluated, the following block is executed unexpectedly.

appveyor: check empty environment correctly

---

test/command/suite/io_flush/recursive/dependent/data_column/have_index.expected
test/command/suite/io_flush/recursive/dependent/data_column/have_index.test
test/command/suite/io_flush/recursive/dependent/data_column/no_index.expected
test/command/suite/io_flush/recursive/dependent/data_column/no_index.test
test/command/suite/io_flush/recursive/dependent/data_column/reference.expected
test/command/suite/io_flush/recursive/dependent/data_column/reference.test
test/command/suite/io_flush/recursive/dependent/index_column/source_key.expected
test/command/suite/io_flush/recursive/dependent/index_column/source_key.test
test/command/suite/io_flush/recursive/dependent/index_column/sources.expected
test/command/suite/io_flush/recursive/dependent/index_column/sources.test
test/command/suite/select/filter/index/optimization/and_min_skip/equal_match_match.expected
test/command/suite/select/filter/index/optimization/and_min_skip/equal_match_match.test
test/command/suite/select/filter/index/optimization/and_min_skip/nested_index.expected
test/command/suite/select/filter/index/optimization/and_min_skip/nested_index.test
test/command/suite/select/query/match/with_index/token_mecab/use_reading.expected
test/command/suite/select/query/match/with_index/token_mecab/use_reading.test
test/command/suite/select/query/match/with_index/token_pattern/match.expected
test/command/suite/select/query/match/with_index/token_pattern/match.test
test/command/suite/select/query/match/with_index/token_table/same.expected
test/command/suite/select/query/match/with_index/token_table/same.test

`table_create`の`normalizer`が間違えられがちなので、直しました。
テストの結果に影響はありませんでした。
default_normalizer -> normalizer
normalize -> normalizer

test: fix parameter name in table_create

---

vendor/mruby/Makefile.am

Patch via
https://github.com/msys2/MINGW-packages/commit/9c76ae395dd490b259d270608b47d130c6245490#diff-b266d04f16a509dc5bd3a3d12ca9df53

windows: fix build error on MinGW

---

Makefile.am

Put COPYING under /usr/share/groonga/COPYING

Install missing COPYING

---

lib/output.c

In the previous commit, it breaks range_filter/too_small_limit test case.
range_filter Memos id --limit -2
-[[[-22,0.0,0.0],"[range_filter] too small limit: <-2>"]]
-#|e| [range_filter] too small limit: <-2>
+[[0,0.0,0.0],[[["_id","UInt32"],["id","Int32"],["text","Text"]]]]

grn_output_range_normalize: fix wrong variable reference

---

autogen.sh

When RapidJSON support is enabled, proper compiler option must be
set by AX_CXX_COMPILE_STDCXX_11 macro. This m4 macro
is distributed in autoconf-archive package. We need to
enable it before regenerating configure script correctly.

Add missing check about m4 macro availability

---

configure.ac

The configure phase did not detect libedit despite installing dev files and this fix makes it work properly.
Verified on FreeBSD 11 and Debian 9.

Detect libedit at configure

---

plugins/sharding/logical_range_filter.rb
test/command/suite/sharding/logical_range_filter/limit/positive/many_unmatched_records.expected
test/command/suite/sharding/logical_range_filter/limit/positive/many_unmatched_records.test

This commit fixes the following error:
#|e| ArgumentError: already closed object
This exception occurs when max_n_unmatched_records estimation
is not accurate. In such a case, execute_filter(nil) is executed
as a fallback without specifying range index, as a result, no
method exception is raised and closes same object twice in
ensure block.

logical_range_filter: fix exception about closing same object twice

---

configure.ac

`==` operator for test(1) is not in the standard, then not portable.

configure: fix test(1) portability

---

plugins/tokenizers/mecab.c
test/command/suite/tokenizers/mecab/options/use_base_form.expected
test/command/suite/tokenizers/mecab/options/use_base_form.test

We can search using the base form of a token by this option.
For example, if we search "支えた" using this option, "支える" is hit also.

Add new option for tokenmecab

---

src/groonga.c

Because if Groonga has not runnable thread when we execute "shutdown --mode immediate", Groonga can not execute shutdown immediately.
TODO: test

groonga: accept "/d/shutdown?mode=immediate" immediately even when all threads are used

---

packages/launchpad-helper.rb

We success build a package for Ubuntu 20.04 by using current master's source.
https://launchpad.net/~groonga/+archive/ubuntu/nightly/+build/18891539

package ubuntu: add support for Ubuntu 20.04 (Focal Fossa)

---

lib/proc/proc_select.c

It needs to use ``GRN_OBJ_WEIGHT_FLOAT32``

select: use column flags for dynamic column

---

lib/io.c

I think ``GRN_INVALID_ARGUMENT`` is not suitable in this case.
Because this error cause is Groonga can't allocate memory.

io: fix a wrong error code

---

.github/workflows/macos.yml

Because Homebrew provide Apache Arrow 1.0.0.
https://github.com/Homebrew/homebrew-core/commit/057bf8766203e92e49bd86a46cbfffde1a8d25ee

ci: use the latest red-arrow for macOS

---

lib/ii.c

It is 3x faster with source data size of about 13GiB.
source_column size: 12.840GiB
Before: 1499 sec
Patched: 412 sec

Optimize offline index construction using token column

---

packages/yum/centos-8/Dockerfile
packages/yum/groonga.spec.in

groonga-tokenizer-mecab requires mecab-devel package.
However, currently, mecab-devel package doesn't provide in the repository of CentOS8.
Therefore, we provide mecab-devel package in the repository of Groonga(packages.groonga.org) for a while.
Thereby we can provide groonga-tonkenizer-mecab on CentOS8.
We can build groonga-tokenizer-mecab package by this PR.

package groonga-tokenizer-mecab: add support for CentOS8

---

data/html/admin/assets/groonga-admin.css
data/html/admin/assets/groonga-admin.ja.js
data/html/admin/assets/groonga-admin.js

This commit fixes a part of #1139.
The logo of Groonga is displayed by this commit.

admin: fix wrong paths to images

---

data/html/admin/index.ja.html

This commit fixes a part of #1139.
The throughput chart is displayed on the index page for Japanese by this commit.

admin: add missing include scripts

---

data/html/admin/assets/groonga-admin.ja.js
data/html/admin/assets/groonga-admin.js

Because attr may not get the status of a checkbox.

admin: use prop instead of attr

---

.github/workflows/macos.yml

Because we fail to install python 3.9 if symlink for python 3.8 exists.

ci macos: unlink symlink for python 3.8

---

doc/source/troubleshooting/how_to_analyze_error_message.rst

There is a small typo in doc/source/troubleshooting/how_to_analyze_error_message.rst.
Should read `reported` rather than `repoted`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, repoted -> reported

---

packages/launchpad-helper.rb

"apt_prepare_debian_dir()" is expecting that gives
the distribution name, the code name and, the architecture
into the second argument.
(See: https://github.com/apache/arrow/blob/master/dev/tasks/linux-packages/package-task.rb#L262)
However, in "launchpad-helper.rb", we are setting
the code name and version into the second argument of
"apt_prepare_debian_dir()".
Then, in Mroonga, "detect_mysql_version_ubuntu()" can't call in
https://github.com/mroonga/mroonga/blob/9d79ad72c71f8a7929ef92616f6ddb196f2dce66/packages/mroonga-package-task.rb#L50.
Because #{destribution} of
https://github.com/mroonga/mroonga/blob/master/packages/mroonga-package-task.rb#L50
is the code name of Ubuntu.

packages launchpad: fix a wrong argument

---

.github/workflows/package.yml

Because qemu-user-static in Ubuntu 20.04 has a crash bug as below.
* https://bugs.launchpad.net/qemu/+bug/1749393
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=971537
This bug has already fixed in Ubuntu 20.10.
However, this bug isn't fixed in Ubuntu 20.04.

package: add a new task for installing qemu-user-static from Groovy

---

lib/sort.c

GitHub: fix GH-1178.
There are paths that don't assign a sort flag to "key->flags".
By this, sort flag is unexpected vale and Groonga doesn't output sort results.

sort_keys: add missing sort flag assignments

---

doc/source/reference/api/grn_cache.rst
doc/source/reference/api/grn_column.rst

Because highlightlang directive is removed since Sphinx 4.0.0.

doc: use highlight directive instead of highlightlang directive

---

include/groonga/token.h

{,u}int{8,16,32,64}_t are suitable raw integer types such as int and
unsigned int. Because they aren't depend on build environment. long
may be 32-bit integer or 64-bit integer.

grn_token_status: use uint32_t instead of unsigned int

---

include/groonga/raw_string.h
include/groonga/token.h
lib/grn_token_cursor.h
lib/token.c
lib/token_cursor.c
plugins/token_filters/stem.c
test/command/suite/token_filters/stem/keep_original/add.expected
test/command/suite/token_filters/stem/keep_original/add.test
test/command/suite/token_filters/stem/keep_original/search_by_original.expected
test/command/suite/token_filters/stem/keep_original/search_by_original.test

Users can search by the original token (not stemmed token) conditionally with this.
It's useful when users want to search by a stemmed word generally but users sometimes want to search by a exact (not stemmed) word. For example:
* Searching by a stemmed word returns many results.
* Stemming returns wrong result.
* Users want to find only records that have a exact (not stemmed) word.

TokenFilterStem: add support for searching by the original token conditionally

---

packages/yum/groonga.spec.in

This avoids the following error:
https://github.com/groonga/groonga/runs/2691119502?check_suite_focus=true
Error: Package: arrow-devel-4.0.0-1.el7.x86_64 (groonga-centos)
You could try using --skip-broken to work around the problem
Requires: arrow-libs = 4.0.0-1.el7
Available: arrow-libs-0.3.1.20170506-1.el7.centos.x86_64 (groonga-centos)
arrow-libs = 0.3.1.20170506-1.el7.centos
Available: arrow-libs-0.3.1.20170508-1.el7.centos.x86_64 (groonga-centos)
arrow-libs = 0.3.1.20170508-1.el7.centos
Available: arrow-libs-0.3.1.20170510-1.el7.centos.x86_64 (groonga-centos)
arrow-libs = 0.3.1.20170510-1.el7.centos
Available: arrow-libs-0.3.1.20170512-1.el7.centos.x86_64 (groonga-centos)
arrow-libs = 0.3.1.20170512-1.el7.centos
Available: arrow-libs-0.3.1.20170517-1.el7.centos.x86_64 …

packages rpm: require versioned arrow-libs explicitly

---

doc/locale/ja/LC_MESSAGES/news.po

Fix a typo in news

---

doc/source/reference/functions/string_slice.rst

Fix typos in ``string_slice.rst``

Fix typos in string_slice.rst

---

.github/workflows/macos.yml

Because GCC version 8 has been removed from images on May, 31.
See:
https://github.com/actions/virtual-environments/blob/macOS-10.15/20210531.1/images/macos/macos-10.15-Readme.md
https://github.com/actions/virtual-environments/issues/3378

ci macos: remove a needless unlink

---

lib/cpp_sources.am
lib/grn_ctx.hpp
lib/proc/proc_query.cpp
test/command/suite/select/function/query_paralell_or/query/and.expected
test/command/suite/select/function/query_paralell_or/query/and.test

We can't reuse a result set for grn_table_selector_select(). It
doesn't work when a query has multiple conditions.
If we reuse a result set, we need to truncate the result set. But
"truncate" is slower than "delete all". ("Truncate" may be faster with
a large result set.)

query_parallel_or: fix a wrong result bug

---

include/groonga/raw_string.h
lib/normalizer.c
lib/raw_string.c
lib/string.c
test/command/suite/normalizers/multiple/options/all.expected
test/command/suite/normalizers/multiple/options/all.test
test/command/suite/normalizers/multiple/options/error.expected
test/command/suite/normalizers/multiple/options/error.test
test/command/suite/normalizers/table/checks.expected
test/command/suite/normalizers/table/checks.test
test/command/suite/normalizers/table/highlight_html.expected
test/command/suite/normalizers/table/highlight_html.test
test/command/suite/normalizers/table/many.expected
test/command/suite/normalizers/table/many.test
test/command/suite/normalizers/table/report_source_offset.expected
test/command/suite/normalizers/table/report_source_offset.test
test/command/suite/normalizers/table/target/data_column/invalid/no_equal_index.expected
test/command/suite/normalizers/table/target/data_column/invalid/no_equal_index.test
test/command/suite/normalizers/table/target/data_column/invalid/nonexistent.expected
test/command/suite/normalizers/table/target/data_column/invalid/nonexistent.test
test/command/suite/normalizers/table/target/data_column/invalid/not_patricia_trie.expected
test/command/suite/normalizers/table/target/data_column/invalid/not_patricia_trie.test
test/command/suite/normalizers/table/target/data_column/many.expected
test/command/suite/normalizers/table/target/data_column/many.test
test/command/suite/normalizers/table/types.expected
test/command/suite/normalizers/table/types.test
test/command/suite/normalizers/table/unicode_version.expected
test/command/suite/normalizers/table/unicode_version.test

Without this change, the following table is only supported:
table_create Normalizations TABLE_PAT_KEY ShortText
column_create Normalizations normalized COLUMN_SCALAR ShortText
With this change, the following table with an index is also supported:
table_create Normalizations TABLE_NO_KEY
column_create Normalizations target COLUMN_SCALAR ShortText
column_create Normalizations normalized COLUMN_SCALAR ShortText
table_create Terms TABLE_PAT_KEY ShortText
column_create Terms normalizations_target COLUMN_INDEX \
Normalizations target
The former can be used with:
NormalizerTable("normalized", Normalizations.normalized")
The latter can be used with:
NormalizerTable("normalized", "Normalizations.normalized",
"target", "Normalizations.target")
Note that "column" option is deprecated. Use …

NormalizerTable: add support for indexed target

---

lib/expr.c
test/command/suite/select/function/query_paralell_or/match_columns/scorer.expected
test/command/suite/select/function/query_paralell_or/match_columns/scorer.test

In order to slice the expr of match_columns including ``scorer_tf_idf``, it is necessary to adjust the nargs of ``GRN_OP_CALL``. 
Example case:
```
#$GRN_QUERY_PARALLEL_OR_N_CONDITIONS_THRESHOLD=1
#$GRN_QUERY_PARALLEL_OR_N_THREADS_LIMIT=2
table_create Tags TABLE_HASH_KEY ShortText
table_create Users TABLE_HASH_KEY ShortText
column_create Users comment COLUMN_SCALAR ShortText
column_create Users tags_by_me COLUMN_VECTOR Tags
column_create Users tags_by_others COLUMN_VECTOR Tags
load --table Users
[
{"_key": "Alice",
"tags_by_me": ["beginner", "active"],
"tags_by_others": ["expert", "active"]},
{"_key": "Bob",
"tags_by_me": ["expert", "passive"],
"tags_by_others": ["beginner", "passive"]},
{"_key": "Chris",
"tags_by_me": ["beginner", "passive"],
"tags_by_others": ["beginner", "active"]}
] …
```

grn_expr_slice: adjust nargs for GRN_OP_CALL

---

lib/expr.c
test/command/suite/select/query/adjust/decrease/nested.expected
test/command/suite/select/query/adjust/decrease/nested.test
test/command/suite/select/query/adjust/increase/nested.expected
test/command/suite/select/query/adjust/increase/nested.test

Parent weights are added to the specified weight.
Negative is also supported but there is no meaningful syntax for
it. For example "~2(~3XXX)" is invalid. "~" requires one or more
preceding words. So nested negative is meaningless.

increment/decrement: add support for nested

---

lib/mrb/mrb_ctx.c
lib/mrb/mrb_object.c
lib/mrb/scripts/command_line/grndb.rb
lib/mrb/scripts/context.rb
lib/mrb/scripts/database.rb
src/grndb.c
test/command_line/helper/groonga_log.rb
test/command_line/suite/grndb/test_recover.rb

We can reduce memory usage by this.
This may decrease performance but it will be acceptable.
Note that "grndb check" doesn't close used objects immediately yet.

grndb recover: close used objects immediately

---

lib/db.c

If some threads open the same object around the same time,
threads except for a thread that executes the opening object
at first are waiting for opening the target object.
At this time, threads that are waited for an opening object
take locks, but these locks are not released.
Therefore, these locks remain until Groonga's process is
restarted in the above case.

grn_ctx_at: add missing lock clear

---

lib/db.c

Because if reference count mode and succeeded case, vp->lock unlock
when grn_obj_unlink().

grn_ctx_at: don't unlock when reference count mode and succeeded case

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/package.yml
.github/workflows/windows-mingw.yml
.github/workflows/windows-msvc.yml

Because CI doesn't execute even if we push tags or maintenance branch currently.

ci: add missing trigger patterns

---

lib/io.c

Currently, If DO_MAP fails, opened fileinfo is not close.
Because unlink does not release file descriptor.
Therefore, If DO_MAP fails, the file descriptor is not released until
Groonga restarts.

grn_io_seg_map_: fix a resource leak

---

CMakeLists.txt
configure.ac
lib/arrow.cpp
lib/token_column.cpp
lib/window_function_executor.cpp

Update required apache arrow version to 3.0.0 in order to avoid complicating the source code.
Checking arrow version and branching by it are not so complicated for now, but they can be very complicated in the future.

Update required apache arrow version to 3.0.0

---

include/groonga/groonga.h
lib/grn_snip.h
lib/proc/proc_snippet.c
lib/snip.c
test/command/suite/select/function/snippet/delimiter_regexp/invalid.expected
test/command/suite/select/function/snippet/delimiter_regexp/invalid.test
test/command/suite/select/function/snippet/delimiter_regexp/multiple.expected
test/command/suite/select/function/snippet/delimiter_regexp/multiple.test
test/command/suite/select/function/snippet/delimiter_regexp/overlap.expected
test/command/suite/select/function/snippet/delimiter_regexp/overlap.test

Use case: Use only text in one sentence as snippet by finding "." (for
English) or U+3002 IDEOGRAPHIC FULL STOP (for Japanese).
Note that found delimiters aren't included in snippet. For example,
"." isn't included in snippet with /\./ regular expression. This is
useful for the use case.

snip: add support for regular expression to find delimiter

---

.github/workflows/windows-mingw.yml

Because pactoys-git renamed in upstream at the following commit.
https://github.com/msys2/MSYS2-packages/commit/0235754b07cbf708d28841aa59c0eddbe5ddd7a7#diff-27400a81bc42a425824029a2cf68650fea9de0875c5fb0c7c4b53ccd8665b9d7

ci mingw: follow a package name change

---

data/html/admin/assets/groonga-admin.ja.js
data/html/admin/assets/groonga-admin.js

#1186 
`$('#table-tab-recordlist-full-checkbox').attr('checked')` returns the initial state of the checkbox, does not changed with the current state of the checkbox.
We should use `prop()` instead of `attr()` for this checkbox.
https://api.jquery.com/attr/
> $( elem ).prop( "checked" ) | true (Boolean) Will change with checkbox state
> --|--
> $( elem ).attr( "checked" )             (1.6+) | "checked" (String) Initial state of the checkbox; does not change

groonga admin: Fix advanced search to work properly

---

lib/arrow.cpp
test/command/suite/sharding/logical_range_filter/command_version/3/apache_arrow.expected

Make `StreamWriter` write string type values as string type `DictionaryArray`.
Writing `DictionaryArray` on `FileDumper` is not supported because `arrow::FileWriter` does not support dictionary replacement. For writing `DictionaryArray` on `FileDumper`, we should create a single dictionary array for a filed including the case of using delta dictionaries, but it may cause memory exhaustion or exceeding a `ArrowArray` length limitation and so on when the dictionary is large.  
https://arrow.apache.org/docs/format/Columnar.html#ipc-file-format
https://arrow.apache.org/docs/format/Columnar.html#array-lengths
`StreamWriter` writes string type values as string type `DictionaryArray`.
Other type values are written as before because changing to write these types as `DictionaryArray`  does not …

arrow: use dictionary array for reference text column

---

lib/db.c
lib/proc/proc_column.c
lib/store.c
test/command/suite/column_create/index/source/mismatch/table_key_reference/column_builtin.expected
test/command/suite/column_create/index/source/mismatch/table_key_reference/column_builtin.test
test/command/suite/column_create/index/source/mismatch/table_key_reference/table_key_builtin.expected
test/command/suite/column_create/index/source/mismatch/table_key_reference/table_key_builtin.test
test/command/suite/column_create/index/source/mismatch/table_key_type/column_reference.expected
test/command/suite/column_create/index/source/mismatch/table_key_type/column_reference.test
test/command/suite/column_create/index/source/mismatch/table_key_type/table_key_reference.expected
test/command/suite/column_create/index/source/mismatch/table_key_type/table_key_reference.test
test/command/suite/column_create/index/source/multi_column/vector_full_text_search.expected
test/command/suite/column_create/index/source/multi_column/vector_full_text_search.test
test/command/suite/column_create/index/source/multi_column/without_section.expected
test/command/suite/column_create/index/source/multi_column/without_section.test
test/command/suite/column_create/index/source/nonexistent.expected
test/command/suite/column_create/index/source/nonexistent.test
test/command/suite/column_create/index/source/pseudo_column/_id.expected
test/command/suite/column_create/index/source/pseudo_column/_id.test
test/command/suite/column_create/index/source/vector_column/full_text_search_without_section.expected
test/command/suite/column_create/index/source/vector_column/full_text_search_without_section.test
test/command/suite/column_create/path/nonexistent/not_windows.expected
test/command/suite/column_create/path/nonexistent/not_windows.test
test/command/suite/column_create/path/nonexistent/windows.expected
test/command/suite/column_create/path/nonexistent/windows.test

**Details of #1300**
Sample  queries
```
table_create Statuses TABLE_NO_KEY
column_create Statuses start_time COLUMN_SCALAR UInt16
column_create Statuses end_time COLUMN_SCALAR UInt16
table_create Times TABLE_PAT_KEY UInt16
column_create Times statuses COLUMN_INDEX Statuses start_time,end_time *1
table_remove Times *2
```
https://github.com/groonga/groonga/blob/master/lib/proc/proc_column.c#L280
`grn->rc` is `GRN_INVALID_ARGUMENT` at the line above when executing the `column_create` (*1), and the `grn_obj_remove` above reaches the line below.
https://github.com/groonga/groonga/blob/master/lib/db.c#L11309
`_grn_obj_remove_spec` returns a return code of `grn_ja_replace` in this case.
(https://github.com/groonga/groonga/blob/master/lib/store.c#L3204)
If `grn_ja_replace` returns the original …

Fix to not break table when column_create fails (for #1300)

---

.github/workflows/package.yml

Because qemu-user-static in Ubuntu 20.04 has a crash bug as below.
* https://bugs.launchpad.net/qemu/+bug/1749393
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=971537
This bug has been already fixed in Ubuntu 20.10.
However, Ubuntu 20.10 already has been EOL.
Therefore, we use qemu-user-static on Ubuntu 21.10.

ci package: use qemu-user-static on Impish 

---

.github/workflows/package.yml

Because the following bug has already resolved in Ubuntu 20.04.
https://bugs.launchpad.net/qemu/+bug/1749393
Therefore, "Install QEMU from Impish" is needless.

ci package: remove a task for installing qemu-user-static from Impish

---

.github/workflows/windows-msvc.yml
packages/windows/vcruntime/vs2022/readme.txt

Visual studio 2022 is installed to `Program Files` not `Program Files (x86)`

ci: Add support for Visual Studio 2022

---

.github/workflows/linux.yml
.github/workflows/macos.yml

HTTP chunked test is slower than others. We should improve performance for HTTP chunked
but we increase timeout for now.

ci: increase timeout for HTTP chunked test

---

lib/db.c
test/command/suite/select/columns/stage/filtered/time_reference_count.expected
test/command/suite/select/columns/stage/filtered/time_reference_count.test
test/command/suite/select/columns/window_function/window_sum/reference_count.expected
test/command/suite/select/columns/window_function/window_sum/reference_count.test
test/command/suite/select/output_columns/nonexistent/with_filter.expected
test/command/suite/select/output_columns/nonexistent/with_filter.test

This is a patch for https://github.com/groonga/groonga/pull/1330/files#r827579558
An opened table is not closed in cases below.
1. using `time_classify_xxx` with dynamic column
2. using `window` function with dynamic column
3. specifying a non existent column on `output_column` with specifying `filter`
`select` command also has these issues so I guess this is not the matter of `logical_range_filter`.
The commands to reproduce these are below.
**common**
```
plugin_register functions/time
table_create Logs_20170315 TABLE_NO_KEY
column_create Logs_20170315 timestamp COLUMN_SCALAR Time
column_create Logs_20170315 price COLUMN_SCALAR UInt32
load --table Logs_20170315
[
{"timestamp": "2017/03/15 00:00:00", "price": 1000},
{"timestamp": "2017/03/15 11:00:00", "price":  900},
{"timestamp": …
```

Add necessary unref to grn_obj_get_accessor

---

plugins/sharding.rb
plugins/sharding/logical_range_filter.rb
plugins/sharding/sources.am
plugins/sharding/stream_executor.rb

This is a preparation for #1341.
A purpose is make `each_shard_executor` sharable with `logical_range_filter` and `logical_count`.

Separate Executor to an independent class

---

plugins/sharding/logical_range_filter.rb
plugins/sharding/stream_shard_executor.rb

logical_range_filter: Make result_sets enumeration sharable on `StreamShardExecutor`

logical_range_filter: Make result_sets enumeration sharable

---

plugins/sharding/logical_range_filter.rb
plugins/sharding/stream_execute_context.rb

Move the `order` attribute to `StreamExcuteContext` from `ExecuteContext`

logical_range_filter: Move order to StreamExcuteContext

---

lib/db.c
test/command/suite/select/output_columns/nonexistent/reference_count/pseudo_start_with_a.expected
test/command/suite/select/output_columns/nonexistent/reference_count/pseudo_start_with_a.test

Fix to unref obj if a pseudo column starts with "a" is not a reserved column.
Derived from https://github.com/groonga/groonga/pull/1335.

accessor: Add missing unref to pseudo column start with "a"

---

lib/db.c
test/command/suite/select/output_columns/nonexistent/reference_count/pseudo_start_with_s.expected
test/command/suite/select/output_columns/nonexistent/reference_count/pseudo_start_with_s.test

Fix to unref obj if a pseudo column starts with "s" is not a reserved column.
Derived from https://github.com/groonga/groonga/pull/1335.

accessor: Add missing unref to pseudo column start with "s"

---

lib/db.c
test/command/suite/select/output_columns/nonexistent/reference_count/pseudo_start_with_m.expected
test/command/suite/select/output_columns/nonexistent/reference_count/pseudo_start_with_m.test

Fix to unref `obj` if a pseudo column starts with "m" is not a reserved column.
Derived from #1335.

accessor: Add missing unref to pseudo column start with "m"

---

lib/ii.c

Because if Groonga doesn't stop making the result set when failing to add the result set of the search of regular expressions, Groonga output many error logs.
Therefore, the command response is slow when the number of hits is many in this case.
This modification is stopping making the result set on the way when failing to add the result set.
Thereby, the command response quickly

ii: add a condition for stopping making the result set on the way when fail to add the result set

---

data/munin/groonga_query_performance_

Currently, the thread id has "0x" as the prefix in the query log of Groonga.

munin: fix a wrong regular expression of thread id

---

lib/proc/proc_select.cpp

Because if we don't add "#include <unordered_map>", a build error occurs in an environment without Apache Arrow.

select: add a missinga "#include <unordered_map>"

---

lib/proc/proc_select.cpp

Because we use "grn::ChildCtxReleaser" in "proc_select.cpp".
ChildCtxReleaser class is defined in "grn_ctx.hpp".
Therefore, if we don't include "grn_ctx.hpp", a build error occurs in an environment without Apache Arrow.

select: Include "grn_ctx.hpp" even if in an environment without Apache Arrow

---

doc/locale/ja/LC_MESSAGES/reference/commands/select.po
doc/source/reference/commands/select.rst

The feature `slices.table` is not implemented.
Maybe it was intended `drilldowns.table`.

doc: Remove `slices.table` description

---

lib/db.c

Currently, Groonga doesn't stop making a result set when failing to
add the result set of a OR search.
Therefore, when the number of results of the OR search is many and a
query has many OR conditions, Groonga may response slow with the
"request_cancel" command.
if we execute the "request_cancel" command while Groonga adds the
result set of the OR search, the addition to the result set fails.
Therefore, Groonga output  a error of "failed to add:".
Groonga may output this error a lot because this error occurs every
failing to add the result set.
If Groonga output this error a lot, Groonga's response is very slow.
This modification is stopping making the result set on the way when
failing to add the result set.
Thereby, the command responds quickly.

db: add a new condition for stopping result set marge when fail to add the result set

---

packages/Rakefile
packages/packages-groonga-org-package-task.rb

Changed to redirect to GitHub Releases by `.htaccess` to download latest Groonga.
Changes
* Skip downloading Groonga packages to local machine when target is Windows.
* Create a new task named `prepare`.
* This task creates `.htaccess` for redirecting when target is Windows.
Created `.htaccess` is like below.
```
Redirect /windows/groonga/groonga-latest-x64-vs2022.zip https://github.com/groonga/groonga/releases/download/v12.0.9/groonga-12.0.9-x64-vs2022.zip
Redirect /windows/groonga/groonga-latest-x64-vs2022-with-vcruntime.zip https://github.com/groonga/groonga/releases/download/v12.0.9/groonga-12.0.9-x64-vs2022-with-vcruntime.zip
Redirect /windows/groonga/groonga-latest-x64-vs2019.zip https://github.com/groonga/groonga/releases/download/v12.0.9/groonga-12.0.9-x64-vs2019.zip
Redirect …
```

packages windows: redirect to GitHub Releases to download latest Groonga

---

packages/Rakefile
packages/packages-groonga-org-package-task.rb

By this change, we can download the latest source archive from the github release page into the top of the repository by executing "cd packages && rake dist".

packages: download latest source archive in dist task

---

packages/launchpad-helper.rb

`DPUT_CONFIGUARATION_NAME` seems a typo of `DPUT_CONFIGURATION_NAME`.

packages: fix a typo of an environment variable

---

.github/workflows/linux.yml
.github/workflows/package.yml

Because pydata-sphinx-theme occurs problem of https://github.com/pydata/pydata-sphinx-theme/issues/1094 when we use Sphinx 6.0.0.
The cause of this problem is the following change of Sphinx.
* https://github.com/sphinx-doc/sphinx/issues/11062
* https://github.com/sphinx-doc/sphinx/pull/11063
Therefore we use Sphinx 5.x until pydata-sphinx-theme resolve this problem.

ci: use Sphinx 5.x instead of Sphinx 6.x

---

doc/source/conf.py

`google_analytics_id` is deprecated in pydata-sphinx-theme after 0.12. Use `analytics` instead.
Ref: https://github.com/pydata/pydata-sphinx-theme/issues/903

doc: use "analytics" instead of "google_analytics_id"

---

doc/files.am

`bootstrap.js` and `bootstrap.css` are necessary to the latest document site.
They are copied (moved) into result files of `make update-document` by adding them into files.am.
The reason why we need to add `bootstrap.js` and `bootstrap.css`  is because `pydata-sphinx-theme` split bootstrap and theme styling.
https://github.com/pydata/pydata-sphinx-theme/pull/994

doc: add bootstrap.js/css into files.am

---

.github/workflows/linux.yml
.github/workflows/package.yml

This is a workaround for a "503 Service Unavailable" error when executing the apt command.
For #1480.
See also: https://github.com/actions/runner-images/issues/6894

ci: retry acquisition on apt

---

packages/post-msys2.sh

For #1426.
Added a new script `packages/post-msys2.sh`.
This script updates `mingw-w64-groonga/PKGBUILD` in your local `MINGW-packages` repository and creates a new branch to your forked remote `MINGW-packages` repository.
How to create a new pull request with this script.
1. Fork `https://github.com/msys2/MINGW-packages`
2. Clone the forked repository to the local (e.g. $HOME/work/MINGW-packages)
3. Add an "upstream" remote to the local repository (`git remote add upstream https://github.com/msys2/MINGW-packages.git`)
4. Execute the added new script as below (This process creates a new branch to your forked repository)
```
cd path/to/Groonga/repository
cd packages
./post-msys2.sh ${version} $HOME/work/MINGW-packages
```
5. Check if CI of your forked repository are passed.
6. Create Pull …

packages: add script for creating branch to forked `MINGW-packages` repository

---

doc/source/news.rst

We are free to use our own marker characters, but in according with https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#sections, the following are recommended:
1st: `=`
2nd: `-`
3rd: `^`
4th: `"`

doc: fix section headers

---

doc/locale/ja/LC_MESSAGES/contribution/development/release.po
doc/source/contribution/development/release.rst

#1473
`release.rst` uses Literal block(`::`), but it is preferred to use Code blocks (`.. code-block::`).

doc: use code block instead of literal block in release.rst

---

packages/packages-groonga-org-package-task.rb

The Rakefile of packages.groonga.org use `#latest_commit_time` at https://github.com/groonga/packages.groonga.org/blob/master/groonga-release/Rakefile#L9.
However `#latest_commit_time` is moved to dev/tasks/linux-packages/helper.rb from dev/tasks/linux-packages/package-task.rb in https://github.com/apache/arrow/commit/f82501e763ff48af610077f9525ae83cc3ab2e95.
Therefore we include `Helper::ApacheArrow` module.

packages: correct PackagesGroongaOrgPackageTask to reflect the modification of Apache Arrow 11.0.0

---

lib/grn_nfkc.h
lib/nfkc.c
lib/normalizer.c
test/command/suite/normalizers/nfkc100/unify_katakana_z_sounds.expected
test/command/suite/normalizers/nfkc100/unify_katakana_z_sounds.test
test/command/suite/normalizers/nfkc121/unify_katakana_z_sounds.expected
test/command/suite/normalizers/nfkc121/unify_katakana_z_sounds.test
test/command/suite/normalizers/nfkc130/unify_katakana_z_sounds.expected
test/command/suite/normalizers/nfkc130/unify_katakana_z_sounds.test
test/command/suite/normalizers/nfkc150/unify_katakana_z_sounds.expected
test/command/suite/normalizers/nfkc150/unify_katakana_z_sounds.test

When `unify_katakana_z_sounds` is specified, `NormalizerNFKC*` normalize characters as below.
ズァ -> ザ
ズィ -> ジ
ズェ -> ゼ
ズォ -> ゾ
Usage: 
```
normalize \
'NormalizerNFKC130("unify_katakana_z_sounds", true, \
"report_source_offset", true)' \
"ズァズィズェズォ" \
WITH_CHECKS|WITH_TYPES
```

NormalizerNFKC:  add `unify_katakana_z_sounds` option

---

.clang-format
.github/workflows/lint.yml
.pre-commit-config.yaml
lib/ctx.c

GitHub: #1529
We may want to enable SortIncludes.
Unsupported patterns:
```c
GRN_HASH_EACH_BEGIN() {
} GRN_HASH_EACH_END();
```
```c
exit :
```
```c
case XXX :
```
```c
if (XXX) { return; }
```

clang-format: enable only for lib/ctx.c as the first step

---

packages/Rakefile
packages/packages-groonga-org-package-task.rb

For example, this script output .htaccess as below when we release PGroonga 3.0.3.
```
edirect /source/pgroonga/pgroonga-3.0.1.tar.gz https://github.com/pgroonga/pgroonga/releases/download/3.0.1/pgroonga-3.0.1.tar.gz
Redirect /source/pgroonga/pgroonga-3.0.1.tar.gz.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.1/pgroonga-3.0.1.tar.gz.asc
Redirect /source/pgroonga/pgroonga-3.0.1.zip https://github.com/pgroonga/pgroonga/releases/download/3.0.1/pgroonga-3.0.1.zip 
Redirect /source/pgroonga/pgroonga-3.0.1.zip.asc https://github.com/pgroonga/pgroonga/releases/download/3.0.1/pgroonga-3.0.1.zip.asc
Redirect /source/pgroonga/pgroonga-3.0.2.tar.gz https://github.com/pgroonga/pgroonga/releases/download/3.0.2/pgroonga-3.0.2.tar.gz
Redirect /source/pgroonga/pgroonga-3.0.2.tar.gz.asc …
```

packages source: fix new version addition to redirect list

---

packages/packages-groonga-org-package-task.rb

The maximum value of per page of the list artifacts is 30 in default.
However, the number of packages of Mroonga is 35.
The number of per page of the list artifacts in default is not enough.

packages: expand the maximum value of per page of the list artifacts

---

doc/source/reference/executables/grnslap.rst
src/grnslap.c

procotol ->
protocol
The example run results in the documentation was out of date, so I have updated it.

Fix typo in grnslap

---

include/groonga/highlighter.h
lib/highlighter.c
lib/proc/proc_highlight.c
test/command/suite/select/function/highlight/sequential_class_tag_mode.expected
test/command/suite/select/function/highlight/sequential_class_tag_mode.test
test/command/suite/select/function/highlight_html/sequential_class_tag_mode.expected
test/command/suite/select/function/highlight_html/sequential_class_tag_mode.test

Because "cycled" has a meaning that a return to the initial position.
However, "cycled_class_tag" isn't behavior of the return to the initial position.
Therefore, we use sequential "instead" of "cycled".

highlight: use more suitable name

---

lib/ii.c
test/command/suite/select/filter/near_phrase/additional_last_interval/negative.expected
test/command/suite/select/filter/near_phrase/additional_last_interval/negative.test
test/command/suite/select/filter/near_phrase/max_element_intervals/additional_last_interval.expected
test/command/suite/select/filter/ordered_near_phrase/additional_last_interval/negative.expected
test/command/suite/select/filter/ordered_near_phrase/additional_last_interval/negative.test
test/command/suite/select/query/near_phrase/last/additional_last_interval/negative.expected
test/command/suite/select/query/near_phrase/last/additional_last_interval/negative.test
test/command/suite/select/query/near_phrase/max_element_intervals/additional_last_interval.expected
test/command/suite/select/query/near_phrase_product/last/additional_last_interval/negative.expected
test/command/suite/select/query/near_phrase_product/last/additional_last_interval/negative.test
test/command/suite/select/query/ordered_near_phrase/additional_last_interval/negative.expected
test/command/suite/select/query/ordered_near_phrase/additional_last_interval/negative.test

Currently, interval calculation is wrong as below when we use additional_last_interval.
* Input: "AaaxxxBbbcdefghi."
* query: '*NP3,-1"aaa bbb .$"'
Expected:
The number of tokens between "Aaa" and "Bbb" is 3.
Before:
The number of tokens between "Aaa" and "Bbb" is 7.
Current implementation expecte min_without_last_token's potision shows the potition of the last character of "Aaa" and max_without_last_token's potision shows the potition of the last character of "Bbb".
However, in fact, min_without_last_token's potision shows "A"'s potition and max_without_last_token's potision shows "B"'s potition.

ii near-phrase-family: fix interval calculation when we use additional_last_interval

---

lib/db.c

Because if Groonga try getting lock in 1000 or more, the number of "current_lock" is always increased.

grn_db_value_lock: add a missing decrement on lock failure

---

.github/workflows/linux.yml
lib/db.c

Skip lock/unlock built-in objects because built-in objects must be kept opening by the current design.

db: optimize built-in objects reference

---

.github/workflows/package.yml

ci package: fix syntax error

---

packages/debian/copyright

Currently, we don't get Groonga's source from packages.groonga.org but GitHub release page.

packages debian: update Groonga's source URL

---

packages/yum/almalinux-9/Dockerfile

Because build for RPM package fail as below when we use gcc 11. https://github.com/groonga/groonga/actions/runs/7026368743/job/19119118727#step:8:4050
Probablly, the cause of this problem is gcc.
Because this problem is internal compiler error and this problem occures even if Groonga's source code does not change.
So, I use gcc 12 instead of gcc 11.

packages almalinux 9: Use gcc 12

---

lib/grn_pat.h
lib/pat.c
lib/sort.c

The related `grn_pat_is_key_encoded` was also changed to use bool.
#1638

Use bool instead of grn_bool in sort.c

---

test/command/suite/normalizers/nfkc/unify_to_katakana/etc.expected
test/command/suite/normalizers/nfkc/unify_to_katakana/etc.test
test/command/suite/normalizers/nfkc/unify_to_katakana/ga.expected
test/command/suite/normalizers/nfkc/unify_to_katakana/ga.test
test/command/suite/normalizers/nfkc/unify_to_katakana/ha.expected
test/command/suite/normalizers/nfkc/unify_to_katakana/ha.test
test/command/suite/normalizers/nfkc/unify_to_katakana/ka.expected
test/command/suite/normalizers/nfkc/unify_to_katakana/ka.test
test/command/suite/normalizers/nfkc/unify_to_katakana/katakana_hiragana_semi_voiced_sound_mark.expected
test/command/suite/normalizers/nfkc/unify_to_katakana/katakana_hiragana_semi_voiced_sound_mark.test

* etc.*
* ga.*
* ha.*
* ka.*
* katakana_hiragana_semi_voiced_sound_mark.*

Re-add `unify_to_katakana` tests (`etc.*` - `katakana_hiragana_semi_voiced_sound_mark.*`)

---

test/command/suite/normalizers/nfkc/unify_to_katakana/katakana_hiragana_voiced_sound_mark.expected
test/command/suite/normalizers/nfkc/unify_to_katakana/katakana_hiragana_voiced_sound_mark.test
test/command/suite/normalizers/nfkc/unify_to_katakana/ma.expected
test/command/suite/normalizers/nfkc/unify_to_katakana/ma.test
test/command/suite/normalizers/nfkc/unify_to_katakana/na.expected
test/command/suite/normalizers/nfkc/unify_to_katakana/na.test
test/command/suite/normalizers/nfkc/unify_to_katakana/pa.expected
test/command/suite/normalizers/nfkc/unify_to_katakana/pa.test
test/command/suite/normalizers/nfkc/unify_to_katakana/ra.expected
test/command/suite/normalizers/nfkc/unify_to_katakana/ra.test

* katakana_hiragana_voiced_sound_mark.*
* ma.*
* na.*
* pa.*
* ra.*
#1673

Re-add `unify_to_katakana` tests (`katakana_hiragana_voiced_sound_mark.*` - `ra.*`)

---

test/command/suite/normalizers/nfkc/unify_to_katakana/sa.expected
test/command/suite/normalizers/nfkc/unify_to_katakana/sa.test
test/command/suite/normalizers/nfkc/unify_to_katakana/ta.expected
test/command/suite/normalizers/nfkc/unify_to_katakana/ta.test
test/command/suite/normalizers/nfkc/unify_to_katakana/wa.expected
test/command/suite/normalizers/nfkc/unify_to_katakana/wa.test
test/command/suite/normalizers/nfkc/unify_to_katakana/ya.expected
test/command/suite/normalizers/nfkc/unify_to_katakana/ya.test
test/command/suite/normalizers/nfkc/unify_to_katakana/za.expected
test/command/suite/normalizers/nfkc/unify_to_katakana/za.test

* sa.*
* ta.*
* wa.*
* ya.*
* za.*
#1673

Re-add `unify_to_katakana` tests (`sa.*` - `za.*`)

---

doc/.gitignore
doc/Gemfile
doc/locale/ja/LC_MESSAGES/contribution/documentation/introduction.po
doc/source/contribution/documentation/introduction.rst

```
CMake Error at cmake/GroongaSphinx.cmake:53 (find_program):
Could not find XGETTEXT using the following names: xgettext
```
We installed `gettext` to resolve this error.
```
Extension error:
Could not import extension myst_parser (exception: No module named 'myst_parser')
```
We installed from `doc/requirements.txt` to resolve this error. Sphinx is included in `requirements.txt`.
Remove pyenv section. Python3 is provided on major platforms.
```
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- gettext/tools (LoadError)
from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
from /docs/doc/../doc/update-edit-po.rb:19:in `<main>'
```
We install 'gem gettext'.

docs: Install any missing software

---

include/groonga/ii.h
lib/ii.c

There are many changes, but most of them are replacements of `GRN_TRUE`->`true` and `GRN_FALSE`->`false` due to the change from `grn_bool` to `bool`.
#1638

Use bool instead of grn_bool in ii.{c,h}

---

include/groonga/groonga.h
include/groonga/token.h
lib/ctx.c
lib/db.c
lib/ii.c
lib/output.c
lib/proc/proc_column.c
lib/proc/proc_object.c
lib/proc/proc_table.c
lib/proc/proc_tokenize.c
lib/token.c

Some other functions have also been changed, but they are used as arguments to `grn_ctx_output_bool`.
#1638

Change the argument `value` of `grn_ctx_output_bool` from `grn_bool` to `bool`

---

src/groonga.c

GitHub: fix GH-1644
`init_default_hostname()` is slow on Mac.
Remove `init_default_hostname()` and always use `localhost` as the default hostname.

Remove `init_default_hostname` and always use `localhost` as the default hostname

---

doc/locale/ja/LC_MESSAGES/reference/commands/status.po
doc/source/reference/commands/status.rst

I found that it was not listed, so I added it.

docs: Add `n_jobs` and `memory_map_size` to the status reference

---

lib/arrow.cpp
test/command/suite/select/output/apache_arrow/reference_int64.expected
test/command/suite/select/output/apache_arrow/reference_int64.test

arrow: Support `Int64` in `output_type=apache-arrow` for columns that reference other table

---

doc/locale/ja/LC_MESSAGES/tutorial/match_columns.po

- Fixed a translation in Japanese because there is differences between the sample code and the explanation

doc tutorial: fix a translation about match_columns in tutorial

---

setup.sh

- Add `libarrow-dev` package to setup script
- I faced the following CMake Error when I build groonga with `--preset=doc`
```console
% cmake -S . -B ../groonga.doc --preset=doc
CMake Error at CMakeLists.txt:531 (find_package):
By not providing "FindArrow.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "Arrow", but
CMake did not find one.
Could not find a package configuration file provided by "Arrow" with any of
the following names:
ArrowConfig.cmake
arrow-config.cmake
Add the installation prefix of "Arrow" to CMAKE_PREFIX_PATH or set
"Arrow_DIR" to a directory containing one of the above files.  If "Arrow"
provides a separate development package or SDK, be sure it has been
installed.
-- Configuring incomplete, errors occurred!
See …
```

Add a `libarrow-dev` package to setup script

---

plugins/tokenizers/h3_index.c

We want use `M_PI` macro in math.h.
But we can't use `M_PI` in VC++ just because we include `math.h`. We need to define `_USE_MATH_DEFINES` before including `math.h` in order to use `M_PI`.
See: https://learn.microsoft.com/en-us/cpp/c-runtime-library/math-constants
`math.h` is included in `groonga.h`.
So, we define `_USE_MATH_DEFINES` before including `groonga.h`

h3: add missing definition for using common math constants in VC++

---

vendor/Makefile.am

Because prevent we forget include related products into Groonga source archive.
If we execute "download.rb" with no arguments, "download.rb" download all related products.
Here is diff under the "vendor/" between before this modification and after this modification.
```diff
--- old.list	2024-03-01 14:55:16.310975363 +0900
+++ new.list	2024-03-01 15:00:04.172958257 +0900
@@ -13788,6 +13788,7 @@
./tools/ucd-symbol-list.rb
./vendor
./vendor/CMakeLists.txt
+./vendor/CRoaring-1.1.2.tar.gz
./vendor/Makefile.am
./vendor/Makefile.in
./vendor/c-blosc2-2.13.2.tar.gz
@@ -13827,6 +13828,7 @@
./vendor/groonga-log/Makefile.in
./vendor/groonga-log/ruby_scripts_groonga_log_sources.am
./vendor/groonga-log/ruby_scripts_sources.am
+./vendor/h3-4.1.0.tar.gz
./vendor/lz4
./vendor/lz4/CMakeLists.txt …
```

dist: download all related products when we execute "make dist"

---

.github/workflows/cmake.yml
test/command/suite/load/vector/reference/missing_add/object/empty.test

Because Apache Arrow format can't send an empty key.

test: skip a test that uses an empty key in Apache Arrow input mode

---

doc/locale/ja/LC_MESSAGES/contribution/documentation/introduction.po
doc/source/contribution/documentation/introduction.md

I will add a new sections to the `introduction.md` about translating documentation.

doc contribution/documentation: translate documentation

---

doc/locale/ja/LC_MESSAGES/contribution/documentation/introduction.po
doc/source/contribution/documentation/introduction.md

I will add a new sections to the `introduction.md` about translating documentation.

doc contribution/documentation: add how to reflect translations to `.po` files to the translate doc section

---

doc/locale/ja/LC_MESSAGES/contribution/documentation/introduction.po
doc/source/contribution/documentation/introduction.md

I will add a new sections to the `introduction.md` about translating documentation.

doc contribution/documentation: add how to preview translations on HTML files to the translate doc section

---

doc/locale/ja/LC_MESSAGES/contribution/documentation/introduction.po

doc contribution/documentation: translate `Preview translations on HTML files` in Japanese

---

packages/yum/test.sh

CI failed with the following error log.
```
ERROR:  Error installing grntest:
timeout requires Ruby version >= 2.6.0. The current ruby version is 2.5.0.
```
- ref: https://github.com/groonga/groonga/actions/runs/8677683712/job/23793718468
Successfully install gem `grntest`.
The gem `timeout` requires Ruby version >= 2.6.0.
On AlmaLinux8, the default Ruby version is 2.5.0 as shown below.
```console
$ dnf module list ruby
Name                          Stream                           Profiles                            Summary                                                                     
ruby                          2.5 [d]                          common [d]                          An interpreter of object-oriented scripting language                        
ruby …
```

package almalinux-8 test: use Ruby 3.1 instead of 2.5 for grntest

---

doc/locale/ja/LC_MESSAGES/contribution/documentation/introduction.po
doc/source/contribution/documentation/introduction.md

The Update step is a duplicated content from the introduction because the processes for editing and translating documentation are already covered at other steps in the introduction page.

doc contribution/documentation: remove `Update` step in the doc contribution guide

---

lib/grn_store.h
lib/store.c

We will add `grn_obj_is_empty` after this.
We will use it there.
`grn_obj_is_empty` is used to improve checking for empty values.

ja: Add grn_ja_is_empty()

---

include/groonga/obj.h
lib/obj.c

First, we support only `ja`.
Related: GH-1767

Add grn_obj_is_empty()

---

lib/db.c

This is an optimization. This doesn't change the current behavior.
In `grn_obj_set_value()`, it checks if the value is the same, and if it is, it does not update.
This check fetches value but it's heavy when we need to remove many records.
For example, `RESULT_SET1 && RESULT_SET2` is heavy is `RESULT_SET1` and `RESULT_SET2` have many different records.
We can check it with more lighter way. We don't need entire value. We just need to know whether the existing value is empty or not.

ja: Skip object clear in grn_obj_clear_value(), if object is empty

---

packages/apt/test.sh

Apache Arrow C++ requires C++17 or later.
However re2.pc on Debian bullseye have "-std=c++11". If "-std=c++11" was added, we can't build Apache Arrow C++.
TODO: This is testing now on CI.

test debian bullseye: workaround for build error of red-arrow

---

tools/parse-backtrace.rb

Add an option to skip libgroonga installation since it was used in an environment where Groonga was already installed.                 
First, it is only available on Ubuntu 22.04.

tools/parse-backtrace: Add option to use installed Groonga

---

doc/locale/ja/LC_MESSAGES/contribution/documentation/introduction.po
doc/source/contribution/documentation/introduction.md

Consider sending a PR before the `Optional: Translate documentation`.
This approach allows non-Japanese speakers to update only the English sections without needing to skip any parts.
ref: https://github.com/groonga/groonga/pull/1746#discussion_r1542432771

doc contribution/documentation: improve steps about send patch

---

.github/workflows/cmake.yml

Because it has already been installed at the previous step.

ci cmake windows: remove unnecessary step for installing red-arrow

---

lib/expr.c

In `invalid match target: <>` error, stop processing.
This error occurs in scan_info_build_match(), so check rc.
The other calls to scan_info_build_match() have already been checked.
* https://github.com/groonga/groonga/blob/c4a58af6373b283f76eb6b4c49276f020752d7da/lib/expr.c#L3349-L3361
* https://github.com/groonga/groonga/blob/c4a58af6373b283f76eb6b4c49276f020752d7da/lib/expr.c#L3749-L3757

Add rc check after scan_info_build_match()

---

lib/expr.c

Same as GH-1790.
Checks for errors at an earlier step.

Add rc check after scan_info_build_match_expr_codes()

---

lib/expr.c

Add rc check because the error message changes depending on whether mruby is enabled or disabled when rc is not `GRN_SUCCESS`.
When mruby is enabled and rc is not `GRN_SUCCESS`, NULL is retuned because rc is checked.
(The next process will not continue.)
If mruby is disabled and rc is not checked, the next process will be executed and the error message may be overwritten.

grn_scan_info_build: Add missing RC check of grn_scan_scan_info_build_simple()

---

lib/expr.c
test/command/suite/select/match_columns/invalid/table.expected
test/command/suite/select/match_columns/invalid/table.test

Include the result of grn_inspect() in the message because there may be logs with no information, such as `invalid match target: <>`.

scan_info_build_match_expr_codes: Improve error message

---

include/groonga/expr.h
lib/expr.c

Currently there is no way to know if `grn_expr_parse()` has added to `expr->codes`.
By using `grn_expr_get_n_codes()`, we can get the number of `expr->codes` so that we can check the increment.

Add grn_expr_get_n_codes()

---

.github/workflows/package.yml
packages/yum/almalinux-8-aarch64/from
packages/yum/almalinux-9-aarch64/from

ref: https://github.com/groonga/groonga/issues/1806
This change solves the following error on CI.
Because Docker build process does not automatically detect the correct platform for the image. As a result, the platform information defaults to the host platform. So in this case, platform infromation wasn't as a arm64.
To resolve this issue, we need to specify the platform explicitly in the Docker build command.
ref: https://docs.docker.com/build/building/multi-platform/
Here is the error log:
https://github.com/groonga/groonga/actions/runs/9705591558/job/26788067581#step:9:42
```
------
#3 [internal] load metadata for docker.io/arm64v8/almalinux:8
#3 ERROR: no match for platform in manifest: not found
------
Dockerfile:2
--------------------
1 |     ARG FROM=almalinux:8
2 | >>> FROM …
```

packages almalinux: add `--platform linux/arm64` when building arm64's image

---

lib/db.c

GitHub: fix GH-1810
"grn_fopen()" is defined as "_fsopen()" in Windows.
We can specify "shflag" in the third argument of "_fsopen()". We use "shflg" in "_fsopen()".
We need to include "share.h" to use "shflag".
See: https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fsopen-wfsopen?view=msvc-160
However, db.c does not include "share.h".
So, "error C2065: '_SH_DENYNO': undeclared identifier" occur.
This problem only occur in Groonga for Windows.
Because "fopen()" does not have "shflag".
("grn_fopen()" is defined "fopen()" in Linux.)

db: add missing header for "grn_fopen()"

---

packages/windows/download_github_actions_artifact.rb

Fixed the error:
```
<?xml version="1.0" encoding="utf-8"?> (Octokit::BadRequest)
<Error><Code>InvalidAuthenticationInfo</Code><Message>Authentication information is not given in the correct format. Check the value of Authorization header.
RequestId:xxx
Time:2024-07-05T06:20:29.6447183Z</Message></Error>
```

packages/windows: Use Octokit's artifact_download_url

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_user_data.po
doc/source/reference/api/grn_user_data.rst
include/groonga/groonga.h

Target: doc/source/reference/api/grn_user_data.rst

docs: api/grn_user_data: Copy the contents of the reference to a header file

---

.github/workflows/autotools.yml

This reverts commit 8275463f7d8f8fc7308b232049fdb0cf538bd3d5.
The new `msgpack-c` package has just released, which resolves this problem at upstream.
Now prefix path is reflected in `pkgconfig/msgpack-c.pc` when we passed `-DCMAKE_INSTALL_PREFIX`.
ref: https://github.com/Homebrew/homebrew-core/pull/175543
ref: https://github.com/msgpack/msgpack-c/releases/tag/c-6.0.2

ci macos: revert "ci macos: add workaround for msgpack-c"

---

packages/launchpad-helper.rb

Because Ubuntu 23.10 reached EOL at July 11, 2024. 
See: https://lists.ubuntu.com/archives/ubuntu-announce/2024-July/000303.html

package ubuntu: drop support for Ubuntu 23.10 (Mantic Minotaur)

---

doc/source/reference/api/grn_table_cursor.rst
include/groonga/table.h

docs: api/grn_table_cursor: Move the grn_table_cursor_open reference to the header file

---

doc/source/reference/api/grn_table.rst
include/groonga/table.h

docs: api/grn_table: Move the grn_table_create() reference to the header file

---

.github/workflows/document.yml
.github/workflows/lint.yml
doc/Doxyfile

Updated settings for running doxygen with CI.
* QUIET = YES
* The warning log is hard to find, so the generation log is not output
* WARN_AS_ERROR = FAIL_ON_WARNINGS
* If there is a warning, it should be terminated abnormally

ci: Run doxygen to check for correct markup

---

lib/grn_nfkc.h
lib/nfkc.c
lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark.test

GitHub: ref GH-1755
This PR adds the `unify_alphabet_diacritical_mark` option to NormalizerNFKC.
This option will allow the removal of diacritical marks to normalize them to alphabets in the following PRs.
In this PR, we are not implementing the actual logic, but just introducing the option interface.

NormalizerNFKC: add `unify_alphabet_diacritical_mark` option

---

packages/packages-groonga-org-package-task.rb

Currently, we don't download `.htaccess` for Windows from packages.groonga.org before download packages from GitHub release page.
So,  `.htaccess` for Windows is wrote only the latest version of Windows packages as below.
```
Redirect /windows/groonga/groonga-14.0.6-x64-vs2022.zip https://github.com/groonga/groonga/releases/download/v14.0.6/groonga-14.0.6-x64-vs2022.zip
Redirect /windows/groonga/groonga-latest-x64-vs2022.zip https://github.com/groonga/groonga/releases/download/v14.0.6/groonga-14.0.6-x64-vs2022.zip
Redirect /windows/groonga/groonga-14.0.6-x64-vs2022-with-vcruntime.zip https://github.com/groonga/groonga/releases/download/v14.0.6/groonga-14.0.6-x64-vs2022-with-vcruntime.zip
Redirect /windows/groonga/groonga-latest-x64-vs2022-with-vcruntime.zip …
```

packages windows: add redirect to old version

---

doc/locale/ja/LC_MESSAGES/install/debian.po
doc/locale/ja/LC_MESSAGES/install/ubuntu.po

This patch will change to correct package name in Japanese Debian/Ubuntu install guide
Fix GH-1847

doc install: Fix typo in Japanese Debian/Ubuntu install guide

---

doc/locale/ja/LC_MESSAGES/install/mac_os_x.po
doc/source/install/mac_os_x.rst

GitHub: fix GH-1846
Recent Homebrew installs the packages in /opt/homebrew.
Therefore, sed command does not work as expected when I follow the document.
And, the following settings are made by Homebrew default in mecabrc.
Seems that it necessary additional configuration.
```
;
; Configuration file of MeCab
;
; $Id: mecabrc.in,v 1.3 2006/05/29 15:36:08 taku-ku Exp $;
;
dicdir =  /opt/homebrew/lib/mecab/dic/ipadic
; userdic = /home/foo/bar/user.dic
; output-format-type = wakati
; input-buffer-size = 8192
; node-format = %m\n
; bos-format = %S\n
; eos-format = EOS\n
```
So this patch remove unnecessary configuration for mecabrc.

doc install/mac_os_x: remove unnecessary configuration for mecabrc

---

doc/locale/ja/LC_MESSAGES/tutorial/drilldown.po
doc/source/tutorial/drilldown.rst

This PR will replace `drildown` with `drilldown`.

doc tutorial/drilldown: Fix typos

---

doc/locale/ja/LC_MESSAGES/reference/commands/select.po
doc/source/reference/commands/select.rst

This patch will fix typos in documentation of select command reference.

doc reference/commands/select: fix typos

---

packages/apt/debian-bookworm/Dockerfile
packages/apt/debian-trixie/Dockerfile
packages/debian/control.in
packages/yum/groonga.spec.in

GitHub: fix GH-1844
This patch will install libedit when it builds the groonga package due to build a package with libedit enabled.

packages: add libedit package as dependency

---

doc/source/reference/api/grn_table.rst
include/groonga/table.h

docs: api/grn_table: Move the grn_table_update() reference to the header file

---

doc/source/reference/api/grn_table_cursor.rst
include/groonga/table.h

docs: api/grn_table_cursor: Move the get_key() and get_value() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_table_cursor.po
doc/source/reference/api/grn_table_cursor.rst
include/groonga/table.h

docs: api/grn_table_cursor: Move the delete() and table() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_table.po
doc/source/reference/api/grn_table.rst
include/groonga/table.h

docs: api/grn_table: Move grn_table_sort() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_command_version.po
doc/source/reference/api/grn_command_version.rst
include/groonga/groonga.h

docs: api/grn_command_version: Move the grn_command_version reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_encoding.po
doc/source/reference/api/grn_encoding.rst
include/groonga/groonga.h

docs: api/grn_encoding: Move the default encoding get and set reference to the header file

---

lib/logger.c

This bug occurred in the following conditions.
* When logging to a file
*  `--log-path <path>`
* `--query-log-path <path>`
* Log rotate is enabled
* `--log-rotate-threshold-size <threshold>`
* `--query-log-rotate-threshold-size <threshold>`
* Process ID log output is enabled
* `--log-flags process_id`
When the log is rotated, `output->file` is closed and set to `NULL`.
The crash occurs because of `flock(fileno(output->file), LOCK_UN);` in that state.
This unlocking was only executed when outputting process ID to the log, so it occurred only when outputting process ID.

logger: Fix crash bug when log rotate is enabled

---

.github/workflows/package.yml
packages/Rakefile
packages/apt/test.sh
packages/apt/ubuntu-focal/Dockerfile
packages/debian/rules
test/command/suite/select/drilldowns/keys/multiple_large.test

GitHub: ref GH-1865
In this PR, we add steps for building and testing Ubuntu focal packages as part of our regular development workflow on CI.
The reason for adding this is to prevent potential build failures on Launchpad during the release process, which can result in late discovery of issues and delays.
Ubuntu focal provides `xxHash` version 0.7.3, which does not meet the required version 0.8.0. We have updated the tests to skip xxHash-dependent functionality on Ubuntu focal by adding `@require-feature xxhash` which is the grntest's function. This change ensures that the test about features requiring `xxHash` are executed only when `xxHash` is available.
```
-- Checking for module 'libxxhash>=0.8.0'
--   Requested 'libxxhash >= 0.8.0' but version of xxhash is 0.7.3
You may find new …
```

ci package ubuntu: add steps for building and testing Ubuntu focal amd64's package

---

include/groonga/groonga.h

The same definition is in `include/groonga/table.h`.

Remove unnecessary definition

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_table.po
doc/source/reference/api/grn_table.rst
include/groonga/table.h

docs: api/grn_table: move size() and rename() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_table_cursor.po
doc/source/reference/api/grn_table_cursor.rst
include/groonga/groonga.h
include/groonga/table.h

docs api/grn_table_cursor: Move the grn_table_cursor_set_value() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_encoding.po
doc/source/reference/api/grn_encoding.rst
include/groonga/groonga.h

docs: api/grn_encoding: Move the to_string() and parse() reference to the header file

---

.github/workflows/package.yml

GitHub: fix GH-1885
To prevent CI jobs from running for a long time (max: 6 hours) and to ensure efficient usage of CI resources, this commit adds a timeout configuration for package build jobs.
Set timeouts as follows
- 90 minutes for Debian bookworm arm64
- 270 minutes for Debian trixie arm64
- 60 minutes for AlmaLinux 8/9 aarch64
- 30 minutes for all the other platforms
This ensures that long-running jobs do not block other developers from accessing CI resources and helps maintain faster turnaround times for all jobs.
I decided the timeout time using the following information.
I have set the timeout to approximately double the time taken by jobs, or added an extra 10 minutes if the duration is short.
https://github.com/groonga/groonga/actions/runs/10465513740/usage
| Job | Run time |
| …

ci: set timeout for package build jobs

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_table.po
doc/source/reference/api/grn_table.rst
include/groonga/table.h

docs: api/grn_table: move grn_table_delete() reference to the header file

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/b/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/b/latin_extended_additional.test

GitHub: ref GH-1755
This PR enhances the NormalizerNFKC by introducing functionality to the `unify_alphabet_diacritical_mark` option.
This option is specifically aimed at stripping diacritical marks from characters related to the letter `b`.
It ensures that any character with diacritical marks falling under the Combining Diacritical Marks Unicode block is normalized to `b`.
The following code can generate a mapping between Unicode and UTF-8.
```ruby
#!/usr/bin/env ruby
def have_diactritical_combining_character?(character)
code_points = character.unicode_normalize(:nfd).codepoints
code_points.any? do |code_point|
(0x0300..0x036f).cover?(code_point)
end
end
def base_character(character)
character.unicode_normalize(:nfd).chars.first
end
def base_character_is_lower_alphabet?(character) …
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `b`

---

packages/apt/test.sh

GitHub: fix GH-1889
Groonga no longer provides i386 packages as part of the official package distribution, so this condition is no longer needed.
ref: https://github.com/groonga/groonga/pull/1376

package test: remove i386 conditons

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/c/latin_1_supplement.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/c/latin_1_supplement.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/c/latin_extended_a.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/c/latin_extended_a.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/c/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/c/latin_extended_additional.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `c`.
Target character:
```
% ./tools/generate-alphabet-diacritical-mark.rb c
["U+00e7", "ç", ["0xc3", "0xa7"]]
["U+0107", "ć", ["0xc4", "0x87"]]
["U+0109", "ĉ", ["0xc4", "0x89"]]
["U+010b", "ċ", ["0xc4", "0x8b"]]
["U+010d", "č", ["0xc4", "0x8d"]]
["U+1e09", "ḉ", ["0xe1", "0xb8", "0x89"]]
ÇçĆćĈĉĊċČčḈḉ
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `c`

---

lib/normalizer.c

Hexadecimal numbers are lowercased in this repository.

Unify hexadecimal numbers in lowercase

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/d/latin_extended_a.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/d/latin_extended_a.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/d/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/d/latin_extended_additional.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `d`.
Target character:
```
% ./tools/generate-alphabet-diacritical-mark.rb d
["U+010f", "ď", ["0xc4", "0x8f"]]
["U+1e0b", "ḋ", ["0xe1", "0xb8", "0x8b"]]
["U+1e0d", "ḍ", ["0xe1", "0xb8", "0x8d"]]
["U+1e0f", "ḏ", ["0xe1", "0xb8", "0x8f"]]
["U+1e11", "ḑ", ["0xe1", "0xb8", "0x91"]]
["U+1e13", "ḓ", ["0xe1", "0xb8", "0x93"]]
ĎďḊḋḌḍḎḏḐḑḒḓ
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `d`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/e/latin_1_supplement.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/e/latin_1_supplement.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/e/latin_extended_a.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/e/latin_extended_a.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/e/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/e/latin_extended_additional.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/e/latin_extended_b.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/e/latin_extended_b.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `e`.
```
% ./tools/generate-alphabet-diacritical-mark.rb e
["U+00e8", "è", ["0xc3", "0xa8"]]
["U+00e9", "é", ["0xc3", "0xa9"]]
["U+00ea", "ê", ["0xc3", "0xaa"]]
["U+00eb", "ë", ["0xc3", "0xab"]]
["U+0113", "ē", ["0xc4", "0x93"]]
["U+0115", "ĕ", ["0xc4", "0x95"]]
["U+0117", "ė", ["0xc4", "0x97"]]
["U+0119", "ę", ["0xc4", "0x99"]]
["U+011b", "ě", ["0xc4", "0x9b"]]
["U+0205", "ȅ", ["0xc8", "0x85"]]
["U+0207", "ȇ", ["0xc8", "0x87"]]
["U+0229", "ȩ", ["0xc8", "0xa9"]]
["U+1e15", "ḕ", ["0xe1", "0xb8", "0x95"]]
["U+1e17", "ḗ", ["0xe1", "0xb8", "0x97"]]
["U+1e19", "ḙ", ["0xe1", "0xb8", "0x99"]]
["U+1e1b", "ḛ", ["0xe1", "0xb8", "0x9b"]]
["U+1e1d", "ḝ", ["0xe1", "0xb8", …
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `e`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/g/latin_extended_a.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/g/latin_extended_a.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/g/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/g/latin_extended_additional.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/g/latin_extended_b.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/g/latin_extended_b.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `g`.
```
% ./tools/generate-alphabet-diacritical-mark.rb g
["U+011d", "ĝ", ["0xc4", "0x9d"]]
["U+011f", "ğ", ["0xc4", "0x9f"]]
["U+0121", "ġ", ["0xc4", "0xa1"]]
["U+0123", "ģ", ["0xc4", "0xa3"]]
["U+01e7", "ǧ", ["0xc7", "0xa7"]]
["U+01f5", "ǵ", ["0xc7", "0xb5"]]
["U+1e21", "ḡ", ["0xe1", "0xb8", "0xa1"]]
ĜĝĞğĠġĢģǦǧǴǵḠḡ
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `g`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/h/latin_extended_a.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/h/latin_extended_a.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/h/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/h/latin_extended_additional.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/h/latin_extended_b.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/h/latin_extended_b.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `h`.
```
% ./tools/generate-alphabet-diacritical-mark.rb h
["U+0125", "ĥ", ["0xc4", "0xa5"]]
["U+021f", "ȟ", ["0xc8", "0x9f"]]
["U+1e23", "ḣ", ["0xe1", "0xb8", "0xa3"]]
["U+1e25", "ḥ", ["0xe1", "0xb8", "0xa5"]]
["U+1e27", "ḧ", ["0xe1", "0xb8", "0xa7"]]
["U+1e29", "ḩ", ["0xe1", "0xb8", "0xa9"]]
["U+1e2b", "ḫ", ["0xe1", "0xb8", "0xab"]]
["U+1e96", "ẖ", ["0xe1", "0xba", "0x96"]]
ĤĥȞȟḢḣḤḥḦḧḨḩḪḫẖ
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `h`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/k/latin_extended_a.actual
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/k/latin_extended_a.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/k/latin_extended_additional.actual
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/k/latin_extended_additional.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/k/latin_extended_b.actual
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/k/latin_extended_b.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `k`.
```
% ./tools/generate-alphabet-diacritical-mark.rb k
["U+0137", "ķ", ["0xc4", "0xb7"]]
["U+01e9", "ǩ", ["0xc7", "0xa9"]]
["U+1e31", "ḱ", ["0xe1", "0xb8", "0xb1"]]
["U+1e33", "ḳ", ["0xe1", "0xb8", "0xb3"]]
["U+1e35", "ḵ", ["0xe1", "0xb8", "0xb5"]]
ĶķǨǩḰḱḲḳḴḵ
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `k`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/l/latin_extended_a.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/l/latin_extended_a.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/l/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/l/latin_extended_additional.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `l`.
```
% ./tools/generate-alphabet-diacritical-mark.rb l
["U+013a", "ĺ", ["0xc4", "0xba"]]
["U+013c", "ļ", ["0xc4", "0xbc"]]
["U+013e", "ľ", ["0xc4", "0xbe"]]
["U+1e37", "ḷ", ["0xe1", "0xb8", "0xb7"]]
["U+1e39", "ḹ", ["0xe1", "0xb8", "0xb9"]]
["U+1e3b", "ḻ", ["0xe1", "0xb8", "0xbb"]]
["U+1e3d", "ḽ", ["0xe1", "0xb8", "0xbd"]]
ĹĺĻļĽľḶḷḸḹḺḻḼḽ
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `l`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/n/latin_1_supplement.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/n/latin_1_supplement.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/n/latin_extended_a.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/n/latin_extended_a.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/n/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/n/latin_extended_additional.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/n/latin_extended_b.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/n/latin_extended_b.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `n`.
```
% ./tools/generate-alphabet-diacritical-mark.rb n
["U+00f1", "ñ", ["0xc3", "0xb1"]]
["U+0144", "ń", ["0xc5", "0x84"]]
["U+0146", "ņ", ["0xc5", "0x86"]]
["U+0148", "ň", ["0xc5", "0x88"]]
["U+01f9", "ǹ", ["0xc7", "0xb9"]]
["U+1e45", "ṅ", ["0xe1", "0xb9", "0x85"]]
["U+1e47", "ṇ", ["0xe1", "0xb9", "0x87"]]
["U+1e49", "ṉ", ["0xe1", "0xb9", "0x89"]]
["U+1e4b", "ṋ", ["0xe1", "0xb9", "0x8b"]]
ÑñŃńŅņŇňǸǹṄṅṆṇṈṉṊṋ
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `n`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/r/latin_extended_a.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/r/latin_extended_a.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/r/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/r/latin_extended_additional.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/r/latin_extended_b.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/r/latin_extended_b.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `r`.
```
% ./tools/generate-alphabet-diacritical-mark.rb r
["U+0155", "ŕ", ["0xc5", "0x95"]]
["U+0157", "ŗ", ["0xc5", "0x97"]]
["U+0159", "ř", ["0xc5", "0x99"]]
["U+0211", "ȑ", ["0xc8", "0x91"]]
["U+0213", "ȓ", ["0xc8", "0x93"]]
["U+1e59", "ṙ", ["0xe1", "0xb9", "0x99"]]
["U+1e5b", "ṛ", ["0xe1", "0xb9", "0x9b"]]
["U+1e5d", "ṝ", ["0xe1", "0xb9", "0x9d"]]
["U+1e5f", "ṟ", ["0xe1", "0xb9", "0x9f"]]
ŔŕŖŗŘřȐȑȒȓṘṙṚṛṜṝṞṟ
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `r`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/o/latin_1_supplement.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/o/latin_1_supplement.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/o/latin_extended_a.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/o/latin_extended_a.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/o/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/o/latin_extended_additional.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/o/latin_extended_b.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/o/latin_extended_b.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `o`.
```
% ./tools/generate-alphabet-diacritical-mark.rb o
["U+00f2", "ò", ["0xc3", "0xb2"]]
["U+00f3", "ó", ["0xc3", "0xb3"]]
["U+00f4", "ô", ["0xc3", "0xb4"]]
["U+00f5", "õ", ["0xc3", "0xb5"]]
["U+00f6", "ö", ["0xc3", "0xb6"]]
["U+014d", "ō", ["0xc5", "0x8d"]]
["U+014f", "ŏ", ["0xc5", "0x8f"]]
["U+0151", "ő", ["0xc5", "0x91"]]
["U+01a1", "ơ", ["0xc6", "0xa1"]]
["U+01d2", "ǒ", ["0xc7", "0x92"]]
["U+01eb", "ǫ", ["0xc7", "0xab"]]
["U+01ed", "ǭ", ["0xc7", "0xad"]]
["U+020d", "ȍ", ["0xc8", "0x8d"]]
["U+020f", "ȏ", ["0xc8", "0x8f"]]
["U+022b", "ȫ", ["0xc8", "0xab"]]
["U+022d", "ȭ", ["0xc8", "0xad"]]
["U+022f", "ȯ", ["0xc8", "0xaf"]]
["U+0231", "ȱ", ["0xc8", …
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `o`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/s/latin_extended_a.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/s/latin_extended_a.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/s/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/s/latin_extended_additional.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/s/latin_extended_b.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/s/latin_extended_b.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `s`.
```
% ./tools/generate-alphabet-diacritical-mark.rb s
["U+015b", "ś", ["0xc5", "0x9b"]]
["U+015d", "ŝ", ["0xc5", "0x9d"]]
["U+015f", "ş", ["0xc5", "0x9f"]]
["U+0161", "š", ["0xc5", "0xa1"]]
["U+0219", "ș", ["0xc8", "0x99"]]
["U+1e61", "ṡ", ["0xe1", "0xb9", "0xa1"]]
["U+1e63", "ṣ", ["0xe1", "0xb9", "0xa3"]]
["U+1e65", "ṥ", ["0xe1", "0xb9", "0xa5"]]
["U+1e67", "ṧ", ["0xe1", "0xb9", "0xa7"]]
["U+1e69", "ṩ", ["0xe1", "0xb9", "0xa9"]]
ŚśŜŝŞşŠšȘșṠṡṢṣṤṥṦṧṨṩ
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `s`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/u/latin_1_supplement.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/u/latin_1_supplement.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/u/latin_extended_a.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/u/latin_extended_a.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/u/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/u/latin_extended_additional.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/u/latin_extended_b.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/u/latin_extended_b.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `u`.
```
% ./tools/generate-alphabet-diacritical-mark.rb u
["U+00f9", "ù", ["0xc3", "0xb9"]]
["U+00fa", "ú", ["0xc3", "0xba"]]
["U+00fb", "û", ["0xc3", "0xbb"]]
["U+00fc", "ü", ["0xc3", "0xbc"]]
["U+0169", "ũ", ["0xc5", "0xa9"]]
["U+016b", "ū", ["0xc5", "0xab"]]
["U+016d", "ŭ", ["0xc5", "0xad"]]
["U+016f", "ů", ["0xc5", "0xaf"]]
["U+0171", "ű", ["0xc5", "0xb1"]]
["U+0173", "ų", ["0xc5", "0xb3"]]
["U+01b0", "ư", ["0xc6", "0xb0"]]
["U+01d4", "ǔ", ["0xc7", "0x94"]]
["U+01d6", "ǖ", ["0xc7", "0x96"]]
["U+01d8", "ǘ", ["0xc7", "0x98"]]
["U+01da", "ǚ", ["0xc7", "0x9a"]]
["U+01dc", "ǜ", ["0xc7", "0x9c"]]
["U+0215", "ȕ", ["0xc8", "0x95"]]
["U+0217", "ȗ", ["0xc8", …
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `u`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/f/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/f/latin_extended_additional.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `f`.
```
% ./tools/generate-alphabet-diacritical-mark.rb f
["U+1e1f", "ḟ", ["0xe1", "0xb8", "0x9f"]]
Ḟḟ
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `f`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/j/latin_extended_a.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/j/latin_extended_a.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/j/latin_extended_b.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/j/latin_extended_b.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `j`.
```
% ./tools/generate-alphabet-diacritical-mark.rb j
["U+0135", "ĵ", ["0xc4", "0xb5"]]
["U+01f0", "ǰ", ["0xc7", "0xb0"]]
Ĵĵǰ
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `j`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/m/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/m/latin_extended_additional.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `m`.
```
% ./tools/generate-alphabet-diacritical-mark.rb m
["U+1e3f", "ḿ", ["0xe1", "0xb8", "0xbf"]]
["U+1e41", "ṁ", ["0xe1", "0xb9", "0x81"]]
["U+1e43", "ṃ", ["0xe1", "0xb9", "0x83"]]
ḾḿṀṁṂṃ
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `m`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/x/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/x/latin_extended_additional.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `x`.
```
% ./tools/generate-alphabet-diacritical-mark.rb x
["U+1e8b", "ẋ", ["0xe1", "0xba", "0x8b"]]
["U+1e8d", "ẍ", ["0xe1", "0xba", "0x8d"]]
ẊẋẌẍ
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `x`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/y/latin_1_supplement.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/y/latin_1_supplement.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/y/latin_extended_a.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/y/latin_extended_a.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/y/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/y/latin_extended_additional.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/y/latin_extended_b.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/y/latin_extended_b.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `y`.
```
% ./tools/generate-alphabet-diacritical-mark.rb y
["U+00fd", "ý", ["0xc3", "0xbd"]]
["U+00ff", "ÿ", ["0xc3", "0xbf"]]
["U+0177", "ŷ", ["0xc5", "0xb7"]]
["U+0233", "ȳ", ["0xc8", "0xb3"]]
["U+1e8f", "ẏ", ["0xe1", "0xba", "0x8f"]]
["U+1e99", "ẙ", ["0xe1", "0xba", "0x99"]]
["U+1ef3", "ỳ", ["0xe1", "0xbb", "0xb3"]]
["U+1ef5", "ỵ", ["0xe1", "0xbb", "0xb5"]]
["U+1ef7", "ỷ", ["0xe1", "0xbb", "0xb7"]]
["U+1ef9", "ỹ", ["0xe1", "0xbb", "0xb9"]]
ÝýÿŶŷŸȲȳẎẏẙỲỳỴỵỶỷỸỹ
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `y`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/z/latin_extended_a.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/z/latin_extended_a.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/z/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/z/latin_extended_additional.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `z`.
```
% ./tools/generate-alphabet-diacritical-mark.rb z
["U+017a", "ź", ["0xc5", "0xba"]]
["U+017c", "ż", ["0xc5", "0xbc"]]
["U+017e", "ž", ["0xc5", "0xbe"]]
["U+1e91", "ẑ", ["0xe1", "0xba", "0x91"]]
["U+1e93", "ẓ", ["0xe1", "0xba", "0x93"]]
["U+1e95", "ẕ", ["0xe1", "0xba", "0x95"]]
ŹźŻżŽžẐẑẒẓẔẕ
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `z`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/t/latin_extended_a.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/t/latin_extended_a.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/t/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/t/latin_extended_additional.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/t/latin_extended_b.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/t/latin_extended_b.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `t`.
```
% ./tools/generate-alphabet-diacritical-mark.rb t
["U+0163", "ţ", ["0xc5", "0xa3"]]
["U+0165", "ť", ["0xc5", "0xa5"]]
["U+021b", "ț", ["0xc8", "0x9b"]]
["U+1e6b", "ṫ", ["0xe1", "0xb9", "0xab"]]
["U+1e6d", "ṭ", ["0xe1", "0xb9", "0xad"]]
["U+1e6f", "ṯ", ["0xe1", "0xb9", "0xaf"]]
["U+1e71", "ṱ", ["0xe1", "0xb9", "0xb1"]]
["U+1e97", "ẗ", ["0xe1", "0xba", "0x97"]]
ŢţŤťȚțṪṫṬṭṮṯṰṱẗ
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `t`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/p/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/p/latin_extended_additional.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `p`.
```
% ./tools/generate-alphabet-diacritical-mark.rb p
["U+1e55", "ṕ", ["0xe1", "0xb9", "0x95"]]
["U+1e57", "ṗ", ["0xe1", "0xb9", "0x97"]]
ṔṕṖṗ
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `p`

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/v/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/v/latin_extended_additional.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `v`.
```
% ./tools/generate-alphabet-diacritical-mark.rb v
["U+1e7d", "ṽ", ["0xe1", "0xb9", "0xbd"]]
["U+1e7f", "ṿ", ["0xe1", "0xb9", "0xbf"]]
ṼṽṾṿ
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `v`

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po
doc/source/reference/api/grn_obj.rst
include/groonga/groonga.h

docs api/grn_obj: move grn_obj_rename() reference to the header file

---

lib/normalizer.c

`q` has no diacritical marks.
```
% ./tools/generate-alphabet-diacritical-mark.rb q
```

NormalizerNFKC unify_alphabet_diacritical_mark: Add a comment because only `q` does not unify

---

include/groonga/table.h

Update the phrase in include/groonga/table.h.
Use `A on success, B on error` format.

docs: Unify the phrasing

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/i/latin_1_supplement.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/i/latin_1_supplement.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/i/latin_extended_a.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/i/latin_extended_a.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/i/latin_extended_additional.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/i/latin_extended_additional.test
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/i/latin_extended_b.expected
test/command/suite/normalizers/nfkc/unify_alphabet_diacritical_mark/i/latin_extended_b.test

Implementation of grn_nfkc_normalize_unify_alphabet_diacritical_mark(). Commit to normalize to `i`.
Note that "U+0130  LATIN CAPITAL LETTER I WITH DOT ABOVE" isn't normalized correctly.
It should be normalized to "U+0069  LATIN SMALL LETTER I" but it's normalized to "U+0069  LATIN SMALL LETTER I" and "U+0307  COMBINING DOT ABOVE". It will not be fixed in `NormalizerNFKC150` or older to keep backward compatibility. It should be fixed in `NormalizerNFKC160` or later. See also: #1939
```
% ./tools/generate-alphabet-diacritical-mark.rb i
["U+00ec", "ì", ["0xc3", "0xac"]]
["U+00ed", "í", ["0xc3", "0xad"]]
["U+00ee", "î", ["0xc3", "0xae"]]
["U+00ef", "ï", ["0xc3", "0xaf"]]
["U+0129", "ĩ", ["0xc4", "0xa9"]]
["U+012b", "ī", ["0xc4", "0xab"]]
["U+012d", "ĭ", …
```

NormalizerNFKC unify_alphabet_diacritical_mark: remove diacritical mark for `i`

---

packages/apt/ubuntu-focal/Dockerfile
packages/debian/control.in

Build (ubuntu-focal-amd64) job on CI check build error before we build package on Launchpad.
If we build packages on Launchpad, dependency packages are installed based on control.in. On the other hand, if we build packages on CI, depndency packages are installed based on Dockerfile.
So, the dependency packages of control.in and Dockerfile msut be same.
The current different points of control.in and Dockerfile as below.
```diff
--- /tmp/Dockerfile	2024-09-03 15:34:20.335871523 +0900
+++ /tmp/control.in	2024-09-03 15:34:41.244334634 +0900
@@ -1,22 +1,17 @@
-autoconf-archive
-build-essential
-ccache
cmake
debhelper
-devscripts
-dh-apparmor
libedit-dev
libevent-dev
liblz4-dev
libmecab-dev
libmsgpack-dev
-libpcre3-dev
libsimdjson-dev
libssl-dev
libstemmer-dev
-libthrift-dev
+# Broken. xtl-dev …
```

packages ubuntu focal: unify dependency packages

---

packages/apt/ubuntu-jammy/Dockerfile

Currently, building on Launchpad during release was a one-shot process, and dealing with build failures is challenging.
To mitigate this, we're setting up a CI environment that mimics the Launchpad environment for testing.
However, the dependency packages listed in `control.in` and `Dockerfile` are different, making the test ineffective. This change unifies the dependency packages in `Dockerfile` to match those in `control.in` to ensure consistency between the test and actual build environments.

packages ubuntu jammy: unify dependency packages

---

packages/apt/ubuntu-noble/Dockerfile

Currently, building on Launchpad during release was a one-shot process, and dealing with build failures is challenging. To mitigate this, we're setting up a CI environment that mimics the Launchpad environment for testing.
However, the dependency packages listed in control.in and Dockerfile are different, making the test ineffective. This change unifies the dependency packages in Dockerfile to match those in control.in to ensure consistency between the test and actual build environments.

packages ubuntu noble: unify dependency packages

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_table.po
doc/source/reference/api/grn_table.rst
include/groonga/table.h

docs: api/grn_table: move grn_table_columns() reference to the header file

---

lib/logger.c

Crash on Windows when `grn_logger_output_close()` is run before `grn_logger_init()`.
Therefore, we changed it so that it does not close() when not init().  
PGroonga uses a usage where close() is run before init().
(That is the behavior when setting the logger with `grn_logger_set()`.)

logger: Change grn_logger_output_close() not to be run before grn_logger_init()

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_table.po
doc/source/reference/api/grn_table.rst
include/groonga/table.h

docs: api/grn_table: move grn_table_update_by_id() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_table.po
doc/source/reference/api/grn_table.rst
include/groonga/table.h

docs: api/grn_table: move grn_table_get_key() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po
doc/source/reference/api/grn_obj.rst
include/groonga/groonga.h

docs: api/grn_obj: move grn_obj_path() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_table.po
doc/source/reference/api/grn_table.rst
include/groonga/table.h

docs: api/grn_table: move grn_table_group() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po
doc/source/reference/api/grn_obj.rst
include/groonga/groonga.h

docs: api/grn_obj: move grn_obj_name() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po
doc/source/reference/api/grn_obj.rst
include/groonga/groonga.h

docs: api/grn_obj: move grn_obj_expire() reference to the header file

---

doc/files.am
doc/files.cmake
doc/locale/ja/LC_MESSAGES/reference/normalizers/normalizer_nfkc150.po
doc/source/example/reference/normalizers/normalizer-nfkc150-unify-latin-alphabet-with.log
doc/source/reference/normalizers/normalizer_nfkc150.rst

To improve maintainability, we have plans to change the structure of the documentation.
That plan will consolidate the options into one page.
So I have only added it to NormalizerNFKC150 in this commit.

docs: Add unify_latin_alphabet_with option to NormalizerNFKC150

---

doc/files.am
doc/files.cmake
doc/locale/ja/LC_MESSAGES/reference/normalizers/normalizer_nfkc150.po
doc/source/example/reference/normalizers/normalizer-nfkc150-unify-to-katakana.log
doc/source/reference/normalizers/normalizer_nfkc150.rst

To improve maintainability, we have plans to change the structure of the documentation.
That plan will consolidate the options into one page.
So I have only added it to NormalizerNFKC150 in this commit.

docs: Add unify_to_katakana option to NormalizerNFKC150

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_db.po
doc/source/reference/api/grn_db.rst
include/groonga/db.h

docs: api/grn_db: move grn_db_unmap() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po
doc/source/reference/api/grn_obj.rst
include/groonga/groonga.h

docs: api/grn_obj: move grn_obj_lock() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po
doc/source/reference/api/grn_obj.rst
include/groonga/groonga.h

GitHub: https://github.com/groonga/groonga/issues/1817

docs: api/grn_obj: move grn_obj_unlock() reference to the header file

---

.github/workflows/cmake.yml

Because there is a rpath issue in Rroonga.
Once resolved, we should enable mruby test on macos-latest.

ci macos: temporarily disable mruby test on macos-latest

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_search.po
doc/source/reference/api/grn_search.rst
include/groonga/groonga.h

docs: api/grn_search: move grn_obj_search() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_db.po
doc/source/reference/api/grn_db.rst
include/groonga/groonga.h

docs: api/grn_db: move grn_obj_db() reference to the header file

---

lib/db.c
test/unit/util/test-snip.c

Generally, functions for release resource do nothing when NULL is specified like "free(NULL)".
This changes API but this doesn't break backward compatibility.
Because no code exist that use the return value of `grn_obj_close()` when we specify `grn_obj_close(ctx, NULL)` as below.
---
Following functions use the return value of `grn_obj_close()`.
```
./lib/com.c:  if (ctx == msg->ctx) { return grn_obj_close(ctx, obj); }
./lib/db.c:  rc = grn_obj_close(ctx, obj);
./lib/db.c:  rc = grn_obj_close(ctx, obj);
./lib/db.c:  rc = grn_obj_close(ctx, obj);
./lib/db.c:  rc = grn_obj_close(ctx, obj);
./lib/db.c:  rc = grn_obj_close(ctx, obj);
./lib/db.c:  rc = grn_obj_close(ctx, obj);
./lib/db.c:  rc = grn_obj_close(ctx, obj);
./lib/db.c:  rc = grn_obj_close(ctx, obj);
./lib/db.c:  rc = …
```

grn_obj_close: do nothing and return GRN_SUCCESS for NULL

---

include/groonga/groonga.h
lib/db.c

Because `grn_obj_unlink()` may set `GRN_INVALID_ARGUMENT` to `ctx->rc` when an error occures in this function.
Also, `grn_obj_close()` returns `grn_rc`.
So, `grn_obj_unlink()` should also return `grn_rc`.
This changes API but this doesn't break backward compatibility.
Because no code exist that use the return value of `grn_obj_unlink()`.

grn_obj_unlink: return grn_rc

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_info.po
doc/source/reference/api/grn_info.rst
include/groonga/groonga.h

docs: api/grn_info: move grn_obj_(get|set)_element_info reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_info.po
doc/source/reference/api/grn_info.rst
include/groonga/groonga.h

docs: api/grn_info: move grn_obj_(get|set)_info reference to the header file

---

doc/locale/ja/LC_MESSAGES/install/centos.po
doc/locale/ja/LC_MESSAGES/install/cmake.po
doc/source/install.rst
doc/source/install/centos.rst
doc/source/install/cmake.rst
doc/source/install/others.rst

GitHub: GH-2007
Since there was already a cmake.rst, replace "Others" with it.
The installation documentation for each OS refers to `others.rst`, which should be changed separately. We will also add a separate note on the necessary CMake options.

docs: Replace others.rst with cmake.rst

---

.gitignore

This file is generated when a test fails.
To prevent accidental commits.

Add '/test/command/suite/**/*.reject' to .gitignore

---

lib/ctx.cpp

Sometimes the following response is received when canceling.
Example of command version 3 (Incomplete JSON) (`...` is the omission of an element):
```
{
"body": {
"columns":[...],
"records":[
[...],
"header":{
"return_code":-77,
...
}
}
```
If `ctx->rc` is `GRN_CANCEL`, we force using an empty result. Because creating result may be incomplete.
We can do it because the cancelled response must not be used.

request_cancel: Fix a bug that canceled request may return an invalid response

---

packages/yum/almalinux-8/Dockerfile
packages/yum/almalinux-9/Dockerfile
packages/yum/amazon-linux-2023/Dockerfile

Not necessary since Groonga is not build for PHP.
Target files:
```
$ grep -ir php packages
packages/yum/almalinux-9/Dockerfile:    php-devel \
packages/yum/almalinux-8/Dockerfile:    php-devel \
packages/yum/amazon-linux-2023/Dockerfile:    php-devel \
```

packages: Remove `php-devel` from the Dockerfile in yum

---

.github/workflows/setup.yml

```
$ ./build.sh
Usage: ./build.sh SOURCE_DIRECTORY BUILD_DIRECTORY INSTALL_PREFIX
e.g.: ./build.sh . /tmp/build /tmp/local
```

ci: Fix the order of arguments in build.sh

---

.pre-commit-config.yaml
include/groonga/cast.h

GitHub: GH-2024
We will add the documentation to the header of grn_obj_cast().
Therefore, we want to include this file in the formatting targets.

clang-format: add include/groonga/cast.h

---

doc/files.am
doc/files.cmake

This change fixed the following CI error  because the generated file list has been changed from Sphinx 8.1.3.
```
cp: cannot stat './html/_static/styles/bootstrap.css': No such file or directory
```
ref: https://github.com/groonga/groonga/actions/runs/11470920955/job/31920976581#step:9:18973
We have updated the following commands.
```console
$ rm -rf ../groonga.doc && cmake -S . -B ../groonga.doc --preset=doc && cmake --build ../groonga.doc
$ ninja doc_update_files -C ../groonga.doc
```

doc: update the generated file list by Shpinx v8.1.3

---

doc/locale/ja/LC_MESSAGES/reference/commands/object_inspect.po

Because `column-create-generator` is correct name as below.
```
.. _column-create-generator:
``generator``
"""""""""""""
.. versionadded:: 14.1.0
Specifies a generator expression in :doc:`../grn_expr/script_syntax`
that is used to generate column value automatically.
This option is useful if you want to generate a column value from
other column value automatically.
The default value is none.
```
ref: https://github.com/groonga/groonga/blob/main/doc/source/reference/commands/column_create.rst?plain=1#L1880

doc reference object_inspect: fix a typo

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_index_cursor.po
doc/source/reference/api/grn_index_cursor.rst
include/groonga/table.h

docs: api/grn_index_cursor: move grn_index_cursor_next() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_index_cursor.po
doc/source/reference/api/grn_index_cursor.rst
include/groonga/table.h

docs: api/grn_index_cursor: move grn_index_cursor_open() reference to the header file

---

lib/output.c

GitHub: Related: GH-2031, GH-2043
Prepare to fix the output of `records`.
Added grn_output_table_records_content_v1().
Also added grn_output_table_records_content_v3().
The closing process is still included in content() because it is still being separated, but we plan to separate the closing process later.
The process of executing content() in open() will also be separated.

output: grn_output_table_records: Separate open and content

---

include/groonga/output.h
lib/ctx.cpp
lib/grn_output.h
lib/output.c

GitHub: Related: GH-2031
Prepare to fix the output of `records`.
Add grn_output_result_set_open_metadata()  to output only the metadata part.
Added `grn_output_table_records_close_v*` but removed it because it was already abstracted and unnecessary. `grn_output_table_records_content_v*` was removed since it is common in v1 and v3.

output: Add grn_output_result_set_open_metadata()

---

include/groonga/column.h

docs: api/grn_column: fix the syntax about `GRN_COLUMN_NAME_ID_LEN`

---

.github/workflows/cmake.yml

We get Apache Arrow version in "detect_target_apache_arrow_version()" of packages/Rakefile when we build packages.
"detect_target_apache_arrow_version()" refer to .github/workflows/cmake.yml. So, we need to update Apache Arrow version in .github/workflows/cmake.yml.

ci: use the latest Apache Arrow when we build packages

---

lib/mrb/mrb_writer.c
lib/output.c
plugins/sharding/logical_range_filter.rb

GitHub: fixes GH-2026
Example of invalid JSON:
```
...
"records": [],
"records": [
...
],
...
```
An empty array of `records` is output first.
`GRN_OUTPUT_RESULT_SET_OPEN` would output up to `records`, resulting in two `records`, so use `GRN_OUTPUT_RESULT_SET_OPEN_METADATA` instead.

logical_range_filter: Fix two records keys in response of command v3

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_hook.po
doc/source/reference/api/grn_hook.rst
include/groonga/groonga.h

docs: api/grn_hook: move grn_obj_delete_hook() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_hook.po
doc/source/reference/api/grn_hook.rst
include/groonga/groonga.h

docs: api/grn_hook: move grn_obj_get_nhooks() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_column.po
doc/source/reference/api/grn_column.rst
include/groonga/column.h

docs: api/grn_column: move GRN_COLUMN_NAME_KEY{,_LEN} reference to the header file

---

doc/source/reference/commands/object_inspect.rst

This change resolves a warning during documentation generation as follow. It is raised because there is a duplicated label. So we just rename the label to fix it.
```console
$ cmake \
-S .
-B ../groonga.doc
--preset=doc && \
cmake
--build ../groonga.doc
...
/home/otegami/work/c/groonga/doc/source/reference/commands/object_inspect.rst:661: WARNING: Duplicate explicit target name: "object-inspect-return-value-vector-column-value-weight_bfloat16". [docutils]
...
```

doc reference/command/object_inspect: fix duplicated label

---

doc/source/conf.py

We want to embed the results of executing Groonga commands within documents for easy to understand. We preprocess our document sources by `doc/update-execution-example.rb` and generate execution results.
We're using the following syntax for the preprocess in `.md`:
````md
```{include} output-path.md
table_create ...
select ...
```
````
But this causes the following warnings:
```console
$ cmake \
-S .
-B ../groonga.doc
--preset=doc && \
cmake
--build ../groonga.doc
...
/home/otegami/work/c/groonga/doc/source/reference/functions/language_model_vectorize.md.rst:61: WARNING: 'include': Has content, but none permitted [myst.directive_parse]
...
```
We can use other syntax for `.md` because `doc/update-execution-example.rb` is maintained by us. We can just implement a logic for other syntax in …

doc conf: suppress `'include': Has content` warnings in .md

---

lib/alloc.c
lib/grn_ctx_impl.h

Change `freed` in `grn_alloc_info` to bool

---

lib/db.c
lib/grn_db.h

No logic changes, just renaming.
Change `hld_size` to `data_size` since it is not easy to understand.
There is no impact on compatibility since it is only used internally.

grn_hook: Change `hld_size` to `data_size`

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_hook.po
doc/source/reference/api/grn_hook.rst
include/groonga/groonga.h

docs: api/grn_hook: move grn_obj_get_hook() reference to the header file

---

include/groonga/column.h
include/groonga/groonga.h

fix: https://github.com/groonga/groonga/pull/2062#discussion_r1828971015
This changes add the usage to `grn_obj_column` for handling the accessor with pseudo columns.
It also removes the duplicated the examples from pseudo columns' usages.

docs: api/grn_obj: add usage to `grn_obj_column` for handling the accessor

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_hook.po
doc/source/reference/api/grn_hook.rst
include/groonga/groonga.h

docs: api/grn_hook: move grn_obj_add_hook() reference to the header file

---

include/groonga/groonga.h

fix: https://github.com/groonga/groonga/pull/2066#discussion_r1830348283
Update the style of `grn_obj_column` contents as follows
- Fix indendations
- Fix a missing period
- Add `\ref`links for methods

docs: api/grn_obj: update the style of `grn_obj_column` contents

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_ctx.po
doc/source/reference/api/grn_ctx.rst
include/groonga/groonga.h

Unify "DB" with "database" for related grn_ctx_db(). Followed other documents.

docs: api/grn_ctx: move grn_ctx_use() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/normalizers/normalizer_nfkc150.po
doc/source/reference/normalizers/normalizer_nfkc150.rst

GitHub: GH-2080
You can remove the middle dot when used with `remove_symbol`.

docs: unify_middle_dot: Add usage

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_ctx.po
doc/source/reference/api/grn_ctx.rst
include/groonga/groonga.h

docs: api/grn_ctx: move grn_ctx_(init|fin) reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_column.po
doc/source/reference/api/grn_column.rst
include/groonga/groonga.h

docs: api/grn_column: move grn_column_find_index_data reference to the header file

---

CMakeLists.txt

Set up on USearch side.
https://github.com/unum-cloud/usearch/commit/ae47cf29bbd90f7c65a3b2cc7bcee80eb9599d90

cmake: usearch: Remove target_include_directories()

---

include/groonga/geo.h

docs: api/grn_geo: move grn_geo_estimate_size_in_rectangle() reference to the header file

---

test/command/suite/index_column_diff/too_many_tokens/int64_vector.test
test/command/suite/index_column_diff/too_many_tokens/reference_vector.test
test/command/suite/index_column_diff/too_many_tokens/text.test
test/command/suite/index_column_diff/too_many_tokens/text_multi_sources.test
test/command/suite/index_column_diff/too_many_tokens/text_multi_tokens.test
test/command/suite/index_column_diff/too_many_tokens/text_vector.test

In CI, `Test: HTTP: reference count: Apache Arrow: chunked` step for Windows failed as follows.
These tests are unstable using the current timeout time.
```
...
--- (expected)
+++ (actual)
@@ -6,6 +6,5 @@
[[0,0.0,0.0],true]
column_create Deltas index COLUMN_INDEX|WITH_POSITION PostingLists deltas
[[0,0.0,0.0],true]
-#|w| [ii][update][one] too many postings: <Deltas.index>: <1>(1): record:<PostingLists>(1:1), n-postings:<131072>, n-discarded-postings:<1>
index_column_diff Deltas index
[[0,0.0,0.0],[]]
===============================================================================
[2] index_column_diff/too_many_tokens
int64_vector                                                56.2620s [failed]
=============================================================================== …
```

index_column_diff: increase timeout for too_many_token's tests on Windows

---

src/suggest/CMakeLists.txt

CI failed because `groonga-suggest-learner` & `groonga-suggest-httpd` couldn't be linked to `libpthread.so.0` like the followings.
- `groonga-suggest-learner`
```
...
[400/416] : && /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/groonga-14.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -O2 -g -DNDEBUG  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now src/suggest/CMakeFiles/groonga-suggest-learner.dir/groonga_suggest_learner.c.o  -o src/suggest/groonga-suggest-learner  -Wl,-rpath,/build/groonga-14.1.1/obj-x86_64-linux-gnu/lib:  src/suggest/libgroonga-suggest-util.a  lib/libgroonga.so.0.0.0  /usr/lib/x86_64-linux-gnu/libmsgpackc.so  /usr/lib/x86_64-linux-gnu/libevent.so  /usr/lib/x86_64-linux-gnu/libzmq.so && :
FAILED: …
```

ci package ubuntu focal: add missing Threads::Threads dependencies

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_geo.po
doc/source/reference/api/grn_geo.rst

GitHub: GH-2103
In the GH-2103, we forgot to remove the moved documentation. This PR deals with it.

docs: api/grn_geo: remove grn_geo_estimate_in_rectangle() reference

---

lib/pat.c
test/command/suite/load/patricia_trie/bit_less_from_first_segment.expected
test/command/suite/load/patricia_trie/bit_less_from_first_segment.test
test/command/suite/load/patricia_trie/bit_over_from_first_segment.expected
test/command/suite/load/patricia_trie/bit_over_from_first_segment.test
test/command/suite/load/patricia_trie/use_first_segment_in_full.expected
test/command/suite/load/patricia_trie/use_first_segment_in_full.test

When the next length to be added equals `GRN_PAT_SEGMENT_SIZE`, move on to the next segment.
But, if the size is the equal, it can be written to the current segment, so it was fixed so that it can be calculated correctly.
The `grn_io` layer allocates an space of `GRN_PAT_SEGMENT_SIZE`.

pat: Fix the calculation for the target segment

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_geo.po
doc/source/reference/api/grn_geo.rst
include/groonga/geo.h

docs: api/grn_geo: move grn_geo_cursor_next() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_ctx.po
doc/source/reference/api/grn_ctx.rst
include/groonga/output.h

docs: api/grn_ctx: move `grn_ctx_set_output_type()` reference to the header file

---

.pre-commit-config.yaml
include/groonga/portability.h
lib/c_sources.am
lib/cpp_sources.am
lib/grn_portability.h
lib/portability.cpp

Since there is no portability in qsort_s() or qsort_r(), drop wrapping them.
For now, add a function to sort the grn_id array.
(The best is to implement a function that can sort any data with `void *`.)

Add grn_qsort_r_grn_id() to sort the grn_id array

---

lib/pat.c

Since `ts` (short for `tail_segment`) is not easy to understand, change it to `end_segment`.

pat key_put: Improve variable name

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_ctx.po
doc/source/reference/api/grn_ctx.rst
include/groonga/groonga.h

docs: api/grn_ctx: move summary to the header file

---

lib/pat.c

If the same key already exists, it is not copied.

pat: defrag: Optimize the defragmentation process, no unnecessary copying

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_ctx.po
doc/source/reference/api/grn_ctx.rst
include/groonga/output.h

docs: api/grn_ctx: move grn_ctx_get_output_type() reference to the header file

---

lib/pat.c

The code is unchanged, just moved.
Preparation to support WAL with defragmentation. To avoid “warning: implicit declaration of function”.

pat: Move defrag code before WAL code

---

Rakefile
blog_task.rb
release_task.rb

GitHub: GH-2114
In this PR, we prepare a rake task for generating release
announces in blog from the release note. 
At the following PRs, we will implement the logic and contents
step by step.
- The rake task is registered.
```console
$ rake -T | grep announce
git ls-files
rake release:blog:generate    # Generate release announce posts from a release note
```
- Call this rake task
```console
rake release:blog:generate
git ls-files
TODO: Generate release announce posts for Groonga
```

release blog: generate blog post from release note

---

cmake/GroongaSphinx.cmake

Because there is a lot of output and it is hard to find out what is causing the warning.
```
$ sphinx-build --help | grep quiet
--quiet, -q           no output on stdout, just warnings on stderr
```

cmake: docs: Add `--quiet` option to sphinx-build

---

.github/workflows/package.yml
.github/workflows/release.yml

When the tag is pushed, the first release page is created.
It is easier to upload archive files for multiple jobs.

ci: Create the release page first

---

doc/locale/ja/LC_MESSAGES/reference/api/global_configurations.po
doc/source/reference/api/global_configurations.rst
include/groonga/groonga.h

docs: api/global_configurations move grn_get_lock_timeout() reference to the header file

---

.github/workflows/document.yml
doc/Gemfile

We need to install Red Datasets explicitly to use gettext gem's auto locale information fill feature.
`Plural-Forms` is output correctly and the following warnings are no longer printed.
```
WARNING: reading error: /home/runner/work/groonga/groonga/doc/source/../locale/en/LC_MESSAGES/news/1.1.po, invalid literal for int() with base 10: ''
```
Plural-Forms before: `"Plural-Forms: nplurals=; plural=;\n"`
Plural-Forms after : `"Plural-Forms: nplurals=2; plural=n != 1;\n"`

docs: Add required gem, red-datasets

---

doc/locale/ja/LC_MESSAGES/reference/api/global_configurations.po
doc/source/reference/api/global_configurations.rst
include/groonga/groonga.h

docs: api/global_configurations move grn_set_lock_timeout() reference  to the header file

---

.github/workflows/autotools.yml

Because Cutter does not package for Ubuntu 24.

ci: autotools: Drop test with Cutter

---

test/command_line/helper/command_runner.rb

When running `grndb` tests in a Windows environment, encoding file paths
containing Japanese characters failed in the test logs. It caused tests to
fail.
This issue occurred because file paths encoded in CP932 were misinterpreted as
UTF-8 and then converted to UTF-8. The root of the problem lies in the change of
Ruby's behavior. From Ruby 3.0, `Encoding.find("filesystem")` now returns
"UTF-8" instead of the expected CP932 on Windows. Previously, `grndb` would have
treated CP932 data correctly, converting them from CP932(`"filesystem"`) to
UTF-8 without issues by Ruby. With the change, the conversion was incorrectly
attempting to interpret CP932 data as UTF-8(`"filesystem"`), which led to
failures.
- `grndb` outputs results using the encoding specified by the system locale.
- On Windows, …

test command-line: use locale encoding for Japanese file paths on Windows

---

lib/nfkc.c

Passing an invalid `version` of the value will cause a crash.
Example:
```
> normalize 'NormalizerNFKC("version", true)' "groonga" WITH_CHECKS|WITH_TYPES
Aborted (core dumped)
```
GRN_TEXT_INIT was missing, so add it.

nfkc: Add GRN_TEXT_INIT()

---

lib/index_column.c

If we execute `index_column_diff` and `load` at the same time, `index_column_diff` may set an error while it traversing updating posting lists.
However, `index_column_diff` continues processing with ignoring errors. In this case, `index_column_diff` may be slow because it outputs many error logs.
By this change, `index_column_diff` interrupts its process immediately when an error is ocurered.

index_column_diff: interrupt process immediately on error

---

lib/index_column.c

If progress log interval is too small, interval seconds may be zero. If interval seconds is zero, the current implementation reports "inf" throughput.
We should not use "inf" for throughput.

index_column_diff: avoid zero division in progress log

---

lib/ii.cpp

In general, we should call `init()`/`fin()` as a pair. `grn_ii_select()` calls `grn_ii_select_data_init()`. So it should ensure calling `grn_ii_select_data_fin()`. But there are some cases that `grn_ii_select_data_fin()` isn't called.
There is no memory leak in those cases. But we should call `grn_ii_select_data_fin()` for consistency.

grn_ii_select: add missing grn_ii_select_data_fin() calls 

---

doc/locale/ja/LC_MESSAGES/reference/normalizers/normalizer_nfkc.po
doc/source/reference/normalizers/normalizer_nfkc.rst

* NormalizerNFKC added in 14.1.3
* Remove `versionadd` since each option already exists

docs: NormalizerNFKC: Update versionadded information

---

doc/locale/ja/LC_MESSAGES/reference/normalizers/normalizer_nfkc.po
doc/locale/ja/LC_MESSAGES/reference/normalizers/normalizer_nfkc100.po
doc/locale/ja/LC_MESSAGES/reference/normalizers/normalizer_nfkc121.po
doc/locale/ja/LC_MESSAGES/reference/normalizers/normalizer_nfkc130.po
doc/locale/ja/LC_MESSAGES/reference/normalizers/normalizer_nfkc150.po
doc/locale/ja/LC_MESSAGES/reference/normalizers/normalizer_nfkc51.po
doc/source/reference/normalizers/normalizer_nfkc.rst
doc/source/reference/normalizers/normalizer_nfkc100.rst
doc/source/reference/normalizers/normalizer_nfkc121.rst
doc/source/reference/normalizers/normalizer_nfkc130.rst
doc/source/reference/normalizers/normalizer_nfkc150.rst
doc/source/reference/normalizers/normalizer_nfkc51.rst

Guide the use of `NormalizerNFKC` instead.
With this change we noticed that NormalizerNFKC51 is actually for Unicode 5.0, so we added a note about that.

docs: NormalizerNFKC*: Add a note about deprecation

---

doc/files.am
doc/files.cmake
doc/locale/ja/LC_MESSAGES/reference/token_filters/token_filter_nfkc.po
doc/source/reference/normalizers/normalizer_nfkc.rst
doc/source/reference/token_filters/token_filter_nfkc.rst

`TokenFilterNFKC150` was used as a base.
We also tried to refer to `NormalizerNFKC` as much as possible.
An example of execution will be updated later.

docs: Add TokenFilterNFKC reference

---

doc/locale/ja/LC_MESSAGES/reference/token_filters/token_filter_nfkc100.po
doc/locale/ja/LC_MESSAGES/reference/token_filters/token_filter_nfkc150.po
doc/source/reference/token_filters/token_filter_nfkc100.rst
doc/source/reference/token_filters/token_filter_nfkc150.rst

Guide the use of `TokenFilterNFKC` instead.

docs: TokenFilterNFKC*: Add a note about deprecation

---

Rakefile

Since it is necessary to push finally.
mroonga/mroonga also does so.
https://github.com/mroonga/mroonga/blob/110095fd48db417b80fada90a6bbe639391b72d1/Rakefile#L114-L131

rake: release: Run `git push` at the end of `release:version:update` task

---

lib/pat.c
test/command/suite/select/filter/index/compare_operation/greater/float32.expected
test/command/suite/select/filter/index/compare_operation/greater/float32.test
test/command/suite/select/filter/index/compare_operation/greater_equal/float32.expected
test/command/suite/select/filter/index/compare_operation/greater_equal/float32.test
test/command/suite/select/filter/index/compare_operation/less/float32.expected
test/command/suite/select/filter/index/compare_operation/less/float32.test
test/command/suite/select/filter/index/compare_operation/less_equal/float32.expected
test/command/suite/select/filter/index/compare_operation/less_equal/float32.test
test/command/suite/select/filter/index/equal/float32.expected
test/command/suite/select/filter/index/equal/float32.test

Currently, Groonga doesn't support Float32 as a key of patricia trie table.
So, Groonga can't encode Float32 value correctly when we register
Float32 value as a key of patricia trie table.
In this case, we can't get result correctly as below.
```
table_create Lexicon TABLE_PAT_KEY Float32
table_create Numbers TABLE_HASH_KEY UInt64
column_create Numbers id COLUMN_SCALAR Float32
load --table Numbers
[
["_key","id"],
[1,1.1],
[2,2.1],
[3,3.1]
]
column_create Lexicon index COLUMN_INDEX Numbers id
select Numbers --filter 'id >= 2.1' --output_pretty yes
[
[
0,
1738641494.864537,
0.002141714096069336
],
[
[
[
1
],
[
[
"_id",
"UInt32"
],
[
"_key",
"UInt64"
],
[
"id",
"Float32"
]
],
[
1,
1,
1.1
]
]
]
]
```

pat: add support for Float32 as key type

---

.github/workflows/cmake.yml

Previously, the workflow checked out a fixed Apache Arrow repository revision(ref: apache-arrow-18.0.0).
This change replaces that step with a process that queries the GitHub API for the latest Apache Arrow release and downloads its official source archive from the Apache mirror.

ci cmake: use latest Apache Arrow source archive

---

lib/geo.c

Change to bool because the usage is as bool.

geo: Change the argument `include_base_point_mesh` of `grn_geo_get_meshes_for_circle()` to bool

---

Rakefile

We can get the next version with `String#succ`.
```
irb(main):001:0> "15.0.0".succ
=> "15.0.1"
irb(main):002:0> "15.0.9".succ
=> "15.1.0"
```
It is no longer necessary to specify in `NEW_VERSION`.

rake: Automatically set version

---

Rakefile

There are two types of `version`, variable and method, and it is hard to understand, so it is improved.

rake: Change the top level `version` variable to a constant

---

packages/apt/test.sh
packages/apt/ubuntu-jammy/Dockerfile
packages/apt/ubuntu-noble/Dockerfile

Previously, we did not provide Groonga with Apache Arrow in the Launchpad because Launchpad could not reference Apache Arrow. By distributing from packages.groonga.org instead, we remove that restriction.
Enabling Apache Arrow as a dependency in Groonga unlocks additional features, including the recently added static parallel index building support. By adding Apache Arrow to Groonga dependencies, these features become available.

packages ubuntu: support Apache Arrow in packages.groonga.org

---

doc/locale/ja/LC_MESSAGES/install/ubuntu.po
doc/source/install/ubuntu.md

GitHub: close GH-2223
Because we has already dropped Lunar and supported Noble.

docs install/ubuntu: update supported versions

---

doc/locale/ja/LC_MESSAGES/contribution/development/release.po
doc/source/contribution/development/release.rst

We are not notifying the mailing list now.

docs: release: Remove the announcement task to the mailing lists

---

packages/apt/test.sh
test/command/suite/tokenizers/document_vector_bm25/alphabet.test
test/command/suite/tokenizers/document_vector_bm25/reindex.test
test/command/suite/tokenizers/document_vector_bm25/token_column.test
test/command/suite/tokenizers/document_vector_bm25/token_column_different_lexicon.test

If we use grntest to determine whether we can use a test or not instead of executing `rm` before we run a test, developers don't need to execute `rm`.

test tokenizers/document_vector_bm25: use grntest not rm for x86_64 specific tests

---

test/command/suite/tokenizers/document_vector_bm25/alphabet.test
test/command/suite/tokenizers/document_vector_bm25/reindex.test
test/command/suite/tokenizers/document_vector_bm25/token_column.test
test/command/suite/tokenizers/document_vector_bm25/token_column_different_lexicon.test

`status`'s `"cpu"` uses `CMAKE_SYSTEM_PROCESSOR` (`CMAKE_HOST_SYSTEM_PROCESSOR` for non cross-compiling). It uses `uname -m` on Linux and `uname -p` on macOS:  https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html
`uname -m` on aarch64 Linux returns `aarch64` not `arm64` and `uname -p` on arm macOS returns `arm` not `arm64`. So `!arm64` didn't work as we expected.
We confirmed the current expected values are valid only on x86_64 for now. The current expected values may work on other architecture but we use them only for x86_64 safety and easy to maintain.
So let's use `x86_64` for now.

test tokenizers/document_vector_bm25: use "x86_64" not "!arm64"

---

.github/workflows/cmake.yml
.github/workflows/document.yml
.github/workflows/package.yml
.github/workflows/release.yml

This PR changes our release workflow trigger from using workflow_call to a push event (tag push). The motivations are as follows.
Using `workflow_call` requires that every calling workflow supply necessary variables and secrets. It means each workflow must have access to sensitive information. This increases the risk of misconfiguration or potential leaks. Switching to a tag push trigger allows the release workflow to manage its own secrets internally. It reduces exposure and simplifies the configuration process.
ref: https://docs.github.com/en/actions/sharing-automations/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
Adopting the release event approach aligns our process with related projects like PGroonga and Mroonga. Standardizing on the tag push method improves …

ci release: switch release workflow trigger from workflow_call to tag push event

---

doc/locale/ja/LC_MESSAGES/reference/regular_expression.po
doc/source/reference/regular_expression.rst

Only "\A" and "\z" can be evaluated by index.

doc reference regular expression: fix wrong description about index ready

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_cache.po
doc/source/reference/api/grn_cache.rst
include/groonga/cache.h

docs: api/grn_cache move grn_cache_close() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_cache.po
doc/source/reference/api/grn_cache.rst
include/groonga/cache.h

docs: api/cache move grn_cache_get_max_n_entries() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_cache.po
doc/source/reference/api/grn_cache.rst
include/groonga/cache.h

docs: api/cache move grn_cache_set_max_n_entries() reference to the header file

---

.github/workflows/package.yml
packages/Rakefile

Debian trixie on CI is failing because Apache Arrow depends on libre2-11-absl20230802, which is no longer available. Trixie now provides libre2-11 version 20240702-3, causing a dependency mismatch during the Apache Arrow build.
ref: https://packages.debian.org/trixie/libre2-11
```
12.71 Unsatisfied dependencies:
12.77  libarrow1900 : Depends: libre2-11-absl20230802 but it is not installable
12.77 Error: Unable to correct problems, you have held broken packages.
```
ref: https://github.com/groonga/groonga/actions/runs/13889234637/job/38858485115
We will re-enable these tests once Apache Arrow is rebuilt with the updated dependency, expected in the next release in April.

ci debian trixie: disable because of Apache Arrow dependencies' mismatch

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_cache.po
doc/source/reference/api/grn_cache.rst
include/groonga/cache.h

docs: api/cache move grn_cache_current_get() reference to the header file

---

CMakeLists.txt
lib/expr_executor.cpp
test/command/suite/select/filter/arithmetic_operation/slash/int64_max_in_uint64_and_minus_float_one.expected
test/command/suite/select/filter/arithmetic_operation/slash/int64_max_in_uint64_and_minus_float_one.test
test/command/suite/select/filter/arithmetic_operation/slash/int64_max_in_uint64_and_minus_one.expected
test/command/suite/select/filter/arithmetic_operation/slash/int64_max_in_uint64_and_minus_one.test
test/command/suite/select/filter/arithmetic_operation/slash/uint32_max_and_minus_float_one.expected
test/command/suite/select/filter/arithmetic_operation/slash/uint32_max_and_minus_float_one.test
test/command/suite/select/filter/arithmetic_operation/slash/uint32_max_and_minus_one.expected
test/command/suite/select/filter/arithmetic_operation/slash/uint32_max_and_minus_one.test
test/command/suite/select/filter/arithmetic_operation/slash/uint64_max_and_minus_float_one.expected
test/command/suite/select/filter/arithmetic_operation/slash/uint64_max_and_minus_float_one.test
test/command/suite/select/filter/arithmetic_operation/slash/uint64_max_and_minus_one.expected
test/command/suite/select/filter/arithmetic_operation/slash/uint64_max_and_minus_one.test

This is to avoid the following warning.
```
warning C4146: unary minus operator applied to unsigned type, result still unsigned
```

expr_executor: operation slash: Separate implements when uint32_t or uint64_t and when not

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_cache.po
doc/source/reference/api/grn_cache.rst
include/groonga/cache.h

docs: api/cache move grn_cache_current_set() reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_cache.po
doc/source/reference/api/grn_cache.rst
include/groonga/cache.h

docs: api/cache move grn_cache type reference to the header file

---

doc/source/contribution/development/release.rst

Can be released by `rake release` as well as groonga/groonga.
https://github.com/groonga/groonga.org/pull/96

docs: release: Update command to run in groonga/groonga.org

---

lib/expr_executor.cpp
test/command/suite/select/filter/arithmetic_operation/slash/uint16_max_and_minus_float_one.expected
test/command/suite/select/filter/arithmetic_operation/slash/uint16_max_and_minus_float_one.test
test/command/suite/select/filter/arithmetic_operation/slash/uint16_max_and_minus_one.expected
test/command/suite/select/filter/arithmetic_operation/slash/uint16_max_and_minus_one.test
test/command/suite/select/filter/arithmetic_operation/slash/uint8_max_and_minus_float_one.expected
test/command/suite/select/filter/arithmetic_operation/slash/uint8_max_and_minus_float_one.test
test/command/suite/select/filter/arithmetic_operation/slash/uint8_max_and_minus_one.expected
test/command/suite/select/filter/arithmetic_operation/slash/uint8_max_and_minus_one.test

Related Commit:
https://github.com/groonga/groonga/commit/138a586b597e136df33fffac30c031288c8bd949
`UInt8 / -1` and `UInt16 / -1` should also be negative.

expr_executor: operation slash: Separate cases by uintN_t

---

doc/locale/ja/LC_MESSAGES/install/ubuntu.po
doc/source/install/ubuntu.md

GitHub: GH-2253
This is a first step to write the documentation to
recommend using packages.groonga.org instead of the
PPA.
Groonga packages for Ubuntu were available only
through the PPA on Launchpad (ppa:groonga/ppa).
Now packages are also distributed via our Groonga APT
repository at https://packages.groonga.org/.
Packages from our Groonga APT repository
(https://packages.groonga.org/) include Groonga built
with Apache Arrow enabled, which unlocks extra
features such as parallel offline index building.

docs ubuntu: add packages.groonga.org as Groonga APT repository

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_content_type.po
doc/source/reference/api/grn_content_type.rst
include/groonga/groonga.h

docs: api/grn_content_type move grn_content_type enum reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_expr.po
doc/source/reference/api/grn_expr.rst
include/groonga/expr.h

docs: api/grn_expr move grn_expr_get_keywords reference to the header file

---

test/command_line/helper/command_runner.rb

On Windows, `log_path.read.encoding` is UTF-8, but the characters may be broken.
In such a case, conversion with `encode("UTF-8", "Windows-31J")` will result in the expected encoding.
Even if the encoding of the log is UTF-8, the result of `encode("UTF-8", "Windows-31J")` will not be broken.

test: command_line: Fix encoding conversion of logs

---

lib/expr.c

GitHub: https://github.com/groonga/groonga/pull/2268#discussion_r2030946821
This change aligns the function definition with its implementation by renaming the parameters.

grn_expr_syntax_escape: fix mismatched parameter names

---

doc/locale/ja/LC_MESSAGES/install/ubuntu.po
doc/source/conf.py
doc/source/install/ubuntu.md

GitHub: GH-2253
We plan to gradually migrate Ubuntu package provisioning from the old PPA (ppa:groonga/ppa) to the new repository at packages.groonga.org. So we want to update our documentation to recommend using packages.groonga.org instead of the PPA.

doc install/ubuntu: remove deprecated PPA steps

---

doc/source/contribution/documentation/introduction.md
doc/source/news/13.md
doc/source/news/14.md
doc/source/news/15.md

GitHub: https://github.com/groonga/groonga/pull/2271#discussion_r2034482549
It seems that recent MyST-Parser accepts the following Prettier style format as reference directive(?):
```markdown
(XXX)=
```
So we can remove these `prettier-ignore`.

docs: remove needless prettier-ignore

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_expr.po
doc/source/reference/api/grn_expr.rst
include/groonga/expr.h

docs: api/grn_expr move grn_expr_syntax_escape reference to the header file

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_expr.po
doc/source/reference/api/grn_expr.rst
include/groonga/expr.h

docs: api/grn_expr move grn_expr_syntax_escape_query reference to the header file

---

lib/arrow.cpp

Currently only one metadata can be set.
Change it so that multiple metadata can be set.
Related: GitHub GH-2274

output: apache-arrow: Support for multiple metadata

---

.github/workflows/cmake.yml
CMakeLists.txt

GitHub: GH-2273
GitHub: ref https://github.com/groonga/groonga/pull/2270#issuecomment-2785257730
MariaDB bundles Groonga. With the recent UBSAN improvements in MariaDB,
UBSAN errors are detected in the Groonga layer. To catch undefined behavior
issues and ensure robust integration, this change adds a new UBSAN build configuration.
This UBSAN support is implemented only with Clang because GCC doesn't support the `-fno-sanitize=alignment` option,
leading to numerous misalignment errors. And also, MariaDB is using this option too.
ref: https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#usage
ref: https://github.com/MariaDB/server/blob/22efc2c784e1b7199fb5804e6330168277ea7dce/CMakeLists.txt#L239

ci make: support UBSAN

---

lib/CMakeLists.txt

Configuring with `-DGRN_WITH_LLAMA_CPP=system` caused CMake error out.
```
cmake -S . -B ../groonga.build --preset=debug-default -DCMAKE_INSTALL_PREFIX=/tmp/local -DGRN_WITH_LLAMA_CPP=system
...
-- Configuring done (9.3s)
CMake Error at lib/CMakeLists.txt:191 (target_link_libraries):
The link interface of target "libgroonga" contains:
Groonga::llama
but the target was not found.  Possible reasons include:
* There is a typo in the target name.
* A find_package call is missing for an IMPORTED target.
* An ALIAS target is missing.
-- Generating done (0.0s)
```
We were unconditionally injecting INTERFACE links to Groonga::llama, Groonga::ggml and Groonga::ggml-base even when using the system-installed (shared) llama.cpp packages. Those imported targets only exist when we bundle and build …

cmake llama.cpp: fix build error when using system-provided llama.cpp

---

Rakefile

GitHub: GH-2286
This change will extracts the summary from News (
Release notes) for posting it to SNS as release
announces.
```console
$ VERSION=15.0.4 rake release:announce
```

release: extract release announce from News

---

packages/yum/almalinux-8/Dockerfile
packages/yum/test.sh

Error in build because Groonga repository dropped serving arrow-devel-x.x.x.

package: almalinux8: Add Apache Arrow repository install

---

.github/workflows/document.yml
.github/workflows/release.yml
.gitignore
Gemfile
Rakefile

GitHub: GH-2286
This change will post the release summary from News (Release notes) to X.

release: post announce to X

---

doc/source/reference/command/output_trace_log.md

The correct name is `output_type`.

docs: Fix the option name of the output type

---

lib/db.c
lib/hash.c
lib/ii.cpp

GitHub: ref https://github.com/MariaDB/server/pull/3932
GitHub: GH-2273
This changes replace unsafe pointer arithmetic with `offsetof()` for calculating structure field offsets.
And they also fix the following runtime errors.
- runtime error: member access within null pointer of type 'grn_plain_hash_entry'
- runtime error: member access within null pointer of type 'grn_tiny_hash_entry'
- runtime error: member access within null pointer of type 'grn_io_hash_entry_normal'
- runtime error: member access within null pointer of type 'grn_io_hash_entry_large'
- runtime error: member access within null pointer of type 'grn_rich_hash_entry'
- runtime error: member access within null pointer of type 'grn_ii_builder_term'
- runtime error: member access within null pointer of type 'grn_rset_recinfo'

Use `offsetof()` for Groonga record and hash entry size calculations

---

dockerfiles/run.sh

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#grouping-log-lines
```text
::group::{title}
::endgroup::
```

ci alpine-linux: add missing trailing "::" for "::endgroup"

---

.github/workflows/cmake.yml

It's for readability. `env:` is used in `run:`. If we have `env:` before `run:`, we can read `run:` with "what environment variables are used in this `run:`" information.

ci: set `env:` before `run:`

---

doc/source/reference/commands/table_tokenize.rst
doc/source/reference/commands/tokenize.rst

This changes fix the `versionadded` because the next version isn't 15.0.7 but 15.0.8.

docs commands/table_tokenize|tokenize: fix `versionadded`

---

lib/proc/proc_tokenize.c
test/command/suite/table_tokenize/output_style/full.expected
test/command/suite/table_tokenize/output_style/full.test
test/command/suite/table_tokenize/output_style/simple.expected
test/command/suite/table_tokenize/output_style/simple.test

This change introduces a `output_style` option to the `table_tokenize` command. It will get easier for users to know only tokenized tokens when they want to focus on them.
- **full** (default): preserves the existing behavior.
- **simple**: shows only tokens like `["We","are", …]` for readability.

table_tokenize: add `--output_style` option

---

packages/debian/changelog
packages/yum/groonga.spec.in

This reverts commit be4c85460ae076115e10a225fe44b49c2c2a88fc.
Wrong version.
Correct version is 15.0.8.

Revert "package: update version info to 15.0.5 (2025-05-08)"

---

doc/requirements.txt

This is a workaround.
Document build fails when snowballstemmer 3.0.0 or later is installed.
Error example:
```
Traceback
=========
File "/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/snowballstemmer/__init__.py", line 27, in stemmer
raise KeyError("Stemming algorithm '%s' not found" % lang)
KeyError: "Stemming algorithm 'porter' not found"
```

docs: requirements: Specify the version of snowballstemmer

---

doc/locale/ja/LC_MESSAGES/news/15.po
doc/source/news/15.md

Because we mistake a release of Groonga 15.0.8.
So, we will skip 15.0.8.

doc news: update release version

---

.github/workflows/release.yml

https://github.com/groonga/groonga/actions/runs/14903554778/job/41867597413#step:4:111
```text
$ git shortlog -sn v15.0.4..
fatal: ambiguous argument 'v15.0.4..': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

ci release: fix contributors generation

---

.github/workflows/release.yml
Gemfile
Rakefile

GitHub: GH-2315
In release workflow, the following error happened
because gem `x` isn't loaded.
```
Run VERSION=${GITHUB_REF_NAME#v} rake release:announce
VERSION=${GITHUB_REF_NAME#v} rake release:announce
shell: /usr/bin/bash -e {0}
env:
X_API_KEY: ***
X_API_KEY_SECRET: ***
X_ACCESS_TOKEN: ***
X_ACCESS_TOKEN_SECRET: ***
git ls-files
rake aborted!
LoadError: cannot load such file -- x (LoadError)
<internal:/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
<internal:/opt/hostedtoolcache/Ruby/3.4.3/x64/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
/home/runner/work/groonga/groonga/Rakefile:223:in 'block (2 levels) in <top (required)>'
Tasks: TOP => release:announce
(See full trace by running task …
```

ci release: fix gem load error

---

lib/db.c

Using UBSAN raised the following error.
```
/home/runner/work/groonga/groonga/lib/db.c:1274:31: runtime error: applying zero offset to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/runner/work/groonga/groonga/lib/db.c:1274:31
```
We tried to calculate the offset by adding name_size to null pointer in `name = NULL` case.

db: handle empty names and null pointers

---

lib/grn_pat.h
lib/pat.c

I also modify the return value type of `grn_pat_total_key_size()`.
However, no problem that the return value type of `grn_pat_total_key_size()` is change to `uint64_t` from `uint32_t`.
Because the following two reasons.
1. Currently, `grn_pat_total_key_size()` use only as argument of `grn_ctx_output_uint64()` as below.
```c
grn_ctx_output_uint64(ctx, grn_pat_total_key_size(ctx, pat));
```
2. The second argument type of `grn_ctx_output_uint64()` is uint64_t as below. 
```c
void
grn_ctx_output_uint64(grn_ctx *ctx, uint64_t value)
{
grn_output_uint64(ctx, ctx->impl->output.buf, ctx->impl->output.type, value);
}
```

pat:  grn_pat_total_key_size() support KEY_LARGE flag

---

.github/workflows/cmake.yml

During the last release flow, our CMake build job failed and blocked the Groonga release.
This change makes the CMake workflow run daily, preventing it from silently becoming a blocker.
We’ve scheduled the CMake build to run daily at 23:00 UTC (which finishes around 08:00 JST).
This timing also helps us catch any breakages early on release day.

ci cmake: run daily

---

doc/source/reference/commands/column_create.rst

docs: reference/commands/column_create: Remove trailing-whitespace

---

packages/windows/download_github_actions_artifact.rb

Allow downloading GitHub Actions artifacts from
repositories other than the default 'groonga/groonga' by accepting an optional REPOSITORY parameter.
This enables downloading artifacts from forks or
other related repositories.

packages windows: add support for specifying custom repository in artifact downloader

---

lib/pat.c

This commit is part of the work to implement #2349.
We add a new struct for pat node has large key.
Because we don't allocate a needless memory space when we don't use `KEY_LARGE` flag.
We implement only definition of a new struct and a new union in this commit.
We will implement codes use this struct and union by the other commit.

pat: add support for pat node has large key offset

---

doc/locale/ja/LC_MESSAGES/reference/api/grn_inspect.po
doc/source/reference/api/grn_inspect.rst
include/groonga/util.h

docs: api/grn_inspect move grn_inspect_query_log_flags reference to the header file

---

dockerfiles/arch-linux.dockerfile

Fix the following errors:
```
/usr/libexec/mecab/mecab-dict-index -d . -o . -f EUC-JP -t utf-8
make: /usr/libexec/mecab/mecab-dict-index: No such file or directory
make: *** [Makefile:253: matrix.bin] Error 127
```
https://aur.archlinux.org/cgit/aur.git/commit/?h=mecab-ipadic&id=b8615a7971376441d4954362e8209b1ee4f9c60e
```
sed -i "s|^MECAB_DICT_INDEX=.*|MECAB_DICT_INDEX=/usr/lib/mecab/mecab-dict-index|g" configure.in
```
Use the replaced `configure.in`.

ci build: archlinux: fix mecab ipadic build failure

---

doc/source/reference/commands/index_column_diff.rst

docs: reference/commands/index_column_diff: Replace horizontal-tab with spaces

---

.gitignore

Because the downloaded `vendor/usearch-x.x.x.tar.gz` is listed in `Untracked files:`.

Add `/vendor/usearch-*` to .gitignore

---

doc/source/reference/functions/between.rst
doc/source/reference/functions/in_values.rst
doc/source/reference/functions/string_slice.rst
doc/source/reference/functions/string_substring.rst

docs: reference/functions/*: Remove trailing-whitespace

---

doc/locale/ja/LC_MESSAGES/reference/tokenizers/token_delimit.po
doc/source/reference/tokenizers/token_delimit.rst

Space is not allowed just after "``", so HTML is not generated as expected.
Enclosing in double quotes avoids this issue.
In addition to enclosing a space with `"`, `,` is also enclosed in the same way.

docs: tokenizers/token_delimit: Fix an unbalanced inline literal markup

---

doc/locale/ja/LC_MESSAGES/reference/grn_expr/script_syntax.po
doc/source/reference/grn_expr/script_syntax.rst

```
BAD:  ``\\''
GOOD: ``\``
```
* In BAD, inline literal is closed with a single quote
* If we need to display a backslash in an inline literal, we only need one

docs: grn_expr/script_syntax: Fix an unbalanced inline literal markup

---

lib/ii.cpp
test/command/suite/select/filter/ordered_near_phrase/max_element_intervals/multi_tokens/all.expected
test/command/suite/select/filter/ordered_near_phrase/max_element_intervals/multi_tokens/all.test
test/command/suite/select/filter/ordered_near_phrase/max_element_intervals/multi_tokens/less.expected
test/command/suite/select/filter/ordered_near_phrase/max_element_intervals/multi_tokens/less.test
test/command/suite/select/filter/ordered_near_phrase/max_element_intervals/multi_tokens/more.expected
test/command/suite/select/filter/ordered_near_phrase/max_element_intervals/multi_tokens/more.test
test/command/suite/select/filter/ordered_near_phrase/min_interval/with_max_element_intervals/not_match_more_max.expected
test/command/suite/select/filter/ordered_near_phrase/min_interval/with_max_element_intervals/not_match_more_max.test
test/command/suite/select/query/ordered_near_phrase/max_element_intervals/multi_tokens/all.expected
test/command/suite/select/query/ordered_near_phrase/max_element_intervals/multi_tokens/all.test
test/command/suite/select/query/ordered_near_phrase/max_element_intervals/multi_tokens/less.expected
test/command/suite/select/query/ordered_near_phrase/max_element_intervals/multi_tokens/less.test
test/command/suite/select/query/ordered_near_phrase/max_element_intervals/multi_tokens/more.expected
test/command/suite/select/query/ordered_near_phrase/max_element_intervals/multi_tokens/more.test
test/command/suite/select/query/ordered_near_phrase/min_interval/with_max_element_intervals/not_match_more_max.expected
test/command/suite/select/query/ordered_near_phrase/min_interval/with_max_element_intervals/not_match_more_max.test

Currently, we can not calculate correctly interval between phrase.
We calculate interval between phrase as below expression.
```
interval = pos - previous_pos - token_info->n_tokens_in_phrase;
```
However, the avobe expression can not calculate correctly interval.
Because we use token_info->n_tokens_in_phrase.
We should use the n_tokens_in_phrase of previous phrase.
This problem only occurs when we use max element intervals.
Because if we don't use max element intervals, Groonga does not reach posint that cause the problem.
---
For example, if we calculate interval between phrase "abc defghi jklmnop" in "abc123456defghi".
(We use `TokenNgram("unify_alphabet", false, "unify_digit", false)` and `NormalizerNFKC121` in this case.)
Curretnnly:
```
interval = pos - previous_pos - …
```

ii order-near-phrase: fix interval caclulation

---

.github/workflows/cmake.yml
doc/locale/ja/LC_MESSAGES/install/windows.po
doc/source/install/windows.rst
packages/Rakefile

windows-2019's runner image has reached EOL on GitHub Actions.
See: https://github.com/actions/runner-images/issues/12045

packages windows: drop support for windows-2019

---

lib/ii.cpp
test/command/suite/select/filter/near_phrase/min_interval/with_max_element_intervals/not_match_more_max.expected
test/command/suite/select/filter/near_phrase/min_interval/with_max_element_intervals/not_match_more_max.test
test/command/suite/select/filter/near_phrase_product/min_interval/with_max_element_intervals/not_match_more_max.expected
test/command/suite/select/filter/near_phrase_product/min_interval/with_max_element_intervals/not_match_more_max.test
test/command/suite/select/query/near_phrase/min_interval/with_max_element_intervals/not_match_more_max.expected
test/command/suite/select/query/near_phrase/min_interval/with_max_element_intervals/not_match_more_max.test
test/command/suite/select/query/near_phrase_product/min_interval/with_additional_last_interval/not_match_more_max.expected
test/command/suite/select/query/near_phrase_product/min_interval/with_additional_last_interval/not_match_more_max.test
test/command/suite/select/query/near_phrase_product/min_interval/with_max_element_intervals/not_match_more_max.expected
test/command/suite/select/query/near_phrase_product/min_interval/with_max_element_intervals/not_match_more_max.test

This problem is similar problem to GH-2407.
Currently, we can not calculate correctly interval between phrase in `*NP` and `*NPP` operator too.
`*N` operator also include this problem. However, `*N` operator doesn't occur this problem basiaully.
Because `*N` doesn't process phrases basically.
We should use the number of tokens in phrase of previous phrase in `*NP` and `*NPP` operator too.
However, `*NP` and `*NPP` operator use the number of tokens in phrase of current phrase currently in caculating interval between phrases.
So, we modify that use it of previous phrase in this commit.

ii near-phrase/near-phrase-product: fix interval caclulation

---

lib/pat.c

pat: use pat_node_common instead of pat_node in grn_pat_fuzzy_search

---

lib/pat.c

pat: use pat_node_common instead of pat_node in grn_pat_cursor_open

---

lib/pat.c

pat: use pat_node_common instead of pat_node in prefix search

---

lib/pat.c

I added "_pat_get()" function temporary.
Because if we modify the above functions, we must modify many place in lib/pat.c to prevent build error.
So, I added the above functions temporary to reduce affect.
The above functions will change to functions that have no "_" prefix at the completion of GH-2349.

pat: use pat_node_common instead of pat_node in defrag

---

include/groonga/bulk.hpp

Since `GRN_DB_INT64` and larger already casts the return value, cast it for other types.

bulk: Cast the return value of get()

---

CMakeLists.txt

We got the following error when we built Groonga with MariaDB.
```
/home/buildbot/_deps/simdjson-src/include/simdjson/error.h:89:15: error: 'virtual const char* simdjson::simdjson_error::what() const' can be marked override [-Werror=suggest-override]
89 |   const char *what() const noexcept { return error_message(error()); }
|               ^~~~
```
This issue has already been resolved in simdjson v3.11.1. So we will update the simdjson version.
ref: https://github.com/simdjson/simdjson/pull/2305

cmake: Update simdjson version

---

lib/pat.c

pat: use pat_node_common instead of pat_node in grn_pat_inspect_node

---

lib/pat.c

pat: use pat_node_common instead of pat_node in fuzzy search

---

include/groonga/groonga.h
lib/grn_error.h

This is part of the work of GitHub GH-1641.
`level` is `grn_log_level`, but `ctx::errlvl` is `unsigned char`, so cast it.
https://github.com/groonga/groonga/blob/57809bdcf99041ad4e7fcca87df2642240f81d05/include/groonga/groonga.h#L354

grn_error: Cast when assigning to ctx::errlvl

---

lib/pat.c

pat: use pat_node_common instead of pat_node in grn_p_pat_node

---

lib/ii.cpp
test/command/suite/select/filter/ordered_near_phrase_product/min_interval/with_max_element_intervals/match.expected
test/command/suite/select/filter/ordered_near_phrase_product/min_interval/with_max_element_intervals/match.test
test/command/suite/select/filter/ordered_near_phrase_product/min_interval/with_max_element_intervals/not_match_more_max.expected
test/command/suite/select/filter/ordered_near_phrase_product/min_interval/with_max_element_intervals/not_match_more_max.test
test/command/suite/select/query/ordered_near_phrase_product/min_interval/with_max_element_intervals/match.expected
test/command/suite/select/query/ordered_near_phrase_product/min_interval/with_max_element_intervals/match.test
test/command/suite/select/query/ordered_near_phrase_product/min_interval/with_max_element_intervals/not_match_more_max.expected
test/command/suite/select/query/ordered_near_phrase_product/min_interval/with_max_element_intervals/not_match_more_max.test

This problem is similar problem to GH-2407.
Currently, we can not calculate correctly interval between phrase in `*ONPP` operator too.
We should use the number of tokens in phrase of previous phrase in `*ONPP` operator too.
However, `*ONPP` operator use the number of tokens in phrase of current phrase in caculating interval between phrases.
So, we modify that use it of previous phrase in this commit.

ii ordered-near-phrase-product: fix interval caclulation

---

lib/pat.c

pat: use pat_node_common instead of pat_node in delinfo operation

---

lib/pat.c

pat: use pat_node_common instead of pat_node in related wal recover 

---

lib/pat.c

pat: use pat_node_common instead of pat_node in set_cursor_ascend()

---

lib/pat.c

pat: use pat_node_common instead of pat_node in set_cursor_descend()

---

lib/pat.c

pat: use pat_node_common instead of pat_node in sub_search()

---

lib/pat.c

pat: use pat_node_common instead of pat_node in _grn_pat_key()

---

lib/pat.c

pat: use pat_node_common instead of pat_node in grm_pat_get_key()

---

lib/pat.c

pat: use pat_node_common instead of pat_node in grn_pat_add_internal()

---

lib/pat.c

`pat_get()` is not use since this commit.
So, I replace this function.

pat: use pat_node_common instead of pat_node in _grn_pat_create()

---

lib/pat.c

`grn_pat_next_location()` and `pat_node_get_key()` are not use since this commit.
So, I replace these functions.

pat: use pat_node_common instead of pat_node in _grn_pat_get()

---

lib/grn.h
lib/grn_pat.h
lib/pat.c
test/command/suite/object_inspect/table/have_records/key_large/pat_key.expected
test/command/suite/object_inspect/table/no_record/key_large/pat_key.expected

If we use "KEY_LARGE" in "TABLE_PAT_KEY", max total key size is 1TiB.
However, Groonga returns "UINT64_MAX - 1" currently. This value is too big.

pat: fix a wrong max total key size when we use "KEY_LARGE"

---

lib/pat.c

These macros have already replaced inline functions.
So, I removed them.

pat: remove unused macros

---

lib/normalizer.c
test/command/suite/normalizers/nfkc/mix/remove_symbol_and_unify_hyphen_and_prolonged_sound_mark.expected
test/command/suite/normalizers/nfkc/mix/remove_symbol_and_unify_hyphen_and_prolonged_sound_mark.test

GitHub: fixes GH-1543
When `unify_hyphen_and_prolonged_sound_mark` is enabled, the hyphen becomes a symbol and should be removed with `remove_symbol`.
Related fixes: GH-2080

NormalizerNFKC: Add support for `unify_hyphen_and_prolonged_sound_mark` and `remove_symbol` combination

---

.github/workflows/cmake.yml

GitHub: GH-2434
This allows us to notice any breaking changes in Apache Arrow before their official release,
giving us time to adapt our code accordingly.

ci cmake: use Apache Arrow main branch to detect incompatible changes early

---

.github/workflows/cmake.yml
CMakeLists.txt

C4244 is also a "possible loss of data" warning as well as C4267, so add it.
C4244: 'argument' : conversion from 'type1' to 'type2', possible loss of data
C4267: 'var' : conversion from 'size_t' to 'type', possible loss of data
Add `/W3` because the default is `/W1`, so level2 and level3 are not warnings.
https://learn.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level
> /W1 displays level 1 (severe) warnings. /W1 is the default setting in the command-line compiler.

cmake: Enable C4244 when GRN_WARN_CONVERSION=ON

---

test/command_line/helper/groonga_log.rb

test/command_line/helper/groonga_log.rb:217: warning: literal string will be frozen in the future (run with --debug-frozen-string-literal for more information)
test/command_line/helper/groonga_log.rb:41: warning: literal string will be frozen in the future (run with --debug-frozen-string-literal for more information)

test command-line: suppress warnings

---

test/command/suite/normalizers/nfkc/unify_iteration_mark/hiragana/alphabet.expected
test/command/suite/normalizers/nfkc/unify_iteration_mark/hiragana/alphabet.test
test/command/suite/normalizers/nfkc/unify_iteration_mark/hiragana/kangi.expected
test/command/suite/normalizers/nfkc/unify_iteration_mark/hiragana/kangi.test
test/command/suite/normalizers/nfkc/unify_iteration_mark/hiragana/katakana.expected
test/command/suite/normalizers/nfkc/unify_iteration_mark/hiragana/katakana.test
test/command/suite/normalizers/nfkc/unify_iteration_mark/hiragana/with_voiced_sound_mark.expected
test/command/suite/normalizers/nfkc/unify_iteration_mark/hiragana/with_voiced_sound_mark.test
test/command/suite/normalizers/nfkc/unify_iteration_mark/hiragana/without_voiced_sound_mark.expected
test/command/suite/normalizers/nfkc/unify_iteration_mark/hiragana/without_voiced_sound_mark.test

The @add-substitution directive requires the version parameter to be explicitly specified in the normalize command for the substitution to work correctly. Without it, the test framework cannot properly replace the version value.
ref: https://github.com/groonga/groonga/pull/2500#discussion_r2312788153

test: add version parameter to NormalizerNFKC unify_iteration_mark tests

---

.github/dependabot.yml

ref: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependabot-prs#adding-a-prefix-to-commit-messages

ci: add 'ci:' prefix to Dependabot PRs

---

include/groonga/nfkc.h
lib/nfkc.c
packages/yum/test.sh
plugins/token_filters/stem.c
test/command/suite/token_filters/stem/arabic.expected
test/command/suite/token_filters/stem/arabic.test

GitHub: fix GH-2539
See also: https://github.com/pgroonga/pgroonga/discussions/781
Example: Arabic.
Reported by Tsai, Xing Wei. Thanks!!!

token-filter-stem: add support for non ASCII alphabets

---

CMakeLists.txt
config.h.cmake.in
packages/debian/libgroonga0.install
packages/yum/groonga.spec.in
vendor/download.rb

https://github.com/aklomp/base64
Because it looks faster. It uses SIMD if possible.
Apache Arrow bundles another base64 implementation but it will be slower than it. Because this is a simple base64 implementation.
(I haven't measured them. :p)

Bundle base64 implementation
