lib/mrb/mrb_writer.c
=> mrb writer: bind grn_ctx_set_output_type()

test/command/suite/select/match_columns/section/by_column/4_items/ascending.expected, test/command/suite/select/match_columns/section/by_column/4_items/ascending.test, test/command/suite/select/match_columns/section/by_column/4_items/descending.expected, test/command/suite/select/match_columns/section/by_column/4_items/descending.test
Descending test is failing.
```
--- (expected)
+++ (actual)
@@ -51,7 +51,7 @@
[
"Rroonga",
"Start Rroonga!",
-        4
+        2
]
]
]
```
I added omit mark on this test.
=> test select: add tests for 4 items by column of section

lib/ii.c
Reported by Naoya Murakami. Thanks!!!
=> Store position information to grn_ii_buffer.block_buf

test/command/suite/select/match_columns/section/by_index/4_items/first_weight.expected, test/command/suite/select/match_columns/section/by_index/4_items/first_weight.test, test/command/suite/select/match_columns/section/by_index/4_items/last_weight.expected, test/command/suite/select/match_columns/section/by_index/4_items/last_weight.test, test/command/suite/select/match_columns/section/by_index/4_items/middle_mix_weight.expected, test/command/suite/select/match_columns/section/by_index/4_items/middle_mix_weight.test
```
first_weight:
Lexicon.memo_index[0] * 10 ||
Lexicon.memo_index[1] ||
Lexicon.memo_index[2] ||
Lexicon.memo_index[3]
middle_mix_weight:
Lexicon.memo_index[0] ||
Lexicon.memo_index[1] ||
Lexicon.memo_index[2] * 10 ||
Lexicon.memo_index[3]
last_weight:
Lexicon.memo_index[0] ||
Lexicon.memo_index[1] ||
Lexicon.memo_index[2] ||
Lexicon.memo_index[3] * 10
```
=> test select: add tests for mix weight by index of section

doc/source/tutorial/introduction.rst, doc/source/tutorial/micro_blog.rst, doc/source/tutorial/query_expansion.rst
とりあえずチュートリアルのところだけ変えました。
他の部分は改めて大丈夫そうなら他も同様に置き換えます。
=> Replace deprecated option (KEY_NORMALIZE).

doc/source/reference/commands/select.rst, doc/source/reference/functions/query.rst, doc/source/reference/functions/snippet_html.rst, doc/source/reference/grn_expr/query_syntax.rst, doc/source/reference/grn_expr/script_syntax.rst, doc/source/reference/indexing.rst, doc/source/reference/tuning.rst
リファレンス部分を修正しました。
poファイルを修正する場合はそのままファイルを修正すればよいのでしょうか？
それとも何かコマンドでデータを生成したのち修正する形式でしょうか？
=> doc: replace deprecated option (KEY_NORMALIZE)

doc/locale/ja/LC_MESSAGES/reference.po
=> doc ja: fix typo

lib/output.c, test/command/suite/select/output_columns/float_score.expected, test/command/suite/select/output_columns/float_score.test
I want to output score as float to calculate similarity score such as jaccard similarity and cosine distance.
=> Output score as float when commend_version > 1

include/groonga/groonga.h, include/groonga/token.h, lib/db.c, lib/grn_db.h, lib/grn_ii.h, lib/grn_pat.h, lib/ii.c, lib/pat.c, lib/token_cursor.c
grn_obj_searchからgrn_patとインデックスカラムに対してfuzzyサーチできるようにしました。
よければご確認をお願いします。
unitテストは不慣れで作れていないんですが、作った方がいいでしょうか？
この後、procに関数を作る予定なので、できれば、コマンドテストベースで
テストしたいと思っています。
以下は確認用Cコードです。
https://gist.github.com/naoa/c9bc7460f2dbf35adb18
=> support GRN_OP_FUZZY

lib/proc/proc_fuzzy_search.c
=> proc_fuzzy_search: remove needless goto

lib/proc/proc_fuzzy_search.c
=> proc_fuzzy_search: fix typo

lib/proc/proc_fuzzy_search.c
=> Proc fuzzy unlink

include/groonga/plugin.h, lib/plugin.c
そういえば以前、プラグインでcallocを使いたいことがあったのを思い出しました。
よければ、GRN_PLUGIN_CALLOC()があると嬉しいです。
=> plugin: add grn_plugin_calloc()/GRN_PLUGIN_CALLOC()

lib/proc/proc_snippet.c, test/command/suite/select/function/snippet_full/cache.expected, test/command/suite/select/function/snippet_full/cache.test, test/command/suite/select/function/snippet_full/default_tag.expected, test/command/suite/select/function/snippet_full/default_tag.test, test/command/suite/select/function/snippet_full/empty_option.expected, test/command/suite/select/function/snippet_full/empty_option.test, test/command/suite/select/function/snippet_full/html_escape.expected, test/command/suite/select/function/snippet_full/html_escape.test, test/command/suite/select/function/snippet_full/leading_space.expected, test/command/suite/select/function/snippet_full/leading_space.test, test/command/suite/select/function/snippet_full/max_results.expected, test/command/suite/select/function/snippet_full/max_results.test, test/command/suite/select/function/snippet_full/normalizer.expected, test/command/suite/select/function/snippet_full/normalizer.test, test/command/suite/select/function/snippet_full/prefix.expected, test/command/suite/select/function/snippet_full/prefix.test, test/command/suite/select/function/snippet_full/suffix.expected, test/command/suite/select/function/snippet_full/suffix.test, test/command/suite/select/function/snippet_full/twice_keyword.expected, test/command/suite/select/function/snippet_full/twice_keyword.test
=> snippet_full: allow skip object literal option

lib/ii.c
レアトークンを含むフレーズの高速化のためのii_cursor_set_minですが、現状、毎回チャンクの先頭からgapを埋めていってスキップできるchunkのridを探しています。
この場合、chunk数が結構大きくなると、逆にこのskipできるチャンクを探す処理の負荷の方が大きくなることが多いようでした。
そこで、grn_ii_cursorに~~current_chunk~~ previous chunkのridを保存する領域を持たせて毎回トップからスキップできるチャンクを探すのを回避してみました。（もし、~~current_chunk~~ previous chunkのridをcurrent_chunkとかから計算で求められるなら、それでもよさそうですが、私にはその方法は見つけられませんでした。）
grn_ii_cursorの数ごとにメモリ使用量が4バイトほど増えてしまいますが、トークンごとだと思うので、さほど影響ないのではないかなぁと思っています。
以下は検証結果です。パッチ前だと検索速度が落ちているものでも、ほとんど検索速度が落ちなくなっていることがわかります。
| Token:estimate size | N hits  | Normal     | MIN_ENABLE=1 | Normal (Patched) | MIN_ENABLE=1 (Patched) |
|--------------------------------------|---------|------------|------------------|------------------|----------------------------|
| データベ:378354 ベース:321365        | 376880  | 0.6064 sec | 0.7316 sec …
=> Reduce loop for seeking current chunk rid

doc/locale/ja/LC_MESSAGES/contribution.po
=> doc ja: translate

lib/proc/proc_select.c
ラベル付きドリルダウン関連のパラメータをselectのキャッシュに追加しました。
=> Add select cache related labeled drilldown

doc/locale/ja/LC_MESSAGES/install.po, doc/source/install/debian.rst
Related to https://github.com/groonga/groonga/issues/536#issuecomment-214616138.
=> doc install debian: Add limitations note for systemd in debian

lib/proc/proc_select.c, test/command/suite/select/drilldown/labeled/column/stage/initial/output_columns.expected, test/command/suite/select/drilldown/labeled/column/stage/initial/output_columns.test
#540 より分割
ドリルダウン結果でiniitalステージの動的カラムを作る分のコミットです。
=> select drilldown: support dynamic column creation as initial stage

lib/proc/proc_select.c
#540 より分割
動的カラムをソートしてからvalueを評価するコミットです。
今のところ、呼ばれる順序を気にする関数がなさそうなので、テストは書けませんでした。
=> select: support sort when create dynamic column

doc/source/news.rst
=> doc: Fix a typo

lib/expr.c, test/mruby/suite/expression_rewriter/test_and_order.rb, test/mruby/suite/expression_rewriter/test_between.rb, test/mruby/suite/query_optimizer/test_index.rb
scan_infoのinspectですが、indexが表示されていてほしいなと思いました。
=> inspect: add scan_info->index

lib/mrb/scripts/expression_tree.rb, lib/mrb/scripts/expression_tree/accessor.rb, lib/mrb/scripts/expression_tree/sources.am, lib/mrb/scripts/expression_tree_builder.rb, test/mruby/suite/expression_rewriter/test_between.rb
ExpressionTreeBuilderを通すためにExpressionTreeにAccessorを追加しました。
=> expression_tree: add Accessor

lib/proc/proc_select.c, test/command/suite/select/drilldowns/table/slice.expected, test/command/suite/select/drilldowns/table/slice.test
selectのsliceというものを試してみていて、sliceのテーブルをdrilldownで指定できるととても嬉しいなと思いました。
=> select drilldown: support target slice table

plugins/functions/string.c, test/command/suite/select/function/string/string_substring/ascii.expected, test/command/suite/select/function/string/string_substring/ascii.test, test/command/suite/select/function/string/string_substring/multibyte.expected, test/command/suite/select/function/string/string_substring/multibyte.test, test/command/suite/select/function/string/string_substring/no_length.expected, test/command/suite/select/function/string/string_substring/no_length.test
substrみたいな関数がほしいと思いました。いかがでしょうか？
1スタートです。
=> plugin string: add string_substring()

lib/ii.c
たまたま見つけて動作までは確認していないのですがtypoのように思いました。
=> ii_similar_search: fix typos

lib/mrb/mrb_bulk.c
``grn_mrb_value_to_bulk``をtime型のデータにも対応させたいです。
本体の実装でこの関数を通るタイミングがつかめておらず、テストは組めていませんが、
自前のexpression_rewriterプラグインではunsupported objectにならなくなるようになることを確認しています。
=> mrb: support to convert time of mrb_value to grn_bulk

lib/ii.c
grn_select_optarg->match_infoのNULLチェックを追加しました
=> Add NULL check for grn_select_optarg->match_info

lib/ii.c
@daijiro ここってreusedなチェックって必要そうですか！？
=> ii: add missing reused check

lib/expr.c, lib/ii.c, test/command/suite/select/filter/index/regexp/dot_asterisk.expected, test/command/suite/select/filter/index/regexp/dot_asterisk.test
=> Support index search for ".*" regexp pattern

test/command/suite/sharding/logical_select/cache/query.expected, test/command/suite/sharding/logical_select/cache/query.test
Confirm whether query parameter is changed, Groonga returns result
without using cache.
=> test: add query test case without cache

packages/windows/Makefile.am, packages/windows/Rakefile
Add feature uploading sources whitch used to build groonga.
=> Modify release script for windows.

lib/db.c
Before:
grn_table_select() ->
grn_obj_column("column1.column2") ->
grn_column_name() ->
"_key"
After:
grn_table_select() ->
grn_obj_column("column1.column2") ->
grn_column_name() ->
"column1.column2"
=> grn_column_name: return fully qualified name for accessor

plugins/functions/vector.c, test/command/suite/select/function/vector/vector_slice/int64_vector.expected, test/command/suite/select/function/vector/vector_slice/int64_vector.test
=> vector_slice: fix a bug that non 4 bytes vector columns can't slice

lib/dat.cpp, lib/ii.c, lib/io.c
It is needed to identify problem about vanished database files.
=> Add more delete operation logs

lib/geo.c
GitHub #613
This commit avoids crash bug.
=> Add null check of grn_ctx_at()'s return value in geo.c

vendor/mruby/Makefile.am, vendor/mruby/build_config.rb, vendor/mruby/built_sources.am, vendor/mruby/mruby_build.rb
grndb --force-truncate use Dir#foreach so, this PR enable mruby-dir for it.
=> mrb: enable mruby-dir for Dir#foreach

lib/mrb/scripts/command_line/grndb.rb
This option enable to recover corrupted object in database.
=> Add --force-truncate option for grndb

test/command/suite/load/minmax/int16_max.expected, test/command/suite/load/minmax/int16_max.test, test/command/suite/load/minmax/int16_min.expected, test/command/suite/load/minmax/int16_min.test, test/command/suite/load/minmax/int32_max.expected, test/command/suite/load/minmax/int32_max.test, test/command/suite/load/minmax/int32_min.expected, test/command/suite/load/minmax/int32_min.test, test/command/suite/load/minmax/int64_max.expected, test/command/suite/load/minmax/int64_max.test, test/command/suite/load/minmax/int64_min.expected, test/command/suite/load/minmax/int64_min.test, test/command/suite/load/minmax/int8_max.expected, test/command/suite/load/minmax/int8_max.test, test/command/suite/load/minmax/int8_min.expected, test/command/suite/load/minmax/int8_min.test, test/command/suite/load/minmax/uint16_max.expected, test/command/suite/load/minmax/uint16_max.test, test/command/suite/load/minmax/uint32_max.expected, test/command/suite/load/minmax/uint32_max.test, test/command/suite/load/minmax/uint8_max.expected, test/command/suite/load/minmax/uint8_max.test
TODO: max UInt64 test case may return unexpected result.
=> test: add load minmax test case

lib/ii.c
These commits fix a bug that a select cannot find phrases in vector columns (#494) by assigning inverted-index sections to vector elements.
=> Assign inverted-index sections to text vector elements

include/groonga/window_function.h, lib/window_function.c
I would like to get grn_window->n_ids.
=> Add grn_window_size

plugins/functions/time.c
=> functions/time: avoid divided by zero

lib/proc.c, test/command/suite/select/function/max/reference_vector_time.expected, test/command/suite/select/function/max/reference_vector_time.test, test/command/suite/select/function/max/vector_time.expected, test/command/suite/select/function/max/vector_time.test, test/command/suite/select/function/min/reference_vector_time.expected, test/command/suite/select/function/min/reference_vector_time.test, test/command/suite/select/function/min/vector_time.expected, test/command/suite/select/function/min/vector_time.test
I would like to retrieve number in`` grn_uvector`` with ``min`` and ``max``.
=> min,max: support number in vector

doc/source/news.rst
=> doc: add 7.0.7 entry

doc/source/news.rst
Added the following missing items.
* 50e24c86e2dc4b802e32b56c3ac390bff1587e91
* 0839cf6d3dc96ebd4e9c90c0ea5cdff33023d374
* b042a3227655c90cfb7d9955897596bb161c4278
=> doc: update 7.0.8 entry

plugins/functions/index_column.c
=> functions/index_column: add missing static

plugins/functions/index_column.c, test/command/suite/select/function/index_column/index_column_source_records/limit.expected, test/command/suite/select/function/index_column/index_column_source_records/limit.test
=> index_column_source_records: use object literal style option

doc/source/news.rst
Add detail information about groonga-server.
=> doc: update news

doc/locale/ja/LC_MESSAGES/news.po, doc/source/news.rst
ref: 58779cd70c9b2e473052b42a3cb976c450b37b53
=> doc: Add a note about dropped Ubuntu 17.04 to 7.1.1 news

include/groonga/ii.h, lib/ii.c
I added ii's log enhancements that not only token id but also output contents of a token.
=> ii: add log enhancements that output contents of a token

include/groonga/groonga.h, lib/logger.c, src/groonga.c
=> [WIP] logger: add log-flags option

plugins/functions/CMakeLists.txt
string and vector pdb files are exists, but time, number, index_column, math pdb files are missing
=> windows: install missing pdb files

appveyor.yml
build with VS2017, VS2015, VS2013.
=> appveyor: change build order

lib/dat.cpp, lib/db.c, lib/grn_util.h, lib/hash.c, lib/pat.c, lib/util.c, test/command/suite/load/command_version/3/output_ids/array.expected
It seems that there is a case unexpected error occurs but not correct error is not set.
=> table: add missing check for unexpected error case

.travis.yml, configure.ac, lib/Makefile.am, lib/mrb/Makefile.am, lib/proc/Makefile.am, plugins/suggest/Makefile.am, src/Makefile.am
This pull request for bundling LuaJIT in Groonga.
However, I think this pull request is not enough implementation.
=> Add support LuaJIT

lib/c_sources.am, lib/ctx.c, lib/ctx_impl_lua.c, lib/grn_ctx_impl.h, lib/grn_ctx_impl_lua.h
However, currently, this feature is just only initialized the lua vm
and remove the lua vm when groonga finish.
=> ctx: add support lua vm

lib/grn_io.h, lib/ii.c, lib/io.c, lib/store.c
=> Make enums UPPER_CASE for "grn_io_rw_mode"

lib/dat.cpp, lib/grn_io.h, lib/hash.c, lib/ii.c, lib/pat.c, lib/store.c, test/unit/core/test-inverted-index.c
=> Make enums UPPER_CASE for "grn_io_mode"

lib/grn_hash.h, lib/hash.c, lib/ii.c
=> Make enums UPPER_CASE for "grn_rec_unit"

lib/ii.c
=>  Make enums UPPER_CASE for "grn_wv_mode"

test/command/suite/sharding/logical_range_filter/filter/or_equals/optimization/select.expected, test/command/suite/sharding/logical_range_filter/filter/or_equals/optimization/select.test, test/command/suite/sharding/logical_range_filter/index/condition/range/min_exclude_max_exclude.test, test/command/suite/sharding/logical_range_filter/index/condition/range/min_exclude_max_include.test, test/command/suite/sharding/logical_range_filter/index/condition/range/optimization/min_exclude.expected, test/command/suite/sharding/logical_range_filter/index/condition/range/optimization/min_exclude.test, test/command/suite/sharding/logical_range_filter/index/condition/range/optimization/min_exclude_max_exclude.expected, test/command/suite/sharding/logical_range_filter/index/condition/range/optimization/min_exclude_max_exclude.test, test/command/suite/sharding/logical_range_filter/index/condition/range/optimization/min_exclude_max_include.expected, test/command/suite/sharding/logical_range_filter/index/condition/range/optimization/min_exclude_max_include.test, test/command/suite/sharding/logical_range_filter/order/descending.test, test/command/suite/sharding/logical_range_filter/order/optimization/descending.expected, test/command/suite/sharding/logical_range_filter/order/optimization/descending.test
Use #$GRN_EXPR_OPTIMIZE=yes/no explicitly for test case.
=> test: fix logical_range_filter test failure when GRN_EXPR_OPTIMIZE=yes

src/grnslap.c
=> Make enums UPPER_CASE for "flag_xxxx"

src/suggest/groonga_suggest_httpd.c
A part of a fix for issue #43.
=> Make enums UPPER_CASE for "run_mode"

appveyor.yml, packages/windows/download_appveyor_build.rb
It download artifacts files and rename to distinct filename.
=> windows: download appveyor release artifacts automatically

doc/source/example/tutorial/micro_blog_favorite.log
チュートリアルのマイクロブログでexampleが一つおかしかったので、`update_execution_example.py`で再出力しました。
=> doc: update an example in tutorial

src/groonga_benchmark.c
A part of a fix for issue #43.
=> Make enum UPPSER_CASE for "mode_xxx"

test/command/suite/select/match_columns/scorer/tf_at_most/or.expected, test/command/suite/select/match_columns/scorer/tf_at_most/or.test
=> test select match_columns scorer: add a test for OR

lib/db.c, test/command/suite/select/query/prefix_search/index_multiple.expected, test/command/suite/select/query/prefix_search/index_multiple.test
=> Fix a bug that doesn't use a suitable index

packages/ubuntu/upload.rb
=> packages ubuntu: make more robust archive detection

packages/Rakefile, packages/apt/debian-buster-i386/from, packages/apt/debian-buster/Dockerfile, packages/apt/debian-stretch-i386/from, packages/apt/debian-stretch/Dockerfile, packages/yum/centos-6/Dockerfile, packages/yum/centos-7/Dockerfile
It is aimed to replace current build process (Vagrant) for
CI in the future.
=> packages: add rake task for build deb,rpm packages

configure.ac, packages/yum/centos-8/Dockerfile, packages/yum/groonga.spec.in
Because of some *-devel packages are missing, just disable them for a
while.
=> packages yum: support CentOS 8

data/html/admin/assets/groonga-admin.ja.js, data/html/admin/assets/groonga-admin.js
Because a "tabs" has not "select" option in this jQuery version.
=> admin: use "option" instead of "select"

.github/workflows/linux-mingw.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/package.yml, .github/workflows/windows-mingw.yml, .github/workflows/windows-msvc.yml, packages/source/patches/mruby-do-not-check-fd-for-stdin-stdout-stderr.diff
=> ci: add a patch that don't check FD for STDIN/STDOUT/STDERR

lib/hash.c
GRN_DEFINE_NAME() is a more generic definition than grn_hash_name().
=> hash: use GRN_DEFINE_NAME() instead of grn_hash_name()

lib/table.c
This reduces needless parent _score check for one level
search (searching from a persistent table not a result set
table). Persistent tables should not have the GRN_OBJ_WITH_SUBREC
flag. Result set tables must have the flag.
=> grn_table_get_score: improve getting _score performance

lib/logger.c
We can specify "-" as --log-path/--query-log-path to output stdout and
"+" to output stderr.
This will be useful to run Groonga in Docker.
=> log-path, query-log-path: add support for outputting to stdout/stderr

doc/locale/ja/LC_MESSAGES/reference.po, doc/source/example/reference/functions/string_substring/usage_default.log, doc/source/example/reference/functions/string_substring/usage_negative.log, doc/source/example/reference/functions/string_substring/usage_number.log, doc/source/example/reference/functions/string_substring/usage_setup_data.log, doc/source/example/reference/functions/string_substring/usage_setup_schema.log, doc/source/example/reference/functions/string_substring/usage_string_literal.log, doc/source/reference/functions/string_substring.rst
=> Make a document for string_substring

.github/workflows/package.yml, packages/Rakefile, packages/yum/almalinux-8/Dockerfile, packages/yum/test.sh
=> packages yum: add a package for AlmaLinux 8

plugins/sharding/logical_range_filter.rb, plugins/sharding/stream_shard_executor.rb
Move apply_post_filter to StreamShardExecutor from ShardExecutor.
Related: https://github.com/groonga/groonga/pull/1341#discussion_r839303091
=> logical_range_filter: Move apply_post_filter to StreamShardExecutor from ShardExecutor

doc/locale/ja/LC_MESSAGES/contribution/development/release.po, doc/source/contribution/development/release.rst
Fix a process to update document in release.
The process was obsolete.
=> doc: Fix a process to update document in release

doc/source/reference/commands/select.rst
=> doc: Fix a typo for n_workers

doc/locale/ja/LC_MESSAGES/contribution/development/release.po, doc/source/contribution/development/release.rst
=> doc release: fix a typo

doc/locale/ja/LC_MESSAGES/install/almalinux.po, doc/source/install/almalinux.rst
Add description about installing AlmaLinux 9
=> doc: Add description about installing AlmaLinux 9

Makefile.am
Change to commit results of `make update-latest-release`.
=> release: commit results of update-latest-release

doc/locale/ja/LC_MESSAGES/news/13.po, doc/source/news/13.md
This news is described only summary.
I'll describe the detail of modification in this release to Groonga's blog.
=> doc: add 13.0.8 entry

include/groonga/id.h, include/groonga/obj.h, lib/id.c, lib/obj.c
Related `grn_obj_is_builtin` was also changed to return bool.
=> Change `grn_id_is_builtin` to return bool instead of grn_bool

include/groonga/id.h, include/groonga/type.h, lib/id.c, lib/type.c
Related changes to `grn_id_is_builtin_type`.
#1638
=> Change `grn_type_id_is_builtin` to return bool instead of grn_bool

include/groonga/obj.h, include/groonga/type.h, lib/obj.c, lib/type.c
Related changes to `grn_obj_is_number_family_bulk`.
#1638
=> Change `grn_type_id_is_number_family` to return bool instead of grn_bool

include/groonga/type.h, lib/obj.c, lib/type.c
=> Change `grn_type_id_is_text_family` to return bool instead of grn_bool

include/groonga/plugin.h, lib/plugin.c, lib/proc.c, lib/proc/proc_dump.c, lib/proc/proc_object.c, lib/proc/proc_table.c
The related codes were also changed.
#1638
=> Use bool instead of grn_bool in plugin.{h,c}

lib/window_function.c
=> Use bool instead of grn_bool in window_function.c

include/groonga/groonga.h, lib/logger.c, src/groonga.c
The related codes were also changed.
Removed unnecessary else and unnecessary assignments.
#1638
=> Change the return value of grn_log_level_parse from grn_bool to bool

include/groonga/groonga.h, lib/logger.c
=> Use bool instead of grn_bool in logger.c

lib/grn_util.h, lib/io.c, lib/util.c
I also changed the relevant code in io.c.
#1638
=> Use bool instead of grn_bool in util.c

include/groonga/db.h, include/groonga/obj.h, lib/dat.cpp, lib/db.c, lib/grn_dat.h, lib/grn_pat.h, lib/mrb/mrb_database.c, lib/pat.c
I also changed the related codes.
#1638
=> Change `grn_obj_is_dirty` to return bool instead of grn_bool

test/command/suite/normalizers/nfkc/unify_to_katakana/a.expected, test/command/suite/normalizers/nfkc/unify_to_katakana/a.test, test/command/suite/normalizers/nfkc/unify_to_katakana/ba.expected, test/command/suite/normalizers/nfkc/unify_to_katakana/ba.test, test/command/suite/normalizers/nfkc/unify_to_katakana/combining_katakana_hiragana_semi_voiced_sound_mark.expected, test/command/suite/normalizers/nfkc/unify_to_katakana/combining_katakana_hiragana_semi_voiced_sound_mark.test, test/command/suite/normalizers/nfkc/unify_to_katakana/combining_katakana_hiragana_voiced_sound_mark.expected, test/command/suite/normalizers/nfkc/unify_to_katakana/combining_katakana_hiragana_voiced_sound_mark.test, test/command/suite/normalizers/nfkc/unify_to_katakana/da.expected, test/command/suite/normalizers/nfkc/unify_to_katakana/da.test
* a.*
* ba.*
* combining_katakana_hiragana_semi_voiced_sound_mark.*
* combining_katakana_hiragana_voiced_sound_mark.*
* da.*
#1673
=> Re-add `unify_to_katakana` tests (`a.*` - `da.*`)

lib/group.c
=> Use bool instead of grn_bool in group.c

lib/expr.c
Removed unnecessary `else`.
#1638
=> Use bool instead of grn_bool in `is_index_searchable_regexp`

.github/workflows/benchmark.yml
=> Fix typo in .github/workflows/benchmark.yml

doc/source/contribution/documentation.rst, doc/source/contribution/documentation/c-api.rst, doc/source/contribution/documentation/i18n.rst, doc/source/contribution/documentation/introduction.rst
- Update the Sphinx documentation link
- ref: https://github.com/sphinx-doc/sphinx
=> doc: update Sphinx link

doc/locale/ja/LC_MESSAGES/contribution/documentation/introduction.po, doc/source/contribution/documentation/introduction.rst
I will add a new sections to the `introduction.rst` about the documentation update process.
=> Add `How to edit documentation` to contribution documentation guide

doc/locale/ja/LC_MESSAGES/contribution/documentation/introduction.po, doc/source/contribution/documentation/introduction.md
I will add a new sections to the `introduction.md` about the documentation update process.
=> doc contribution/documentation: previews modifications on HTML

doc/locale/ja/LC_MESSAGES/contribution/documentation/introduction.po, doc/source/contribution/documentation/introduction.md
=> doc contribution/documentation: add how to submit contribution to doc contribution guide

doc/locale/ja/LC_MESSAGES/reference/tokenizers/token_ngram.po, doc/source/reference/tokenizers/token_ngram.rst, lib/tokenizers.c, test/command/suite/tokenizers/ngram/ignore_blank.expected, test/command/suite/tokenizers/ngram/ignore_blank.test
https://github.com/groonga/groonga/discussions/1759#discussioncomment-9111340
長年追加されてないから不要なのかな。
=> Enable `ignore_blank` option in TokenNgram

doc/locale/ja/LC_MESSAGES/contribution/documentation/introduction.po, doc/source/contribution/documentation/introduction.md
=> doc contribution/documentation: translate how to send patch on doc contribution guide

doc/source/example/reference/tokenizers/token-table-schema.log, doc/source/reference/tokenizers/token_delimit.rst, doc/source/reference/tokenizers/token_table.rst
* Add missing `"`
* Add missing `,`
=> docs: Fix the query examples

.github/workflows/cmake.yml, .github/workflows/package.yml, .gitmodules, packages/Rakefile, packages/packages-groonga-org-package-task.rb
=> Remove vendor/apache-arrow-source

Rakefile, doc/Doxyfile
* EXTRACT_ALL = YES
* Generate all documents anyway, even if there are no comments
* INPUT = include/
* Only under include/
* RECURSIVE = YES
* It also searches for files in subdirectories
* GENERATE_LATEX = NO
* LaTeX files are not generated
GtiHub: GH-1817
=> doxygen: Set up to generate documents for members under include/

doc/locale/ja/LC_MESSAGES/reference/api/grn_type.po, doc/source/reference/api/grn_type.rst, include/groonga/type.h
=> docs: api/grn_type: Move the contents of the reference to a header file

doc/source/reference/api/grn_table.rst, include/groonga/table.h
=> docs: api/grn_table: Move the grn_table_add() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_table.po, doc/locale/ja/LC_MESSAGES/reference/api/grn_table_cursor.po
When the `.rst` file was updated, the update was omitted.
Automatically updated by `cmake --build`.
=> docs: Update `.po` files

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, include/groonga/groonga.h
=> docs api/grn_obj: move the grn_obj_column() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, include/groonga/obj.h
=> docs api/grn_obj: move grn_obj_is_builtin() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_table.po, doc/source/reference/api/grn_table.rst, include/groonga/groonga.h, include/groonga/table.h
=> docs: api/grn_table: Move the get() and at() reference to the header file

include/groonga/groonga.h, include/groonga/table.h
It will be a link when the document is generated by Doxygen.
=> docs: Add `\ref` to `GRN_SUCCESS`

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, lib/obj.c
=> docs: api/grn_obj: move grn_obj_is_index_column() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, include/groonga/obj.h
=> docs api/grn_obj: move grn_obj_is_vector_column() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, include/groonga/groonga.h
=> doc api/grn_obj: move grn_obj_get_value() reference to the header file

tools/generate-alphabet-diacritical-mark.rb
Used to implement a normalizer.
Related: GH-1891, GH-1755
=> tools: Add a script to generate alphabet diacritical mark

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, include/groonga/groonga.h
=> docs api/grn_obj: move grn_obj_get_values() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, include/groonga/groonga.h
=> docs api/grn_obj: move grn_obj_set_value() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_table.po, doc/source/reference/api/grn_table.rst, include/groonga/table.h
=> docs: api/grn_table: move grn_table_delete_by_id() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, include/groonga/groonga.h
=> docs api/grn_obj: move grn_obj_close() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_table.po, doc/source/reference/api/grn_table.rst, include/groonga/table.h
=> docs: api/grn_table: move grn_table_difference() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, include/groonga/groonga.h
=> docs api/grn_obj: move grn_obj_reinit() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_table.po, doc/source/reference/api/grn_table.rst, include/groonga/table.h
=> docs: api/grn_table: move grn_table_truncate() reference to the header file

doc/locale/ja/LC_MESSAGES/contribution/documentation/introduction.po, doc/source/conf.py, doc/source/contribution/documentation/introduction.md
close: https://github.com/groonga/groonga/issues/1733
ref: https://github.com/groonga/groonga/pull/1732
=> doc contribution/documentation: add an outline

doc/locale/ja/LC_MESSAGES/reference/api/grn_table.po, doc/source/reference/api/grn_table.rst, include/groonga/table.h
=> docs: api/grn_table: move grn_table_setoperation() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_table.po, doc/source/reference/api/grn_table.rst, include/groonga/table.h
=> docs: api/grn_table: move grn_table_lcp_search() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, include/groonga/groonga.h
=> docs: api/grn_obj: move grn_obj_get_range() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_match_escalation.po, doc/source/reference/api/grn_match_escalation.rst, include/groonga/groonga.h
=> docs: api/grn_match_escalation: move grn_*_match_escalation_threshold() reference to the header file

include/groonga/groonga.h
Fix the format in https://github.com/groonga/groonga/pull/1973.
=> Fix the style using '\' instead of '@'

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, include/groonga/groonga.h
=> docs: api/grn_obj: move grn_obj_check() reference to the header file

include/groonga/language_model.h
=> language_model.h: Fix the typo

doc/locale/ja/LC_MESSAGES/reference/api/grn_db.po, doc/source/reference/api/grn_db.rst, include/groonga/db.h
=> docs: api/grn_db: move grn_db_touch() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_db.po, doc/source/reference/api/grn_db.rst, include/groonga/db.h
=> docs: api/grn_db: move grn_db_(create|open) reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, include/groonga/groonga.h
=> docs: api/grn_obj: move grn_obj_clear_lock() reference to the header file

.github/workflows/cmake.yml
=> package: windows: Add `vcomp140.dll` to with-vcruntime package

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, include/groonga/groonga.h
=> docs: api/grn_obj: move grn_obj_is_locked() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_proc.po, doc/source/reference/api/grn_proc.rst, include/groonga/groonga.h
=> docs: api/grn_proc: move grn_obj_set_finalizer() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_proc.po, doc/source/reference/api/grn_proc.rst, include/groonga/proc.h
=> docs: api/grn_proc: move grn_proc_create() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, include/groonga/groonga.h
=> docs: api/grn_obj: move grn_obj_unlink() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, include/groonga/groonga.h
=> docs: api/grn_obj: move grn_obj_is_defrag() reference to the header file

src/groonga.c
Since it is used as a bool, change it to bool.
=> bin/groonga: Use bool instead of int

doc/locale/ja/LC_MESSAGES/install/centos.po, doc/locale/ja/LC_MESSAGES/install/others.po, doc/locale/ja/LC_MESSAGES/server/package.po, doc/source/install/centos.rst, doc/source/install/others.rst, doc/source/server/package.rst
=> docs: Update documentation, since dropped CentOS support

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, include/groonga/groonga.h
=> docs: api/grn_obj: move grn_obj_id() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, include/groonga/groonga.h
=> docs: api/grn_obj: move grn_obj_delete_by_id() reference to the header file

doc/locale/ja/LC_MESSAGES/install/cmake.po, doc/source/install/cmake.rst
GitHub: GH-2007
The build and installation was also changed to use CMake.
=> docs: install/cmake: Add a description of the presets

.github/workflows/autotools.yml, .github/workflows/cmake.yml, .github/workflows/setup.yml, setup.sh
OSes that use DNF such as AlmaLinux will be supported separately.
Related: GitHub: GH-2017
=> setup.sh: Add support for macOS

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, include/groonga/groonga.h
=> docs: api/grn_obj: move grn_obj_path_by_id() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_ctx.po, doc/source/reference/api/grn_ctx.rst, include/groonga/groonga.h
=> docs: api/grn_ctx: move grn_ctx_is_opened() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_proc.po, doc/source/reference/api/grn_proc.rst, include/groonga/proc.h
=> docs: api/grn_proc: move grn_proc_get_info() reference to the header file

doc/locale/ja/LC_MESSAGES/install/almalinux.po, doc/locale/ja/LC_MESSAGES/install/amazon_linux.po, doc/locale/ja/LC_MESSAGES/install/cmake.po, doc/locale/ja/LC_MESSAGES/install/debian.po, doc/locale/ja/LC_MESSAGES/install/mac_os_x.po, doc/locale/ja/LC_MESSAGES/install/ubuntu.po, doc/locale/ja/LC_MESSAGES/install/windows.po, doc/source/install/almalinux.rst, doc/source/install/amazon_linux.rst, doc/source/install/cmake.md, doc/source/install/debian.rst, doc/source/install/mac_os_x.rst, doc/source/install/ubuntu.md, doc/source/install/windows.rst
=> docs: install: Update how to build from source code

doc/locale/ja/LC_MESSAGES/reference/api/grn_obj.po, doc/source/reference/api/grn_obj.rst, include/groonga/cast.h
=> docs: api/grn_obj: move grn_obj_cast() reference to the header file

doc/source/reference/api/grn_obj.rst, include/groonga/groonga.h
=> docs: api/grn_obj: move grn_obj reference to the header file

lib/output.c
GitHub: Related: GH-2031
Prepare to fix the output of `records`.
The output of the content was implemented in grn_output_table_records_content().
=> output: grn_output_table_records_v1: Separate open and content

doc/locale/ja/LC_MESSAGES/reference/api/grn_column.po, doc/source/reference/api/grn_column.rst, include/groonga/column.h
=> docs: api/grn_column: move `GRN_COLUMN_NAME_ID_LEN` reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_column.po, doc/source/reference/api/grn_column.rst, include/groonga/column.h
=> docs: api/grn_column: move GRN_COLUMN_NAME_VALUE{,_LEN} reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_column.po, doc/source/reference/api/grn_column.rst, include/groonga/column.h
=> docs: api/grn_column: move GRN_COLUMN_NAME_SCORE{,_LEN} reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_column.po, doc/source/reference/api/grn_column.rst, include/groonga/column.h
=> docs: api/grn_column: move GRN_COLUMN_NAME_NSUBRECS{,_LEN} reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_column.po, doc/source/reference/api/grn_column.rst, include/groonga/column.h, include/groonga/groonga.h
=> docs: api/grn_column: move `grn_column_create()` reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_ctx.po, doc/source/reference/api/grn_ctx.rst, include/groonga/groonga.h
=> docs: api/grn_ctx: move grn_ctx_(set|get)_command_version() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_column.po, doc/source/reference/api/grn_column.rst, include/groonga/column.h
=> docs: api/grn_column: move grn_column_index_update() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_ctx.po, doc/source/reference/api/grn_ctx.rst, include/groonga/groonga.h
=> docs: api/grn_ctx: move grn_ctx_db() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_column.po, doc/source/reference/api/grn_column.rst, include/groonga/column.h
=> docs: api/grn_column: move grn_column_table reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_column.po, doc/source/reference/api/grn_column.rst, include/groonga/groonga.h
=> docs: api/grn_column: move grn_column_rename reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_column.po, doc/source/reference/api/grn_column.rst, include/groonga/groonga.h
=> docs: api/grn_column: move grn_column_name reference to the header file

CMakeLists.txt, config.h.cmake.in, vendor/download.rb
GitHub: GH-1820
Preparing to implement HNSW with USearch.
=> cmake: Add USearch to dependent libraries

doc/locale/ja/LC_MESSAGES/reference/api/grn_ctx.po, doc/source/reference/api/grn_ctx.rst, include/groonga/groonga.h
=> docs: api/grn_ctx: move grn_ctx_(open|close) reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_column.po, doc/source/reference/api/grn_column.rst, include/groonga/column.h
=> docs: api/grn_column: move grn_column_truncate reference to the header file

lib/pat.c
=> grn_pat_size: Return 0 if `pat` is `NULL`

doc/locale/ja/LC_MESSAGES/reference/api/grn_ctx.po, doc/source/reference/api/grn_ctx.rst, include/groonga/groonga.h
=> docs: api/grn_ctx: move grn_ctx_set_finalizer() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_geo.po, doc/source/reference/api/grn_geo.rst, include/groonga/geo.h
=> docs: api/grn_geo: move grn_geo_select_in_rectangle() reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_geo.po, doc/source/reference/api/grn_geo.rst, include/groonga/geo.h
=> docs: api/grn_geo: move grn_geo_estimate_size_in_rectangle() reference to the header file

.github/workflows/autotools.yml, .github/workflows/benchmark.yml, .github/workflows/cmake.yml, .github/workflows/document.yml, .github/workflows/lint.yml, .github/workflows/package.yml, .github/workflows/setup.yml
We can use GitHub Actions on fork by this.
=> ci: enable workflows for all pushes

lib/db.c, lib/pat.c
To not allow other processes to touch it.
=> pat: defrag: Lock with GRN_TABLE_LOCK_BEGIN()

doc/locale/ja/LC_MESSAGES/reference/api/grn_ctx.po, doc/source/reference/api/grn_ctx.rst, include/groonga/groonga.h
=> docs: api/grn_ctx: move grn_ctx_at() reference to the header file

.github/workflows/cmake.yml, .github/workflows/document.yml, .github/workflows/package.yml, .github/workflows/release.yml
GitHub: groonga/packages.groonga.org#43
This PR introduces a part of new release workflow. This release workflow handles the followings.
- Download the uploaded artifacts.
- Upload the release artifacts to release page.
=> ci release: upload release source, packages, or documents

.github/workflows/package.yml
This is for https://github.com/groonga/packages.groonga.org/blob/main/ansible/files/home/packages/tasks/repository-task.rb .
=> ci release package: group by distribution+version

.pre-commit-config.yaml, lib/nfkc.c
In the list of files, "normalizer.c" starting with "n" is also sorted with it.
=> clang-format: add lib/nfkc.c

.github/workflows/document.yml, cmake/GroongaSphinx.cmake
Add `--fail-on-warning` option so that it will fail on warning as well.
=> docs: build: Change to fail with `sphinx-build` warnings

doc/source/example/reference/normalizers/normalizer-nfkc-katakana-gu-small-sounds.rst, doc/source/example/reference/normalizers/normalizer-nfkc-remove-symbol.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-hyphen-and-prolonged-sound-mark.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-hyphen.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-kana-case-hiragana.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-kana-case-katakana.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-kana-hyphen.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-kana-prolonged-sound-mark.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-kana.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-katakana-bu-sounds.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-katakana-di-sound.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-katakana-du-small-sounds.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-katakana-du-sound.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-katakana-trailing-o.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-katakana-v-sounds.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-katakana-wo-sound.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-katakana-zu-small-sounds.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-latin-alphabet-with.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-middle-dot.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-prolonged-sound-mark.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-to-katakana.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-to-romaji-complex.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-to-romaji.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-voiced-sound-mark-hiragana.rst, doc/source/example/reference/normalizers/normalizer-nfkc-unify-voiced-sound-mark-katakana.rst, doc/source/example/reference/normalizers/normalizer-nfkc.rst, doc/source/reference/normalizers/normalizer_nfkc.rst
Files under `doc/source/example/` are automatically generated by `ninja doc_update_examples`.
=> docs: NormalizerNFKC: Update the execution examples

doc/files.am, doc/files.cmake, doc/locale/ja/LC_MESSAGES/reference/normalizers/normalizer_nfkc.po, doc/source/example/reference/normalizers/normalizer-nfkc-version.rst, doc/source/reference/normalizers/normalizer_nfkc.rst
`ninja doc_update_files` executed.
=> docs: NormalizerNFKC: Add an example of `version` option

doc/files.am, doc/files.cmake, doc/locale/ja/LC_MESSAGES/reference/token_filters/token_filter_nfkc.po, doc/source/example/reference/token_filters/nfkc-unify-hyphen.rst, doc/source/example/reference/token_filters/nfkc-unify-kana.rst, doc/source/example/reference/token_filters/nfkc-unify-to-romaji.rst, doc/source/example/reference/token_filters/nfkc-version.rst, doc/source/example/reference/token_filters/nfkc-with-token-mecab.rst, doc/source/example/reference/token_filters/nfkc.rst, doc/source/reference/token_filters/token_filter_nfkc.rst
Files under `doc/source/example/` are automatically generated by `ninja doc_update_examples`.
=> docs: TokenFilterNFKC: Update the execution examples

doc/locale/ja/LC_MESSAGES/news/15.po, doc/source/news/15.md
GitHub: GH-2227
This is a release note for Groonga 15.0.1.
=> docs: add 15.0.1 entry

doc/locale/ja/LC_MESSAGES/reference/api/grn_thread.po, doc/source/reference/api/grn_thread.rst, include/groonga/thread.h
=> docs: api/grn_thread move grn_thread_(get|set)_limit reference to the  header file

doc/locale/ja/LC_MESSAGES/reference/api/plugin.po, doc/source/reference/api/plugin.rst, include/groonga/plugin.h
=> docs: api/plugin: move grn_plugin_mutex_open() reference to the header file

lib/proc/proc_dump.c, lib/proc/proc_schema.c
=> Fix the typo "mesage"

lib/nfkc.rb
inconsitent ->
inconsistent
This is extracted from https://github.com/MariaDB/server/pull/3963.
=> NFKC generator: Fix a typo

lib/hash.c, lib/pat.c
=> Fix a typo in the function name

doc/locale/ja/LC_MESSAGES/reference/api/grn_expr.po, doc/source/reference/api/grn_expr.rst
=> docs: api/grn_expr update reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_ii.po, doc/source/reference/api/grn_ii.rst
=> docs: api/grn_ii update reference to the header file

doc/files.am, doc/files.cmake, doc/locale/ja/LC_MESSAGES/reference/commands/tokenize.po, doc/source/example/reference/commands/tokenize/output_style/full.log, doc/source/example/reference/commands/tokenize/output_style/simple.log, doc/source/reference/commands/tokenize.rst
=> docs commands/tokenize: add `output_style` option

doc/locale/ja/LC_MESSAGES/reference/commands/table_tokenize.po, doc/source/reference/commands/table_tokenize.rst
=> docs commands/table_tokenize: add output_style option

doc/locale/ja/LC_MESSAGES/news/15.po, doc/source/news/15.md
=> docs: add 15.0.8 entry

doc/locale/ja/LC_MESSAGES/reference/api/grn_inspect.po, doc/source/reference/api/grn_inspect.rst, include/groonga/util.h
=> docs: api/grn_inspect move grn_inspect reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_inspect.po, doc/source/reference/api/grn_inspect.rst, include/groonga/util.h
=> docs: api/grn_inspect move grn_inspect_indented reference to the header file

lib/pat.c
=> pat_node: put comment before member

doc/locale/ja/LC_MESSAGES/reference/api/grn_inspect.po, doc/source/reference/api/grn_inspect.rst, include/groonga/util.h
=> docs: api/grn_inspect move grn_inspect_limited reference to the header file

.github/workflows/benchmark.yml
It automatically installs dependent libraries.
=> ci: benchmark: Utilize `rubygems-requirements-system`

doc/locale/ja/LC_MESSAGES/reference/api/grn_inspect.po, doc/source/reference/api/grn_inspect.rst, include/groonga/util.h
=> docs: api/grn_inspect move grn_inspect_name reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_inspect.po, doc/source/reference/api/grn_inspect.rst, include/groonga/util.h
=> docs: api/grn_inspect move grn_inspect_encoding reference to the header file

doc/locale/ja/LC_MESSAGES/reference/api/grn_inspect.po, doc/source/reference/api/grn_inspect.rst, include/groonga/util.h
=> docs: api/grn_inspect move grn_inspect_type reference to the header file

doc/source/reference/commands/logical_select.rst
=> docs: reference/commands/logical_select: Remove trailing-whitespace

lib/pat.c
Aligned with grn_pat_total_key_size().
This commit is part of the work to implement #2349.
=> pat: use more suitable function and argument name

doc/source/news/12.rst
=> docs: news/12: Remove trailing-whitespace

doc/source/contribution/documentation/i18n.rst, doc/source/reference/commands/column_create.rst, doc/source/reference/executables/groonga.rst, doc/source/reference/grn_expr/script_syntax.rst, doc/source/reference/suggest/suggestion.rst
=> docs: Remove trailing-whitespace

doc/locale/ja/LC_MESSAGES/reference/command/return_codes/grn_no_such_file_or_directory.po, doc/source/reference/command/return_codes/grn_no_such_file_or_directory.rst, doc/source/reference/commands/compress_filter.rst
=> docs: Fix an unbalanced inline literal markup

doc/locale/ja/LC_MESSAGES/reference/api/grn_thread.po, doc/source/reference/api/grn_thread.rst, include/groonga/thread.h
=> docs: api/grn_inspect move grn_thread_set_get_limit_func reference to the header file

lib/pat.c
=> pat: use pat_node_common instead of pat_node in search_push

data/travis/setup.sh
* Add the required package
* libarrow-compute-dev
* Update to latest installation steps
* https://groonga.org/docs/install/debian.html#bookworm
* https://groonga.org/docs/install/ubuntu.html
=> Update Groonga install script for CI

lib/pat.c
=> pat: use pat_node_common instead of pat_node in longest common prefix search

lib/pat.c
=> pat: use pat_node_common instead of pat_node in set_cursor_prefix

lib/pat.c
=> pat: use pat_node_common instead of pat_node in set_cursor_near

lib/pat.c
=> pat: use more suitable function and variable name

lib/pat.c
pat_node_set_key() is not use since this commit.
So, I replace this function.
=> pat: use pat_node_common instead of pat_node in grn_pat_delete_with_sis()

lib/pat.c
=> pat: commonalize computation of need number of bits to express a entry size

lib/proc/proc_command_list.c, test/command/suite/command_list/all.expected
=> command_list: show argument names

lib/grn_language_model.hpp, lib/language_model.cpp, test/command/suite/select/function/language_model_vectorize/huggingface.expected, test/command/suite/select/function/language_model_vectorize/huggingface.test
URL:
* `hf:///${USER}/${MODEL}`
* Example: `hf:///groonga/bge-m3-Q4_K_M-GGUF` for https://huggingface.co/groonga/bge-m3-Q4_K_M-GGUF
* `hf:///${USER}/${MODEL}#${TAG}`
* Example: `hf:///Qwen/Qwen3-Embedding-8B-GGUF#Q8_0` for Q8_0 tag of https://huggingface.co/Qwen/Qwen3-Embedding-8B-GGUF
=> language-model: add support for auto download from Hugging Face
